Generals/Code/GameEngine/CMakeLists.txt
Generals/Code/Libraries/Source/WWVegas/WWDownload/CMakeLists.txt

Match the file names in CMakeLists with the casing of the actual files, for case sensitive systems. This also matches the corresponding CMakeLists in GeneralsMD.

Fix filename casings in CMakeLists for case-sensitive systems.

---

scripts/cpp/fixInludesCase.sh

This adds shell script, I have used, to fix file name case in includes, based on comment in given PR: https://github.com/TheSuperHackers/GeneralsGameCode/pull/347#issuecomment-2742519675
I have just finished some cleanup/polishing to it, before publishing it. I prefer this as separate PR as not to mix changes to includes with possible changes to this script. Also it is easier for someone to experiment with it (if interested), when not applied on top of changeset, with includes already fixed. For more details about script see `printHelp` function.
Example usage:
```
./scripts/cpp/fixInludesCase.sh \
-I GeneralsMD/Code/Libraries/Include \
-I GeneralsMD/Code/GameEngine/Include \
-I GeneralsMD/Code/GameEngine/Include/Precompiled \
-I GeneralsMD/Code/Libraries/Source/WWVegas \
-I …
```

Added script to fix file name case in includes

---

Generals/Code/GameEngine/Include/Common/STLTypedefs.h

Copy the fixes that were made in the zero hour code by Xezon.
This fixes as fatal error at startup that prevents the game from starting.

[Gen] Fix incorrect AsciiString hash implementation for non-stlport

---

CMakeLists.txt
GeneralsMD/Code/Libraries/Source/debug/debug.h
GeneralsMD/Code/Libraries/Source/profile/profile_funclevel.cpp

* Fixes #490
This change fixes compile errors in the profile library. It also makes it compile with the `_DEBUG` and `_INTERNAL` builds - to avoid linker errors and make it flexible.

[ZH] Fix compilation errors in profile library

---

CMakeLists.txt
resources/CMakeLists.txt
resources/visualstudio/asciistring.natvis
resources/visualstudio/stllist.natvis
resources/visualstudio/stlvector.natvis
resources/visualstudio/unicodestring.natvis

This change adds natvis files for AsciiString, UnicodeString, _STL::_List_base, _STL::_Vector_base. Taken from Thyme. It allows to properly inspect these types in the Visual Studio debugger. Most useful for the game string classes. The STL ones are for stlport and are not really essential for us, but it does not hurt to have them.

Add natvis for AsciiString, UnicodeString, _STL::_List_base, _STL::_Vector_base

---

Generals/Code/Main/CMakeLists.txt

The CMakeList file for generals vanilla contains the major and minor version. Probably a copy-paste error from Zero-Hour, the minor version is 4, instead of 9.
As Generals Vanilla uses the version in the CRC executable check, this causes a mismatch when joining a multiplayer. This PR changes the minor version to 9.

[GEN] Fix incorrect minor version

---

Generals/Code/GameEngine/Include/Common/STLTypedefs.h
GeneralsMD/Code/GameEngine/Include/Common/STLTypedefs.h

* Merge after #426
This error causes the game to crash early with non-stlport builds. The reason is that the hash impl for stlport does not work with the standard/new std::hash.

[GEN][ZH] Fix incorrect AsciiString hash implementation for non-stlport

---

CMakeLists.txt
Generals/Code/GameEngine/Include/Common/GameMemory.h
Generals/Code/GameEngine/Source/Common/System/GameMemory.cpp
GeneralsMD/Code/GameEngine/Include/Common/GameMemory.h
GeneralsMD/Code/GameEngine/Source/Common/System/GameMemory.cpp
cmake/config.cmake

* Addresses #530
This change adds cmake configurability for MemoryPool features and debugs and disables the slow stack trace debug by default. It also fixes a small compile error with one of the MemoryPool debugs that was turned off previously.
With this change, debug builds are usable.
This change also moves config stuff into a separate cmake file. It is a separate commit.
Callstack of slow stack trace:
```
ntdll.dll!_RtlpFreeHeapInternal@20()	Unknown
ntdll.dll!RtlFreeHeap()	Unknown
KernelBase.dll!776b0c03()	Unknown
[Frames below may be incorrect and/or missing, no symbols loaded for KernelBase.dll]	
ucrtbase.dll!77a23c3b()	Unknown
ucrtbase.dll!77a23bb1()	Unknown
ucrtbase.dll!77a23b7f()	Unknown
dbghelp.dll!SymRowImage::~SymRowImage(void)	Unknown …
```

[GEN][ZH] Add cmake configurability for MemoryPool features and debugs, disable slow stack trace

---

Dependencies/Utility/Utility/intrin_compat.h
GeneralsMD/Code/GameEngine/Include/Common/PerfTimer.h
GeneralsMD/Code/GameEngine/Include/Common/crc.h
GeneralsMD/Code/GameEngine/Source/Common/PerfTimer.cpp
GeneralsMD/Code/Libraries/Include/Lib/BaseType.h
GeneralsMD/Code/Libraries/Include/Lib/intrin_compat.h
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dx8wrapper.h
GeneralsMD/Code/Libraries/Source/WWVegas/WWDebug/CMakeLists.txt
GeneralsMD/Code/Libraries/Source/WWVegas/WWDebug/wwdebug.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WWDebug/wwdebug.h
GeneralsMD/Code/Libraries/Source/WWVegas/WWDebug/wwprofile.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WWLib/CMakeLists.txt
GeneralsMD/Code/Libraries/Source/WWVegas/WWLib/Except.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WWLib/TARGA.CPP
GeneralsMD/Code/Libraries/Source/WWVegas/WWLib/cpudetect.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WWLib/lcw.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WWLib/mpu.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WWLib/mutex.h
GeneralsMD/Code/Libraries/Source/WWVegas/WWMath/vector3.h
GeneralsMD/Code/Libraries/Source/profile/CMakeLists.txt
GeneralsMD/Code/Libraries/Source/profile/internal.h
GeneralsMD/Code/Tools/timingTest/timingTest.cpp

This change replaces most inline assembler for Zero Hour, but VS6 builds will still use the legacy inline assembler everywhere.
This change is required to run the VS2022 c++20 build without crashes.
This change was put together by reference changes from https://github.com/Fighter19/CnC_Generals_Zero_Hour and user Mauller.
TODO:
- ~~Provide better macros (*1)~~
- ~~Add code comments where necessary~~
(*1) 
`#if defined(_MSC_VER) && _MSC_VER < 1300` -> `#define VS6_BUILD 1`
`#if defined(_MSC_VER) && defined(_M_IX86)` -> `#define MSC_X86_BUILD 1`
`#if defined (_WIN32) && !defined (_WIN64)` -> `#define WIN32_BUILD 1`

[ZH] Replace inline assembler for non VS6 builds

---

Generals/Code/GameEngine/Include/Common/PerfTimer.h
Generals/Code/Libraries/Include/Lib/BaseType.h
Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8wrapper.h
Generals/Code/Libraries/Source/WWVegas/WWDebug/CMakeLists.txt
Generals/Code/Libraries/Source/WWVegas/WWDebug/wwdebug.h
Generals/Code/Libraries/Source/WWVegas/WWDebug/wwprofile.cpp
Generals/Code/Libraries/Source/WWVegas/WWLib/CMakeLists.txt
Generals/Code/Libraries/Source/WWVegas/WWLib/cpudetect.cpp
Generals/Code/Libraries/Source/WWVegas/WWLib/lcw.cpp
Generals/Code/Libraries/Source/WWVegas/WWLib/mpu.cpp
Generals/Code/Libraries/Source/WWVegas/WWMath/vector3.h
Generals/Code/Tools/timingTest/timingTest.cpp

This replaces the inline ASM in non VS6 builds that causes crashing during running of the application.
This is a combination of code suggestions by myself and fixes by xezon.
This fix doesn't include other ASM changes seen in the Zero hour ASM change, this only resolves ASM that is causing crashes.

[GEN] Replace inline assembler for non VS6 builds

---

Generals/Code/GameEngine/Include/Common/GameAudio.h
Generals/Code/GameEngine/Include/Common/GameSounds.h
Generals/Code/GameEngine/Source/Common/Audio/GameAudio.cpp
Generals/Code/GameEngine/Source/Common/Audio/GameSounds.cpp
GeneralsMD/Code/GameEngine/Include/Common/GameAudio.h
GeneralsMD/Code/GameEngine/Include/Common/GameSounds.h
GeneralsMD/Code/GameEngine/Source/Common/Audio/GameAudio.cpp
GeneralsMD/Code/GameEngine/Source/Common/Audio/GameSounds.cpp

What happens here is that `addAudioEvent` can delete the passed pointer (there even is a EA comment), but the caller then does nothing if that happens and keeps using that pointer.
This happens right on game boot.

[GEN][ZH] Fix Invalid memory access in AudioManager::addAudioEvent

---

Generals/Code/Libraries/Source/WWVegas/WW3D2/render2dsentence.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/render2dsentence.cpp

This is a classic new/delete mismatch.
```
==3032==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x1b9647fc at pc 0x01820201 bp 0x0097f0d8 sp 0x0097f0cc
READ of size 4 at 0x1b9647fc thread T0
==3032==WARNING: Failed to use and restart external symbolizer!
#0 0x01820200 in FontCharsClass::~FontCharsClass D:\Projects\TheSuperHackers\GeneralsGameCode\GeneralsMD\Code\Libraries\Source\WWVegas\WW3D2\render2dsentence.cpp:1223
#1 0x01821159 in FontCharsClass::`scalar deleting destructor'+0x29 (C:\Generals\English\Command & Conquer Generals Zero Hour\generals.exe+0xf71159)
#2 0x01526b46 in RefCountClass::Delete_This D:\Projects\TheSuperHackers\GeneralsGameCode\GeneralsMD\Code\Libraries\Source\WWVegas\WWLib\RefCount.h:166
#3 0x0179931e in WW3DAssetManager::Release_All_FontChars …
```

[GEN][ZH] Fix heap-buffer-overflow, new/delete mismatch in FontCharsClass::~FontCharsClass

---

Generals/Code/GameEngineDevice/Source/Win32Device/Common/Win32BIGFileSystem.cpp
GeneralsMD/Code/GameEngineDevice/Source/Win32Device/Common/Win32BIGFileSystem.cpp

Checking filename index after using it is no good.
```
==16248==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x020fa947 at pc 0x013440f9 bp 0x020fa918 sp 0x020fa918
READ of size 1 at 0x020fa947 thread T0
==16248==WARNING: Failed to use and restart external symbolizer!
#0 0x013440f8 in Win32BIGFileSystem::openArchiveFile D:\Projects\TheSuperHackers\GeneralsGameCode\GeneralsMD\Code\GameEngineDevice\Source\Win32Device\Common\Win32BIGFileSystem.cpp:159
#1 0x01343a8a in Win32BIGFileSystem::loadBigFilesFromDirectory D:\Projects\TheSuperHackers\GeneralsGameCode\GeneralsMD\Code\GameEngineDevice\Source\Win32Device\Common\Win32BIGFileSystem.cpp:222
#2 0x0134366c in Win32BIGFileSystem::init D:\Projects\TheSuperHackers\GeneralsGameCode\GeneralsMD\Code\GameEngineDevice\Source\Win32Device\ …
```

[GEN][ZH] Fix stack-buffer-underflow in Win32BIGFileSystem::openArchiveFile

---

Generals/Code/GameEngine/Source/GameClient/MessageStream/HotKey.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/HotKey.cpp

We cannot pass a pointer to a wchar_t and treat it as a string. It may not be 0 terminated!
```
==23980==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x017ef62a at pc 0x565b75e2 bp 0x017ef5d0 sp 0x017ef1b0
READ of size 8 at 0x017ef62a thread T0
==23980==WARNING: Failed to use and restart external symbolizer!
#0 0x565b75e1 in wcslen D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\sanitizer_common\sanitizer_common_interceptors.inc:7199
#1 0x0052bcc0 in UnicodeString::set D:\Projects\TheSuperHackers\GeneralsGameCode\GeneralsMD\Code\GameEngine\Source\Common\System\UnicodeString.cpp:176
#2 0x00bd3e7d in HotKeyTranslator::translateGameMessage D:\Projects\TheSuperHackers\GeneralsGameCode\GeneralsMD\Code\GameEngine\Source\GameClient\MessageStream\HotKey.cpp:103
#3 0x005268fe in …
```

[GEN][ZH] Fix stack-buffer-overflow in HotKeyTranslator::translateGameMessage

---

Generals/Code/GameEngine/Include/Common/Player.h
Generals/Code/GameEngine/Source/Common/RTS/Player.cpp
Generals/Code/GameEngine/Source/Common/RTS/PlayerList.cpp
GeneralsMD/Code/GameEngine/Include/Common/Player.h
GeneralsMD/Code/GameEngine/Source/Common/RTS/Player.cpp
GeneralsMD/Code/GameEngine/Source/Common/RTS/PlayerList.cpp

* ~~Possibly related to #21~~
In `PlayerList::reset`, the `TheTeamFactory` is cleared. This will delete teams. But the players still keep a raw pointer to those teams and will use them on destruction. To avoid this trouble, we clean up the `AIPlayer` of the `Player` before we delete the teams.
~~There is a chance that this problem is related to the surrender mismatch, because here we have undefined behaviour before transfering units from one player to another player inside the team.~~
```
==18160==ERROR: AddressSanitizer: heap-use-after-free on address 0x4ef8a841 at pc 0x0022390e bp 0x016fe9fc sp 0x016fe9f0
READ of size 1 at 0x4ef8a841 thread T0
==18160==WARNING: Failed to use and restart external symbolizer!
#0 0x0022390d in Team::setActive …
```

[GEN][ZH] Fix heap-use-after-free in TeamInQueue::~TeamInQueue

---

GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp

When playing back replays, the game checks the CRC stored in the replay with the CRC calculated from memory. When a mismatch occurs, the game warns the user about it. Or at least until this message was commented out:
```
//Kris: Patch 1.01 November 10, 2003 (integrated changes from Matt Campbell)
// Since we don't seem to have any *visible* desyncs when replaying games, but get this warning
// virtually every replay, the assumption is our CRC checking is faulty.  Since we're at the
// tail end of patch season, let's just disable the message, and hope the users believe the
// problem is fixed. -MDC 3/20/2003
//TheInGameUI->message("GUI:CRCMismatch");
```
This PR reenables that message and fixes the underlying issue, which is actually two issues:
- In Multiplayer (not in Singleplayer …

[ZH] Fix Replay CRC Checking

---

.github/workflows/ci.yml

Change CI to only cancel in-progress jobs for pull requests. 
This should allow all jobs related to pushes to main to complete irrespective of concurrency.

[GitHub] Cancel in-progress jobs only for pull requests

---

.gitignore

CLion throws out a `cmake-build-$target/` directory in various places that could pollute the repository. Using Ninja with CLion creates numerous `build.ninja` files across the tree.
This commit fixes those two problems for developers using these tools to avoid accidentally committing those files.

[Git] Expand gitignore to include CLion / JetBrains IDEs

---

Generals/Code/Libraries/Source/WWVegas/WWLib/CMakeLists.txt
Generals/Code/Libraries/Source/WWVegas/WWLib/rcfile.cpp
Generals/Code/Libraries/Source/WWVegas/WWLib/rcfile.h
GeneralsMD/Code/Libraries/Source/WWVegas/WWLib/CMakeLists.txt
GeneralsMD/Code/Libraries/Source/WWVegas/WWLib/rcfile.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WWLib/rcfile.h

* Follow up for #581
This partially reverts commit 931d1051c376c4980780e2bb596cdb6ddbeb44c4

[GEN][ZH] Readd WWVegas/WWLib/rcfile.cpp for w3dview

---

Generals/Code/GameEngine/Source/Common/Recorder.cpp

* Relates to #566
* Follow up for #545
This change replicates the `Fix Replay CRC Checking` from ZH as created by @helmutbuhler.

[GEN] Fix Replay CRC Checking

---

Generals/Code/GameEngine/CMakeLists.txt
Generals/Code/GameEngine/Include/Common/GameMemory.h
Generals/Code/GameEngine/Include/Common/GameMemoryNull.h
Generals/Code/GameEngine/Source/Common/System/GameMemoryNull.cpp
Generals/Code/Libraries/Source/WWVegas/WWLib/always.h
GeneralsMD/Code/GameEngine/CMakeLists.txt
GeneralsMD/Code/GameEngine/Include/Common/GameMemory.h
GeneralsMD/Code/GameEngine/Include/Common/GameMemoryNull.h
GeneralsMD/Code/GameEngine/Source/Common/System/GameMemoryNull.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WWLib/always.h
cmake/config.cmake

This change adds a game memory replacement without memory pools.
Everything that is not called by user code is stripped away in the null implementation.
`new`/`delete` overloads still exist, because right now we do require zero memset for allocations. Disabling the zero memset will cause the game to crash in various places that forgot to zero initialize critical variables, such as pointers, that we would need to fix before being able to get rid of zero memset.
This change unlocks established memory debugs, such as Asan, and performance comparisons of game memory pools vs system heap allocator.

[GEN][ZH] Add optional game memory null replacement

---

Generals/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBar.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Contain/MobNexusContain.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Contain/OpenContain.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Contain/OverlordContain.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TransportContain.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/PartitionManager.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/RailroadGuideAIUpdate.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBar.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/MobNexusContain.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/OpenContain.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/OverlordContain.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/TransportContain.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/PartitionManager.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/RailroadGuideAIUpdate.cpp

Throughout the code there are various iterators in loops that are expecting to break the loop when the end iterator returns null.
Std lib iterators do not work like this and require an explicit check against the end iterator.
There are also other code blocks that attempt to use iterators even if the container is empty, this is undefined behaviour within std lib as the start iterator of an empty container is invalid.
Some checks are also trying to get an iterator and expecting an empty iterator to signal that a conditional should not be entered. This needs to be corrected by validating that the iterator can be obtained first.
- Related to: #563

[GEN][ZH] Fix stlport iterator use to conform with STL

---

Generals/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptEngine.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptEngine.cpp

The script engines stored a copy of the previous iterator to determine if it was stuck within a loop.
The issue is that when the container for the scripts is modified, this previous iterator becomes invalidated with std lib style iterators.
To correct this and replicate the behaviour that Stl port style iterators would have, i instead store the value of the data pointed at by the previous iterator and compare that to the data pointed at by the current iterator.
This correction is required for Debug to work, it also removes any unexpected behaviour that may happen.
- Related to: #563

[GEN][ZH] Fix invalidated iterator access in ScriptEngine::evaluateAndProgressAllSequentialScripts

---

Generals/Code/GameEngine/Include/Common/GlobalData.h
Generals/Code/GameEngine/Include/Common/ThingTemplate.h
Generals/Code/GameEngine/Source/Common/GlobalData.cpp
GeneralsMD/Code/GameEngine/Include/Common/GlobalData.h
GeneralsMD/Code/GameEngine/Include/Common/ThingTemplate.h
GeneralsMD/Code/GameEngine/Source/Common/GlobalData.cpp

[GEN][ZH] Fix compiler warnings for uninitialized variables in copy constructors

---

Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp

The old bump mapped water was loading and tripping ASAN on my system during debug.
It was mentioned to me that this code is not normally entered so players do not see the bump mapped water normally.

[GEN] Compile out unused bump mapped water

---

Generals/Code/GameEngine/Include/Common/ThingTemplate.h
Generals/Code/GameEngine/Include/GameLogic/ObjectTypes.h
GeneralsMD/Code/GameEngine/Include/Common/ThingTemplate.h
GeneralsMD/Code/GameEngine/Include/GameClient/GameClient.h
GeneralsMD/Code/GameEngine/Include/GameLogic/GameLogic.h
GeneralsMD/Code/GameEngine/Include/GameLogic/ObjectTypes.h

I managed to grab the lowest hanging fruit with the least number of changes to knock out 1500 warnings.
Fixing the types on these headers shaved 1/4 of the build time off.
Generals does not have an equivalent to change in GameLogic or GameClient.

[GEN][ZH] Correct the most egregious signed / unsigned mismatch warnings

---

Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp

* Closes #563
This change refactors GameLogic::rebalanceChildSleepyUpdate to avoid the "vector subscript out of range" debug error. Functionality wise nothing changes. In release this is no bug.

[GEN][ZH] Refactor GameLogic::rebalanceChildSleepyUpdate to avoid "vector subscript out of range" debug error

---

Generals/Code/GameEngine/Source/Common/System/AsciiString.cpp
Generals/Code/GameEngine/Source/Common/System/UnicodeString.cpp
Generals/Code/Libraries/Source/WWVegas/WWLib/trim.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/AsciiString.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/UnicodeString.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WWLib/trim.cpp

The two commits here correct some functionality that was causing ASAN to trigger on startup.
The source and destination buffers, according to ASAN, have overlapping memory regions meaning the copy would be unsafe to perform.
The solution and safe way to do this, if it was intended, such as shuffling characters along in a buffer, you should use memmove.
memmove is used in other parts of the code base as well so has compat with VC6.
To see this you must have the null memory implementation in use and ASAN running.
EDIT: Updated to include Unicode and wide character string trim.

[GEN][ZH] Fix incorrect string copy with overlapping memory regions in AsciiString, UnicodeString, strtrim

---

Generals/Code/Main/WinMain.cpp
Generals/Code/Tools/MapCacheBuilder/Source/WinMain.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/CMakeLists.txt
GeneralsMD/Code/Libraries/Source/WWVegas/WWLib/CMakeLists.txt
GeneralsMD/Code/Main/WinMain.cpp
GeneralsMD/Code/Tools/MapCacheBuilder/Source/WinMain.cpp
GeneralsMD/Code/Tools/buildVersionUpdate/CMakeLists.txt
GeneralsMD/Code/Tools/buildVersionUpdate/buildVersionUpdate.cpp
GeneralsMD/Code/Tools/textureCompress/CMakeLists.txt
GeneralsMD/Code/Tools/textureCompress/textureCompress.cpp
GeneralsMD/Code/Tools/versionUpdate/CMakeLists.txt
GeneralsMD/Code/Tools/versionUpdate/versionUpdate.cpp

- Depends on: #615 
This PR mostly unifies the strtrim implementation across the various applications that use strtrim.
The trim.h header has been used to include the wwlib variant of trim directly, local variants that were present have been removed.
~~For some tools that don't include the relevant library, the local implementation has been updated to match the implementation of strtrim in trim.cpp.~~

[GEN][ZH] Remove duplicate strtrim implementations

---

.github/ISSUE_TEMPLATE/bug-report.yaml
.github/workflows/ci.yml
.github/workflows/valid-tags.txt
.github/workflows/validate-pull-request.yml

This pull request adds a new housekeeping workflow that validates that "tags" e.g. [GEN]/[GITHUB], if used in PR titles and commit messages are valid tags.
The list of valid tags is loaded from: `.github/workflows/valid-tags.txt`
- ✅ [GEN] Added a bug for fun. Let’s see if anyone notices.
- ✅ [GEN][ZH] Did some magic, code works now.
- ✅ Renamed all variables to ‘foo’ for consistency.
- ❌ [zh] Reverted everything because I was feeling nostalgic.
- Not uppercase
- ❌ [ZEROHOUR] Refactored the entire project to improve… my mood.
- Invalid tag
- ❌ [ZH][GENERALS] Tried to fix one bug, created two new ones.
- Invalid tag
- ❌ [ZH]:I wrote the code, now it’s your turn to debug it.
- Tags must be followed by at least one space
Other changes:
* …

[GITHUB] Add PR title and commit message validation workflow

---

Generals/Code/Tools/Compress/CMakeLists.txt
Generals/Code/Tools/Compress/Compress.cpp
GeneralsMD/Code/Tools/Compress/CMakeLists.txt
GeneralsMD/Code/Tools/Compress/Compress.cpp

This change decouples the Compress tool from CRCDiff. It does so by getting rid of the CRCDiff/Debug.h include. This means it loses the `OutputDebugString` call in Debug, but that should be of no major concern. The logging inside tools may need another pass entirely.

[GEN][ZH] Decouple Compress from CRCDiff

---

Generals/Code/Libraries/Source/WWVegas/WW3D2/CMakeLists.txt
Generals/Code/Libraries/Source/WWVegas/WW3D2/assetmgr.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/assetstatus.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/assetstatus.h
Generals/Code/Libraries/Source/WWVegas/WW3D2/ringobj.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/ringobj.h
Generals/Code/Libraries/Source/WWVegas/WW3D2/sphereobj.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/sphereobj.h

We don't care for code diffs in the RenderObj classes because they are safe to copy over as asset manager didn't call Register_Prototype_Loader on _RingLoader or _SphereLoader so these chunks wouldn't had worked in Generals at all.

[GEN] Backport WW3D2's ringobj, sphereobj, assetstatus from Zero Hour

---

Generals/Code/Libraries/Source/WWVegas/WWMath/CMakeLists.txt
Generals/Code/Libraries/Source/WWVegas/WWMath/matrix3d.cpp
Generals/Code/Libraries/Source/WWVegas/WWMath/matrix3d.h
Generals/Code/Libraries/Source/WWVegas/WWMath/vector3.h
GeneralsMD/Code/Libraries/Source/WWVegas/WWMath/CMakeLists.txt
GeneralsMD/Code/Libraries/Source/WWVegas/WWMath/matrix3d.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WWMath/matrix3d.h
GeneralsMD/Code/Libraries/Source/WWVegas/WWMath/vector3.h

* Relates to #602
This change fixes compile errors with ALLOW_TEMPORARIES in WWMath.
ALLOW_TEMPORARIES unlocks math functions which are industry standard for vectors and matrices.

[GEN][ZH] Fix compile errors with ALLOW_TEMPORARIES in WWMath

---

Generals/Code/Libraries/Source/WWVegas/WW3D2/CMakeLists.txt
Generals/Code/Libraries/Source/WWVegas/WW3D2/static_sort_list.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/static_sort_list.h
Generals/Code/Libraries/Source/WWVegas/WW3D2/ww3d.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/ww3d.h

Functionally wise this is exactly the same as original General's code before this change. The Zero Hour specific additions to StaticSortListClass are not ported.

[GEN] Backport WW3D2's StaticSortListClass from Zero Hour

---

Generals/Code/Libraries/Source/WWVegas/WWLib/RAWFILE.H
Generals/Code/Libraries/Source/WWVegas/WWLib/mempool.h
Generals/Code/Libraries/Source/WWVegas/WWLib/rawfile.cpp
Generals/Code/Libraries/Source/WWVegas/WWLib/trim.cpp
Generals/Code/Libraries/Source/WWVegas/WWLib/widestring.cpp
Generals/Code/Libraries/Source/WWVegas/WWLib/widestring.h
Generals/Code/Libraries/Source/WWVegas/WWLib/wwstring.cpp
Generals/Code/Libraries/Source/WWVegas/WWLib/wwstring.h

This puts WWLib of Generals in line with Zero Hour.
* mempool : ObjectPoolClass<T,BLOCK_SIZE> now has locks for alloc and free
* rawfile : Brings over the changes of #627
* trim : trim functions now check if character is <= 32 instead of `isspace()`, `iswspace()`
* widestring : now uses FastCriticalSectionClass instead of CriticalSectionClass
* widestring : adds checks for null argument in some functions
* widestring : adds new functions
* wwstring : now uses FastCriticalSectionClass instead of CriticalSectionClass
* wwstring : adds checks for null argument in some functions
* wwstring : adds new functions

[GEN] Backport changes of mempool, rawfile, trim, widestring, wwstring from Zero Hour

---

Core/Libraries/Source/EABrowserDispatch/BrowserDispatch.idl
Core/Libraries/Source/EABrowserEngine/BrowserEngine.idl
Dependencies/Utility/Utility/CppMacros.h
Generals/Code/GameEngine/Include/GameNetwork/WOLBrowser/WebBrowser.h
Generals/Code/GameEngine/Source/Common/GameEngine.cpp
Generals/Code/GameEngine/Source/GameNetwork/WOLBrowser/WebBrowser.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DWebBrowser.cpp
GeneralsMD/Code/GameEngine/Include/GameNetwork/WOLBrowser/WebBrowser.h
GeneralsMD/Code/GameEngine/Source/Common/GameEngine.cpp
GeneralsMD/Code/GameEngine/Source/GameNetwork/WOLBrowser/WebBrowser.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DWebBrowser.cpp

COM related fixes to be able to build using MinGW. 
- fixes to idl files to be able to build using [widl](https://gitlab.winehq.org/wine/wine/-/wikis/Man-Pages/widl)
- fixes to c++ to be able to build using mingw toolchain + [atl](https://github.com/reactos/reactos/tree/master/sdk/lib/atl) library from reactos sdk (MinGW itself does not include atl)
This was extracted from bigger change-set fixing build on MinGW: https://github.com/TheSuperHackers/GeneralsGameCode/pull/547

[GEN][ZH] Fix COM related compile errors for MinGW

---

Core/CMakeLists.txt
Core/Tools/Compress/CMakeLists.txt

The compress tool currently does not build without Zero Hour:
```
D:\Projects\TheSuperHackers\GeneralsGameCode\Core\Tools\Compress\Compress.cpp(21,10): error C1083: Cannot open include file: 'Lib/BaseTypeCore.h': No such file or directory
```
This change makes it independent of Zero Hour and fixes the problem.

[CORE] Fix Compress tool build error

---

Dependencies/Utility/Utility/intrin_compat.h

Fixes of problems in intrin_compat (with MinGW):
- added check for definition of `_rdtsc` after inclusion of `<intrin.h>`, before defining it as inline func. (GCC/Mingw [header](https://github.com/gcc-mirror/gcc/blob/962c3d69f189f6fa451153faf3ce261c50d23d5a/gcc/config/i386/ia32intrin.h#L313)  already defines `_rdtsc` as alias for `__rdtsc`)
- use of `intrin.h` should be consistent  and depend `_WIN32` everywhere (rather than on `_MSC_VER` in some places) to avoid problems on MinGW
This was extracted from bigger change-set fixing build on MinGW: https://github.com/TheSuperHackers/GeneralsGameCode/pull/547

Fix intrin_compat.h to work for MinGW

---

GeneralsMD/Code/GameEngine/Include/GameClient/GameClient.h
GeneralsMD/Code/GameEngine/Include/GameLogic/GameLogic.h
GeneralsMD/Code/GameEngine/Source/GameClient/GameClient.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp

This PR changes zero hour so it uses hashmaps for the Object and Drawable lookup tables, the same as it was in Generals and how it also is in other SAGE games.
I have also added debug asserts to both games into the ```GameLogic::removeObjectFromLookupTable``` function, the drawables equivalent in GameClient will be added with other required fixes in PR #657.

[ZH] Use hash maps for Object and Drawable lookups in GameClient, GameLogic like Generals does

---

Generals/Code/Libraries/Source/WWVegas/WWDebug/wwdebug.cpp
Generals/Code/Libraries/Source/WWVegas/WWDebug/wwdebug.h
Generals/Code/Libraries/Source/WWVegas/WWDebug/wwmemlog.cpp
Generals/Code/Libraries/Source/WWVegas/WWDebug/wwmemlog.h
Generals/Code/Libraries/Source/WWVegas/WWDebug/wwprofile.cpp
Generals/Code/Libraries/Source/WWVegas/WWDebug/wwprofile.h
Generals/Code/Libraries/Source/WWVegas/WWLib/CMakeLists.txt
Generals/Code/Libraries/Source/WWVegas/WWLib/FastAllocator.cpp
Generals/Code/Libraries/Source/WWVegas/WWLib/FastAllocator.h
GeneralsMD/Code/Libraries/Source/WWVegas/WWDebug/wwdebug.h

This change backports all remaining WWDebug changes to wwdebug, wwmemlog, wwprofile from Zero Hour to Generals. WWLib has FastAllocator added because it is a dependency in WWDebug.
Changes
* wwdebug : increases printing buffers from 1024 to 4096 bytes
* wwdebug : adds functionality to exit process on assertion fail
* wwmemlog : adds functionality to enable/disable memlog
* wwmemlog : adds new memory logging categories
* wwmemlog : improves performance of memlog by replacing mutex with critical section
* wwprofile : adds functionality to enable/disable profiler
* wwprofile : implements new profile log systems

[GEN] Backport WWDebug changes to wwdebug, wwmemlog, wwprofile from Zero Hour

---

Generals/Code/GameEngine/Include/GameLogic/Module/BehaviorModule.h
Generals/Code/GameEngine/Include/GameLogic/Module/StealthUpdate.h
Generals/Code/GameEngine/Include/GameLogic/Object.h
Generals/Code/GameEngine/Source/Common/RTS/Player.cpp
Generals/Code/GameEngine/Source/Common/System/Radar.cpp
Generals/Code/GameEngine/Source/GameClient/Drawable.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBar.cpp
Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp
Generals/Code/GameEngine/Source/GameLogic/AI/AIGroup.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Contain/MobNexusContain.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Contain/OpenContain.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Object.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/PartitionManager.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Update/SpecialAbilityUpdate.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Update/StealthDetectorUpdate.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Update/StealthUpdate.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/WeaponSet.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/Common/System/W3DRadar.cpp

This is backported from change done in ZH, shouldn't break any replays or saves.

[GEN] Store StealthUpdate pointer in the Object class to avoid module lookups

---

Generals/Code/GameEngine/Include/Common/CRCDebug.h
Generals/Code/GameEngine/Include/Common/Xfer.h
Generals/Code/GameEngine/Source/Common/CRCDebug.cpp
Generals/Code/GameEngine/Source/Common/CommandLine.cpp
Generals/Code/GameEngine/Source/Common/System/Debug.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Object.cpp
Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp
Generals/Code/GameEngine/Source/GameNetwork/Network.cpp

* Resolves #690
* Follow up for #544
This change replicates #544 on Generals.
Replicated with
```
git diff c47c20265e86b2c9cf28747aeb9048ac9db26b55..34107c5743c8533543f41dc59995cb5766f3181c > changes.patch
git apply -p2 --directory=Generals --reject --whitespace=fix changes.patch
```

[GEN] Improve CRC Logging Debug Functionality

---

Generals/Code/GameEngine/Include/Common/Science.h
Generals/Code/GameEngine/Include/Common/SparseMatchFinder.h
Generals/Code/GameEngine/Include/GameLogic/RankInfo.h
Generals/Code/GameEngine/Source/Common/GlobalData.cpp
Generals/Code/GameEngine/Source/Common/MiniLog.cpp
Generals/Code/GameEngine/Source/Common/RTS/Science.cpp
Generals/Code/GameEngine/Source/Common/System/Debug.cpp
Generals/Code/GameEngine/Source/Common/System/Xfer.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBar.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarCommand.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarCommandProcessing.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarMultiSelect.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/SkirmishGameOptionsMenu.cpp
Generals/Code/GameEngine/Source/GameClient/Input/Mouse.cpp
Generals/Code/GameEngine/Source/GameLogic/Map/TerrainLogic.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/DozerAIUpdate.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/WorkerAIUpdate.cpp
Generals/Code/GameEngine/Source/GameLogic/System/RankInfo.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTruckDraw.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DBibBuffer.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DBridgeBuffer.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3dWaypointBuffer.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarCommand.cpp
GeneralsMD/Code/GameEngine/Source/GameNetwork/GameSpy/Thread/BuddyThread.cpp

Partial split from #688
- ZH BuddyThread.cpp fixes string assignment
- ControlBar.cpp fixes invalid science vector access, fixes memory leak on rightHUDCameoWindow, adds various null checks
- ControlBarCommand.cpp adds various null checks
- ControlBarCommandProcessing.cpp adds various null checks
- ControlBarMultiSelect.cpp adds various null checks
- Debug.cpp adds various null checks
- DozerAIUpdate.cpp - fixes out of bounds crash on invalid task id
- GlobalData.cpp - fixes dangling TheWritableGlobalData pointer
- MiniLog.cpp - fixes crash when m_fp is null
- Mouse.cpp - fixes crash when m_cursorTextDisplayString is null
- RankInfo.cpp - fixes memory leak
- RankInfo.h
- Science.cpp - fixes memory leak
- Science.h
- SkirmishGameOptionsMenu.cpp adds various null checks
- …

[GEN] Backport various crash and memory fixes from Zero Hour

---

Generals/Code/Libraries/Source/WWVegas/WW3D2/part_buf.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/part_buf.h
Generals/Code/Libraries/Source/WWVegas/WW3D2/part_emt.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/part_emt.h

Needed for W3DView, afaict this shouldn't affect any behaviors so hopefully this doesn't backport the reason particles are broken in ZH version
Line Group code isn't ported over yet so this code won't be functional as TailPosition remains NULL

[GEN] Backport BlurTime functionality in WW3D2's ParticleBufferClass

---

Generals/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DAssetManager.h
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DVolumetricShadow.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DAssetManager.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DScene.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DTerrainVisual.cpp
GeneralsMD/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DAssetManager.h
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DVolumetricShadow.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DAssetManager.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DScene.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DTerrainVisual.cpp

This PR removes code blocks for granny based file support that were conditionally included.
It also makes small refactors in some places where the granny code was coupled with non granny code in W3DAssetManager.
There is still some granny referencing code within W3DAssetManger, but this is in a commented out block of functions from Earth and Beyond at the end of the file. I left these blocks untouched, apart from removing the conditional block, to be looked at another time.
Changes:
- Remove and refactor blocks for supporting granny code in W3DAssetManager.
- Remove conditional blocks for granny from W3DScene and W3DTerrainVisual.
- Remove commented out granny affiliated code from W3DVolumetricShadow and correct comment on Iterator.

[GEN][ZH] Remove unused granny related code

---

Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8wrapper.cpp

This change ports a piece of code to WW3D2 that will load a dds file if a tga file under the same name was not found. This avoids pink textures from failed texture loads.

[GEN] Backport loading DDS file if TGA file of the same name was not found

---

Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/TerrainTex.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/assetmgr.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/assetmgr.h
Generals/Code/Libraries/Source/WWVegas/WW3D2/ddsfile.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8wrapper.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8wrapper.h
Generals/Code/Libraries/Source/WWVegas/WW3D2/part_emt.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/surfaceclass.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/texture.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/texture.h
Generals/Code/Libraries/Source/WWVegas/WW3D2/textureloader.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/ww3d.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/ww3d.h
Generals/Code/Libraries/Source/WWVegas/WW3D2/ww3dformat.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/ww3dformat.h
Generals/Code/Tools/WorldBuilder/src/wbview3d.cpp

This change refactors texture related code in WW3D2 to come closer to the implementation of Zero Hour. It does not change behaviour.

[GEN] Bring texture related code in WW3D2 closer to Zero Hour

---

GeneralsMD/Code/GameEngine/Include/GameClient/GameClient.h
GeneralsMD/Code/GameEngine/Include/GameLogic/GameLogic.h
GeneralsMD/Code/GameEngine/Source/GameClient/GameClient.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp

* Closes #734
* Resolves #733
This change reverts #676 because it unexpectedly introduces mismatch with retail game.

Revert "[ZH] Use hash maps for Object and Drawable lookups in GameClient, GameLogic like Generals does (#676)"

---

Core/CMakeLists.txt
Generals/CMakeLists.txt
GeneralsMD/CMakeLists.txt
cmake/config-build.cmake

This change fixes the CMake error on the first generation.
```
...
CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/VC/vcpkg/scripts/buildsystems/vcpkg.cmake:598 (_add_executable):
No SOURCES given to target: g_mapcachebuilder
Call Stack (most recent call first):
Generals/Code/Tools/MapCacheBuilder/CMakeLists.txt:1 (add_executable)
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
It happens because some RTS_GENERALS_* and RTS_ZEROHOUR_* related cmake options are created after they are used in Core.
This change creates all RTS cmake options before using them.

[CMAKE] Move all RTS cmake options into early config-build.cmake to prevent cmake error on first generation

---

Generals/Code/Libraries/Source/WWVegas/WW3D2/assetmgr.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8caps.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8caps.h
Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8list.h
Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8texman.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8texman.h
Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8wrapper.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8wrapper.h
Generals/Code/Libraries/Source/WWVegas/WW3D2/dynamesh.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/matpass.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/seglinerenderer.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/seglinerenderer.h
Generals/Code/Libraries/Source/WWVegas/WW3D2/shattersystem.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/sortingrenderer.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/static_sort_list.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/streakRender.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/streakRender.h
Generals/Code/Libraries/Source/WWVegas/WW3D2/texture.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/texture.h
Generals/Code/Libraries/Source/WWVegas/WW3D2/ww3d.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/ww3d.h

This change ports some WW3D2 code from Zero Hour to Generals.
It includes a few performance optimizations among a lot of refactors and render feature additions.
* dx8caps : Adds device format support checks
* dx8texman : Does texture class abstraction
* dx8texman : Adds depth stencil texture tracking and abstraction
* dx8wrapper : Adds shader system updates
* dx8wrapper : Fixes missing deletion of CurrentCaps in DX8Wrapper::Do_Onetime_Device_Dependent_Shutdowns
* dx8wrapper : Fixes busy cpu when game window is minimized
* dx8wrapper : Adds additional draw calls counters to debug statistics
* dx8wrapper : Adds MESH_RENDER_SNAPSHOT_ENABLED logging
* dynamesh : Adds second texture stage support
* seglinerenderer : Adds diffuse color support
* seglinerenderer : Optimizes segline render …

[GEN] Backport more of WW3D2 from Zero Hour

---

Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GameClient.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp

Merge by rebase
This change reverts #645 and adds a range based check on the removal functions for the object and drawable lookup tables.
- Closes: #761

[GEN][ZH] Revert #645 and add out of range check on object and drawable vector based lookup tables

---

Generals/Code/GameEngine/Source/GameClient/GameClient.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GameClient.cpp

This PR resets the drawable ID within `GameClient::reset()` so it does not keep growing over the lifetime of the game. The implication of uncapped growth is that the `GameClient::m_drawableVector` will keep growing as well.
EDIT: This PR has been heavily modified over time and now only resets the DrawableID
~~Within GameClient::reset the lookup tables were being cleared before their relevant drawables were removed from them.
This was causing out of range container errors similar to what was seen in GameLogic::reset.~~
~~destroyDrawable was also reordered so that the drawable was removed from the lookup table before being destroyed in the drawable list.~~
~~This PR reverts some earlier changes made when zero hour was using a vector as a lookup table and resets the drawable ID in …

[GEN][ZH] Reset DrawableID on map load to avoid massive id growth over the lifetime of the game

---

Generals/Code/GameEngine/Source/GameLogic/Object/GhostObject.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/GhostObject.cpp

In VS6 assigning a float to a bool results in the compiler using uninitialized memory to assign the bool.
This member got initialized in Generals 1.08 to 192, in Zero Hour 1.04 to 72.
Intended value seems to be false, however, the correct way to not break any compatibility is to set this to true.
In the future it should be investigated if it's safe to set it to false.
Fixing this now like this ensures it's always not 0, where's keeping it doesn't guarantee VS6 may not in fact set it to 0 on some build

[GEN][ZH] Fix incorrectly initialized bool GhostObject::m_parentGeometryIsSmall

---

.github/workflows/build-toolchain.yml
.github/workflows/ci.yml
CMakePresets.json

* Follow up for #605
* Build Binaries with NMake
* Build Profiling Binaries with NMake
* Build Internal Binaries with NMake
* Build Debug Binaries with NMake
* Windows 32bit build
* Windows 32bit Profile build
* Windows 32bit Internal build
* Windows 32bit Debug build
* Non-Windows build
* Windows 32bit VC6 Release
* Windows 32bit VC6 Profile
* Windows 32bit VC6 Internal
* Windows 32bit VC6 Debug
* Windows 32bit Release
* Windows 32bit Profile
* Windows 32bit Internal
* Windows 32bit Debug
* Windows 32bit VCPKG Release
* Windows 32bit VCPKG Profile
* Windows 32bit VCPKG Internal
* Windows 32bit VCPKG Debug
* Unix 32bit VCPKG Release
"Windows 32bit VC6" and "Windows 32bit" no longer use VCPKG as their tool chain, because they do not need it to work.

[CMAKE] Remove vcpkg toolchain from default windows cmake presets and add new cmake presets with vcpkg toolchain

---

Generals/Code/GameEngine/Source/GameLogic/Object/Update/StealthUpdate.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/StealthUpdate.cpp

This fix was originally discovered by @helmutbuhler and split out of the original PR it was contained in.
This fix corrects the behaviour where when the drawable was not being set for a new visual disguise on a stealth unit.
The call to get the new drawable was not being handled correctly and was not updating the draw variable.
This would have resulted in a memory leak, possible use after free and unexpected behaviour with stealthing units.
- Relates https://github.com/TheSuperHackers/GeneralsGameCode/pull/716

[GEN][ZH] Fix drawable assignment in StealthUpdate::changeVisualDisguise()

---

Generals/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/DockUpdate.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/DockUpdate.cpp

This fix was originally discovered by @helmutbuhler and split out of the original PR it was contained in.
This fix initiallises an array that is used immediately but not all of the bins are updated with data.
This can result in random contents being included instead of being zeroed.
- Relates https://github.com/TheSuperHackers/GeneralsGameCode/pull/716

[GEN][ZH] Fix uninitialized memory read in DockUpdate::loadDockPositions

---

Generals/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/MissileAIUpdate.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/MissileAIUpdate.cpp

This problem was originaly discovered by @helmutbuhler and has been split out of the original PR.
This commit corrects iterator usage to conform with STL iterator behaviour instead of STLport behaviours.
- Closes #716

[GEN][ZH] Fix iterator usage in projectileHandleCollision functions

---

Generals/Code/GameEngine/Source/GameLogic/AI/AIPlayer.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIPlayer.cpp

When running Debug, there are instances where the varaible ```CPP supplyTruck``` will cause a runtime exception due to being uninitialised.
From current testing, the behaviour appears to be that with the value set to False, we can consistantly desync a game with retail.
As the variables is uninitialised, there is a higher chance of it being a non-zero value, resulting in it being considered true in retail.
This needs some further testing and discussion to determine if we set the value to True for now and correct it later, or just set a value in debug only and leave it uninitialised in retail.
- Relates To: #632

[GEN][ZH] Fix uninitialized supplyTruck variable in AiPlayer::onUnitProduced()

---

Generals/Code/GameEngine/Source/GameLogic/AI/AIPathfind.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIPathfind.cpp

**Merge by rebase**
Some uninitialised variables throw, use before initialised type, variable exceptions during Debug.
For most of them, default initialisation to zero is fine, for the Clasify fence, partially-initialised Iregion2D cellbounds variable, i have done my best to deduce the correct way to initialise it based on prior code in generals and rationalising what the function is doing.
For the cellbounds, it is attempting to create a bounding box of positions around the initial position that is given.
Therefore the coordinates of the cellbounds should be around the position when initialised.
The value is cast by the ceiling of the float so it goes to the next value up instead of rounding down. this way the value will be on the correct side of the initial positon to create the box.
- …

[GEN][ZH] Fix uninitialized variables in AiPathFind::findGroundPath, AiPathFind::classifyFence

---

Generals/Code/Libraries/Source/WWVegas/WWMath/cardinalspline.cpp
Generals/Code/Libraries/Source/WWVegas/WWMath/colmathaabox.cpp
Generals/Code/Libraries/Source/WWVegas/WWMath/colmathaabtri.cpp
Generals/Code/Libraries/Source/WWVegas/WWMath/colmathobbobb.cpp
Generals/Code/Libraries/Source/WWVegas/WWMath/colmathobbtri.cpp

* Follow up for #694
This change unifies the remaining code of WWMath.
Generals inherits the following changes:
* cardinalspline : Optimizes code in CardinalSpline3DClass::Update_Tangents
* colmathaabox : Fixes normal direction in CollisionMath::Collide for AABox-AABox collision
* colmathaabtri : Refactors the origin of the CollisionContext normal in aabtri_compute_contact_normal function
* colmathobbobb : Fixes float division by zero in obb_separation_test function
* colmathobbtri : Refactors storage type in obbtri_compute_contact_normal function
* colmathobbtri : Changes normal value calculation in CollisionMath::Collide for OBBox-Tri collision
As far as I could tell, the collision math changes in colmathaabox, colmathaabtri, colmathobbtri are never called in Zero …

[GEN] Backport collision test related changes and fixes in WWMath from Zero Hour

---

cmake/config-debug.cmake

This change fixes incorrect feature info setup for debug options in cmake.
Affects
* DebugLogging
* DebugCrashing
* DebugStacktrace
* DebugProfile
Previously it would claim that the debug options were always turned on.

[CMAKE] Fix feature infos of debug options

---

Generals/Code/GameEngine/Include/Common/CommandLine.h
Generals/Code/GameEngine/Include/Common/GlobalData.h
Generals/Code/GameEngine/Source/Common/CommandLine.cpp
Generals/Code/GameEngine/Source/Common/GlobalData.cpp
Generals/Code/GameEngine/Source/GameClient/GameClient.cpp
Generals/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp

This change unifies the code in CommandLine from Zero Hour to Generals.
ZH uses slightly different command line parameters.
This PR makes GEN uses the ZH version.
This also fixes an issue where -quickstart command was encapsulated in `Debug` and `Internal` flags since removal of `Playtest` flag, and thus didn't work in release versions.
Generals gets the followin new command line arguments:
* -extraLogging
* -stats
* -noshaders

[GEN] Backport command line arguments from Zero Hour

---

Generals/Code/GameEngine/Include/GameClient/Water.h
Generals/Code/GameEngine/Source/GameClient/Water.cpp
Generals/Code/GameEngineDevice/Include/W3DDevice/Common/W3DRadar.h
Generals/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DWater.h
Generals/Code/GameEngineDevice/Source/W3DDevice/Common/System/W3DRadar.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp

This change backports the code for the following WaterTransparency ini settings from Zero Hour to Generals:
```
StandingWaterColor = R:255 G:255 B:255
StandingWaterTexture = Texture.tga
AdditiveBlending = yes/no
RadarWaterColor = R:140 G:140 B:255
```
The behaviour of Generals is unchanged.
Additionally it fixes a memory leak in the destructor of WaterRenderObjClass. That is only called on shutdown and therefore inconsequential.

[GEN] Backport WaterTransparencySetting additions from Zero Hour

---

Generals/Code/GameEngine/Source/Common/Recorder.cpp
GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp

Another day goes by, and another bug is discovered. But this time, it's not a bug in the retail version, but in our build with VS22.
The replay header contains (among other) these elements:
- starttime
- endtime
- number of frames
- mismatch flag
- quitEarly flag
- disconnect flag (for each player)
- replayName (string)
start and endtime are of type time_t. On VC6 this was 32-bit, but on newer compilers it's 64-bit. In order to remain compatible, we need to load and save them as 32-bit. This PR fixes that.
Now you may ask: Wait, why did we not notice until now? Why are replays working?
Well, the replayName syncs everything up. It's serialized with a special character to indicate its end, and since all other header elements very likely don't contain that character, the serialization is …

[ZH] Fix replay header mismatch between builds using 32 bit or 64 bit wide time_t

---

Generals/Code/GameEngine/Include/GameLogic/Object.h
Generals/Code/GameEngine/Source/GameLogic/AI/AIPathfind.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Object.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate.cpp
GeneralsMD/Code/GameEngine/Include/GameLogic/Object.h
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIPathfind.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Object.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate.cpp

* Split off of #771
This change fixes compile errors from enabling DEBUG_CRC without DEBUG_LOGGING.

[GEN][ZH] Fix DEBUG_CRC compile errors

---

Generals/Code/Libraries/Source/WWVegas/WW3D2/shader.cpp

No actual functionality changes but makes diffing to ZH's simpler

[GEN] Bring ShaderClass::Apply more in line with Zero Hour

---

Generals/Code/GameEngine/Source/GameNetwork/LANAPIhandlers.cpp
GeneralsMD/Code/GameEngine/Source/GameNetwork/LANAPIhandlers.cpp

* Split off of #408
This change compiles out the duplicate serial check in LAN lobby. This is a requirement for running multiple clients locally.

[GEN][ZH] Compile out duplicate serial check in LAN lobby

---

Generals/Code/GameEngine/Include/Common/GameAudio.h
Generals/Code/GameEngine/Source/GameLogic/Object/Die/FXListDie.cpp
Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp
Generals/Code/GameEngineDevice/Include/MilesAudioDevice/MilesAudioManager.h
Generals/Code/GameEngineDevice/Source/MilesAudioDevice/MilesAudioManager.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp

**Merge by rebase**
This PR removes all instances of the empty ```stopAllAmbientsBy()``` functions and the functions definitions.
- Required For: #782

[GEN][ZH] Remove all instances of stopAllAmbientsBy()

---

Generals/Code/GameEngine/Include/Common/AudioEventInfo.h
Generals/Code/GameEngine/Include/Common/GameAudio.h
Generals/Code/GameEngine/Source/Common/Audio/GameAudio.cpp
Generals/Code/GameEngineDevice/Include/MilesAudioDevice/MilesAudioManager.h
Generals/Code/GameEngineDevice/Source/MilesAudioDevice/MilesAudioManager.cpp
GeneralsMD/Code/GameEngineDevice/Include/MilesAudioDevice/MilesAudioManager.h

**Squash and merge**
This PR makes the changes required to synchronize the audio implementations between Generals and Zero hour.
Most changes are backports to Generals, while some small tweaks are made to zero hour to match generals.
- Merge After: #793

[GEN][ZH] Unify code of GameAudio and MilesAudioManager

---

Generals/Code/GameEngine/Source/Common/GameEngine.cpp
GeneralsMD/Code/GameEngine/Source/Common/GameEngine.cpp

The game previously exited if `generalsa.sec` and `generalsb.sec` were not found in `Music.big` and `gensec.big` respectively.
Since copyright protection has already been disabled in the codebase, these fingerprinting files are no longer validated or used beyond their presence check.
This change prevents unnecessary termination in such cases. It may be ideal to remove the entire presence check and related logic altogether in a future cleanup.

[GEN][ZH] Remove obsolete sec file presence checks

---

Generals/Code/GameEngine/Include/Common/Debug.h
Generals/Code/GameEngine/Source/Common/Recorder.cpp
Generals/Code/GameEngine/Source/Common/System/Debug.cpp
GeneralsMD/Code/GameEngine/Include/Common/Debug.h
GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/Debug.cpp

This change couples the use of the debug log file in the Recorder class with the actual debug log file. This removes code duplication but also fixes minor discrepancies with how the log file is used in RecorderClass.
1. RecorderClass originally relied on the log file being located in the work directory
2. RecorderClass originally did not consider the app prefix for the log file name
Both of these were no practical issues, but are not clean either. With this change, both these things are no longer a concern.
Replicated without conflicts with
```
git diff d2e5d6007e0baa92d3d79ea2cf40200bdf581a0f..c27da312a54c3b479d527dee298e5400ae41384d > changes.patch
git apply -p2 --directory=Generals --reject --whitespace=fix changes.patch

[GEN][ZH] Fix and simplify the use of the log file in RecorderClass

---

Generals/Code/GameEngine/CMakeLists.txt
Generals/Code/GameEngine/Include/GameClient/ClientInstance.h
Generals/Code/GameEngine/Source/Common/Recorder.cpp
Generals/Code/GameEngine/Source/Common/System/Debug.cpp
Generals/Code/GameEngine/Source/GameClient/ClientInstance.cpp
Generals/Code/GameEngine/Source/GameClient/GameText.cpp
Generals/Code/Main/WinMain.cpp
GeneralsMD/Code/GameEngine/CMakeLists.txt
GeneralsMD/Code/GameEngine/Include/GameClient/ClientInstance.h
GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/Debug.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/ClientInstance.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GameText.cpp
GeneralsMD/Code/Main/WinMain.cpp
cmake/config-debug.cmake

* Relates to #407
This change adds multi instance support for debugging and testing. Accessible in cmake with the RTS_DEBUG_MULTI_INSTANCE option. It is turned off by default. When turned off, the game behaves as usual. When turned on, the game clients can do the following:
1. More than one game client can be launched
2. The instance id will be appended to the game window title for clients 2..N
3. The instance id will be appended to the log file names for clients 2..N
4. The instance id will be appended to the replay file names for clients 2..N
Replicated with
```
git diff ce5d683582389c63d05fd370390059a301672d2e..06e5179db50763d8a2466c2f16dcc746024bf29e > changes.patch
git apply -p2 --directory=Generals --reject --whitespace=fix changes.patch
```

[GEN][ZH] Implement multi instance support for the game client

---

Dependencies/Utility/Utility/CppMacros.h
Generals/Code/Libraries/Source/WWVegas/WW3D2/intersec.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIPathfind.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/intersec.cpp

Fixes warnings of `register` keyword being deprecated, by introducing a macro for the register keyword.

[GEN][ZH] Fix compile warnings from the use of deprecated register keywords

---

Core/Libraries/Source/WWVegas/WWLib/Except.cpp
Core/Libraries/Source/WWVegas/WWLib/ini.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/dazzle.cpp
Generals/Code/Tools/GUIEdit/Source/Dialog Procedures/ListboxProperties.cpp
Generals/Code/Tools/GUIEdit/Source/LayoutScheme.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dazzle.cpp
GeneralsMD/Code/Tools/GUIEdit/Source/Dialog Procedures/ListboxProperties.cpp
GeneralsMD/Code/Tools/GUIEdit/Source/LayoutScheme.cpp
GeneralsMD/Code/Tools/wdump/chunk_d.cpp

Fixes the following warnings:
- Incorrect string format specifier used
- Number of parameters not matching number of format specifiers
- Not using the return result of fscanf (separate commit)

[GEN][ZH] Fix compile warnings related to the use of printf and scanf

---

Generals/Code/GameEngine/Source/Common/RTS/Player.cpp
GeneralsMD/Code/GameEngine/Source/Common/RTS/Player.cpp

This PR performs some extra sanitation on the player during reset to prevent invalid codepaths being entered when the teamlist is cleared and teams are destroyed.
The way to trigger the issue that this fixes is to play as the USA, build a strategy center and enable the "search and destroy" battleplan. Make sure you have a few units then exit the game.
The full explanation for what is occuring can be found in the attached issue.
This issues does not cause crashing in the retail executable.
- Closes: #773

[GEN][ZH] Fix dangling pointer at Player::m_defaultTeam when Team is destroyed

---

Core/Libraries/Source/WWVegas/CMakeLists.txt
Core/Libraries/Source/WWVegas/WWDebug/CMakeLists.txt
Core/Libraries/Source/WWVegas/WWLib/CMakeLists.txt
Core/Libraries/Source/WWVegas/WWMath/CMakeLists.txt
Core/Libraries/Source/WWVegas/WWSaveLoad/CMakeLists.txt
Core/Libraries/Source/WWVegas/WWStub/CMakeLists.txt
Generals/Code/Libraries/Source/WWVegas/WW3D2/CMakeLists.txt
Generals/Code/Tools/ParticleEditor/CMakeLists.txt
Generals/Code/Tools/WorldBuilder/CMakeLists.txt
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/CMakeLists.txt

This change just cleans up some comments in CMake scripts.

[CMAKE] Clean up some comments in CMake scripts

---

Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/GUICallbacks/W3DControlBar.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/GUICallbacks/W3DControlBar.cpp

* Fixes #797
This PR prevents a possible division by zero from occuring when player progress is calculated.

[GEN][ZH] Fix possible division by zero in W3DCommandBarGenExpDraw()

---

Generals/Code/GameEngine/Include/GameClient/Water.h
GeneralsMD/Code/GameEngine/Include/GameClient/Water.h

* Follow up for #777
* Fixes #822

[GEN] Fix wrong water color on radar

---

Dependencies/Utility/Utility/CppMacros.h
Dependencies/Utility/Utility/endian_compat.h
Generals/Code/GameEngineDevice/Source/Win32Device/Common/Win32BIGFileSystem.cpp
GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdBIGFileSystem.cpp
GeneralsMD/Code/GameEngineDevice/Source/Win32Device/Common/Win32BIGFileSystem.cpp

This PR is a prerequisit to a PR to unify AsciiString, it adds endian compatibility functions within an endian_compat header.
These are then used in the BIGFileSystems as they previously reloed on the networking ntohl function.
For StdBIGFileSystem this was being indirectly provided through the windows header in AsciiString. And directly included in win32BigFileSystem through winsock2.
This change is necessary to provide cross compat byte swapping functionality.

[GEN][ZH] Add endian compat for BIGFileSystems

---

Generals/Code/GameEngine/Source/GameLogic/Object/Update/ProductionUpdate.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DLaserDraw.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
Generals/Code/GameEngineDevice/Source/Win32Device/Common/Win32BIGFileSystem.cpp
Generals/Code/GameEngineDevice/Source/Win32Device/Common/Win32LocalFileSystem.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/meshmdl.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/Snow.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/ProductionUpdate.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DLaserDraw.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
GeneralsMD/Code/GameEngineDevice/Source/Win32Device/Common/Win32BIGFileSystem.cpp
GeneralsMD/Code/GameEngineDevice/Source/Win32Device/Common/Win32LocalFileSystem.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/meshmdl.cpp

Fix freeing some reference counted pointers so that underlying memory is properly freed.
Also fix the cleanup in some classes that were not clearing dependent objects.
~~Will be checking for more so left this as draft for the moment.~~
EDIT: This should be good to merge now, the memory leaks it fixes are some of the most prominent that i came across.
Fixes:
- Gen + ZH - ~W3DLaserDraw() was leaking materials.
- Gen + ZH - ~ProductionUpdate() was leaking production queue items if game exited before buildings sold or destroyed.
- ZH - Snow system was leaking on shutdown, wouldn't affect runtime but means a clean shutdown.
- Gen + ZH - ~W3DTankDraw() was leaking particle systems, therefore leaking particles as well.
- Gen + ZH - ~MeshModelClass() had an extra call to …

[GEN][ZH] Fix various memory leaks

---

Generals/Code/GameEngine/Source/Common/Recorder.cpp
GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp

When AsciiString::format is called with format %ls it is supposed to convert Unicode to Ascii. When that conversion fails AsciiString::format throws an exception which results in a serious error.
Long term we should fix this by using UTF-8 everywhere, but for now using AsciiString::translate fixes the problem.
Note that this crash only occurs in debug build and is therefore no problem for retail version. Also the display of the version in the replay menu works fine, just this debug code for an assertion is crashing.
Here is a replay to test: 
[00-00-01_3v3_DESKTOPT_DESKTOPS_DESKTOPG_MediAI_MediAI_MediAI.zip](https://github.com/user-attachments/files/20078145/00-00-01_3v3_DESKTOPT_DESKTOPS_DESKTOPG_MediAI_MediAI_MediAI.zip)
```
KernelBase.dll!75bcb5e2()	Unknown
[Frames below may be …
```

[GEN][ZH] Fix crash when DEBUG_CRASHING is enabled and loading a replay with unicode characters

---

Generals/Code/GameEngine/Source/Common/Recorder.cpp
GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp

* Follow up for #795
This change fixes a compile error in RecorderClass::cleanUpReplayFile when building RTS_DEBUG without DEBUG_LOGGING. Introduced by #795.

[GEN][ZH] Fix compile error in RecorderClass::cleanUpReplayFile when building RTS_DEBUG without DEBUG_LOGGING

---

Generals/Code/GameEngine/Source/Common/System/AsciiString.cpp
Generals/Code/GameEngine/Source/Common/System/UnicodeString.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/AsciiString.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/UnicodeString.cpp

* Relates to #824
This change demotes the unnecessary throw to debug assert in AsciiString::format_va and UnicodeString::format_va. Unnecessary throw because this format error is not necessarily a fatal error that needs to terminate the process. The program may just run fine with this error. The debug assert is enough to see the error.

[GEN][ZH] Demote throw to assert in AsciiString::format_va, UnicodeString::format_va

---

cmake/config-memory.cmake

This PR adds a check that overrides the currently selected option for Game Memory if ASAN is detected as being enabled.

[CMAKE] Disable game memory manager if ASAN is enabled

---

Generals/Code/GameEngine/Source/GameLogic/AI/AIPlayer.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIPlayer.cpp

* Follow up for #653
So I did a bunch of automated testing with about 1400 replays (that's about 20 days of combined gametime). All these replays 
- did not mismatch when they were originally played (that is stored in the replay)
- have at least 2 human players
- have at least one AI player
- were played on a compatible 1.04 or 1.05 retail version
I checked to leave the supplyTruck variable uninitialized and initialized to true. The end result was that not a single replay mismatched with it initialized to true. (I already confirmed that initializing to false causes mismatches, so I didn't check that again)
So I suggest to initialize it. Why?
- I already confirmed that enabling some logging in StateMachine::internalGetState will cause mismatches when the variable is left uninitialized. …

[GEN][ZH] Initialize supplyTruck variable

---

Generals/Code/Libraries/Source/WWVegas/WW3D2/sortingrenderer.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/sortingrenderer.cpp

* Fixes #181
This change fixes a major memory leak in SortingRendererClass::Insert_To_Sorting_Pool(). It can be triggered by spawning the binary shower particle effects with the Hacker.
```
>	generalszh.exe!SortingRendererClass::Flush() Line 617	C++
generalszh.exe!RTS3DScene::Flush(RenderInfoClass & rinfo) Line 872	C++
generalszh.exe!RTS3DScene::Render(RenderInfoClass & rinfo) Line 1074	C++
generalszh.exe!WW3D::Render(SceneClass * scene, CameraClass * cam, bool clear, bool clearz, const Vector3 & color) Line 979	C++
generalszh.exe!RTS3DScene::draw() Line 1724	C++
generalszh.exe!SubsystemInterface::DRAW() Line 105	C++
generalszh.exe!RTS3DScene::doRender(CameraClass * cam) Line 1708	C++
generalszh.exe!W3DView::draw() Line 1565	C++
generalszh.exe!SubsystemInterface::DRAW() Line 105	C++ …
```

[GEN][ZH] Fix memory leak in SortingRendererClass::Insert_To_Sorting_Pool()

---

Generals/Code/GameEngine/Source/GameLogic/Object/Update/SpecialAbilityUpdate.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/SpecialAbilityUpdate.cpp

* Relates to #181
This change fixes a minor memory leak in SpecialAbilityUpdate::isWithinStartAbilityRange(). It is reproducible when using the China Hacker to disable buildings.
```
Leaked a block of size 16, tagstring D:\Projects\TheSuperHackers\GeneralsGameCode\GeneralsMD\Code\GameEngine\Source\GameLogic\Object\SimpleObjectIterator.cpp, from pool/dma SimpleObjectIteratorClumpPool
Leaked a block of size 16, tagstring D:\Projects\TheSuperHackers\GeneralsGameCode\GeneralsMD\Code\GameEngine\Source\GameLogic\Object\SimpleObjectIterator.cpp, from pool/dma SimpleObjectIteratorClumpPool
Leaked a block of size 16, tagstring D:\Projects\TheSuperHackers\GeneralsGameCode\GeneralsMD\Code\GameEngine\Source\GameLogic\Object\SimpleObjectIterator.cpp, from pool/dma SimpleObjectIteratorClumpPool
... …
```

[GEN][ZH] Fix memory leak in SpecialAbilityUpdate::isWithinStartAbilityRange()

---

Generals/Code/Main/WinMain.cpp
GeneralsMD/Code/Main/WinMain.cpp

This PR prevents the game from freezing when the left ALT key is pressed.
The underlying issue is due to the games window process not acknowledging the ```WM_SYSCOMMAND SC_KEYMENU``` message.
Due to this, the message is then processed by the default window process which then will try to open the windows context menu which does not exist in this instance but causes the message loop to freeze.
- Resolves: #105
This may also help prevent some mismatches that could be caused by a game freezing for too long when someone is playing in window mode.

[GEN][ZH] Fix game halting when left Alt key is pressed

---

Generals/Code/GameEngine/Source/Common/CommandLine.cpp
GeneralsMD/Code/GameEngine/Source/Common/CommandLine.cpp

"-useWaveEditor" command line is gated behind DEBUG/INTERNAL builds, but the code supporting it is built for release as well.

[GEN][ZH] Enable use of Wave Editor in release build

---

Generals/Code/GameEngine/Include/GameClient/InGameUI.h
Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp
Generals/Code/GameEngine/Source/GameClient/MessageStream/GUICommandTranslator.cpp
Generals/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp

- Resolves #305
- Relates to #555 
- Requires issue #525 to be resolved first
This change backports the left mouse click deselect functionality with the Alternate Mouse Setup from Zero Hour to Generals. Previously in Generals it was not possible to deselect units or buildings with a mouse click when the Alternate Mouse Setup was enabled.

[GEN] Backport left click deselect functionality with Alternate Mouse Setup from Zero Hour

---

Core/Tools/WW3D/pluglib/CMakeLists.txt
Core/Tools/WW3D/pluglib/Vector.H

* Follow up for #712
This change fixes a VC6 compile error in max2w3d pluglib that was introduced by #712.

[CORE] Fix VC6 compile error in max2w3d pluglib

---

Generals/Code/GameEngine/Source/Common/System/AsciiString.cpp
Generals/Code/GameEngine/Source/Common/System/UnicodeString.cpp
Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/AsciiString.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/UnicodeString.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/InGameUI.cpp

* Follow up for #835
* Relates to #857
This change demotes unnecessary throw to debug assert in functions InGameUI::message and InGameUI::messageColor. Unnecessary throw because this format error is not necessarily a fatal error that needs to terminate the process. The program may just run fine with this error. The debug assert is enough to see the error.

[GEN][ZH] Demote throw to assert in InGameUI::message, InGameUI::messageColor

---

Generals/Code/GameEngine/Source/Common/Dict.cpp
Generals/Code/GameEngine/Source/Common/System/AsciiString.cpp
Generals/Code/GameEngine/Source/Common/System/UnicodeString.cpp
GeneralsMD/Code/GameEngine/Source/Common/Dict.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/AsciiString.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/UnicodeString.cpp

* Relates to #857
This change demotes unnecessary throw to debug assert in functions
* AsciiString::ensureUniqueBufferOfSize
* UnicodeString::ensureUniqueBufferOfSize
* Dict::ensureUnique
Unnecessary throw because it is not necessary to terminate the process if the string is a bit longer than an arbitrary limit. The program may just run fine when the limit is exceeed. The debug assert is enough to see the error.
This change also fixes a logical issue in ensureUniqueBufferOfSize, most notably for UnicodeString, where MAX_LEN was effectively halved.

[GEN][ZH] Demote throw to assert in AsciiString::ensureUniqueBufferOfSize, UnicodeString::ensureUniqueBufferOfSize, Dict::ensureUnique

---

Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/InGameUI.cpp

* Follow up for #860
This change readds a call to `va_end` that was mistakenly removed in a previous change #860.

[GEN][ZH] Fix missing call to va_end in InGameUI::messageColor()

---

Generals/Code/GameEngine/Source/Common/Recorder.cpp
GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp

This change pauses replay playback on CRC mismatch. The mismatch text message is visible when the game is paused. The replay can be unpaused by pressing ESC twice to open and close the exit menu.

[GEN][ZH] Pause replay on CRC mismatch

---

Generals/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp

* Fixes #841
The following loop contains undefined behavior:
https://github.com/TheSuperHackers/GeneralsGameCode/blob/696cb63bd92b58962bc6618a39771ee36f069ace/Generals/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp#L3039-L3055
The compiler can see that the forward progress guarantee is violated if the iterator (`*it`) points to a `nullptr`. In other words, this could become an infinite loop, which is undefined behavior in C++20 and the compiler is likely to get rid of the entire `!= nullptr` check:
https://github.com/TheSuperHackers/GeneralsGameCode/blob/696cb63bd92b58962bc6618a39771ee36f069ace/Generals/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp#L3043-L3046

[GEN][ZH] Fix infinite loop in ParticleSystemManager::update

---

Generals/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBar.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Diplomacy.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/DifficultySelect.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/DownloadMenu.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanMapSelectMenu.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupCommunicator.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/QuitMenu.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ScoreScreen.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/SkirmishMapSelectMenu.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLMapSelectMenu.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/Shell/Shell.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/WindowLayout.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBar.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Diplomacy.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/DifficultySelect.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/DownloadMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanMapSelectMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupCommunicator.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/QuitMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ScoreScreen.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/SkirmishMapSelectMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLMapSelectMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Shell/Shell.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/WindowLayout.cpp

Same issue as: https://github.com/TheSuperHackers/GeneralsGameCode/pull/870
https://github.com/TheSuperHackers/GeneralsGameCode/blob/e61cef2ce5b1a04e288bfb0c3220e94c2e4c99ae/Generals/Code/GameEngine/Source/GameClient/GUI/WindowLayout.cpp#L174-L179
This pr removes the explicit `if (this == NULL)` check in `WindowLayout::destroyWindows`, and added `nullptr` checks at the call sites where needed.

[GEN][ZH] Fix undefined behavior in WindowLayout::destroyWindows

---

Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DBufferManager.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DVolumetricShadow.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DBufferManager.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DVolumetricShadow.cpp

* Fixes #22
* Relates to #TheAssemblyArmada/Thyme#1101
This change fixes game crashes from exceeding the limits of `MAX_VB_SIZES`, `MAX_IB_SIZES` and `MAX_NUMBER_SLOTS`.
`MAX_NUMBER_SLOTS` is exceeded in the original game when more than 512 Scorpion tanks are rendered in the scene. This is just a sample test case.
This change also fixes errors in nearby strings and source code comments.
```cpp
> 	generalszh.exe!W3DVolumetricShadow::RenderMeshVolume(int meshIndex, int lightIndex, const Matrix3D * meshXform) Line 1392	C++
generalszh.exe!W3DVolumetricShadow::RenderVolume(int meshIndex, int lightIndex) Line 1337	C++
generalszh.exe!W3DVolumetricShadowManager::renderShadows(bool forceStencilFill) Line 3563	C++
generalszh.exe!DoShadows(RenderInfoClass & rinfo, bool stencilPass) Line 91	C++ …
```

[GEN][ZH] Fix crash in W3DBufferManager when a shadow buffer limit is exceeded

---

GeneralsMD/Code/GameEngine/Include/Common/AsciiString.h
GeneralsMD/Code/GameEngine/Include/Common/CriticalSection.h
GeneralsMD/Code/GameEngine/Source/Common/System/AsciiString.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/CriticalSection.cpp

- Merge after: #798 
This PR unifies the implementation of AsciiString between Generals and Zero Hour by using the Generals version of AsciiString in Zero Hour.
Zero Hour had to use a different scoped mutex implementation as they inlined a few of the string access functions. They likely thought this would help performance but it lead to a messier implementation.
The Generals version of AsciiString is also more cross compatible than the Zero Hour version as it is not dependend on windows functions. And the scoped section can have its implementation altered independent of code that makes use of it.

[ZH] Unify code of AsciiString

---

Generals/Code/GameEngine/Include/Common/GameMemory.h
Generals/Code/GameEngine/Include/Common/GameMemoryNull.h
GeneralsMD/Code/GameEngine/Include/Common/GameMemory.h
GeneralsMD/Code/GameEngine/Include/Common/GameMemoryNull.h

* Follow up for #870
This change renames `MemoryPoolObject::deleteInstance` to `MemoryPoolObject::deleteInstanceInternal`.
Reason being, when overloading the global `deleteInstance`, then a call to `deleteInstance` within a member function of a parent class of `MemoryPoolObject` will call `MemoryPoolObject::deleteInstance` instead of `::deleteInstance`, which is confusing and error prone.

[GEN][ZH] Rename MemoryPoolObject::deleteInstance to MemoryPoolObject::deleteInstanceInternal

---

Generals/Code/GameEngine/Source/GameLogic/AI/AIPathfind.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIPathfind.cpp

* Follow up for #632
This PR adds conditional initialisation to the ```costSoFar``` variable in ```Pathfinder::findGroundPath``` within AiPathfind.cpp.
It came to light recently that the Golden Replays did not catch this issue, but some other replays could mismatch compared to retail due to the initialisation of this varaible.
For builds other than the VC6 build, the variable will be initialised to prevent throwing an uninitialised variable exception during debug.

[GEN][ZH] Revert to uninitialized variable in AiPathFind::findGroundPath for VC6 builds to avoid mismatch with retail builds

---

GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DSmudge.cpp

This change fixes a missing call to IDirect3DSurface8::UnlockRect in W3DSmudge's copyRect. There was no observed issue.
Yes, in **DirectX 8**, if you successfully call `IDirect3DSurface8::LockRect`, **you must call `UnlockRect` before releasing the surface**, even if you're about to call `Release()`.
---
* Locking a surface gives you **direct access to memory** (CPU-side), and **locks GPU access** to the surface.
* **`UnlockRect()` is required to release that lock** and signal that you're done with the CPU-side access.
* If you skip `UnlockRect` and call `Release()` directly, you're violating the interface contract. The behavior is **undefined**:
* Some drivers may crash.
* Others may leak memory or hang the GPU.
* It may work in debug builds but crash in release (or vice versa).
--- …

[ZH] Add missing call to IDirect3DSurface8::UnlockRect in W3DSmudge's copyRect

---

Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp

* Fixes #896
* Closes #881
* Follow up for #809
This change fixes asserts and crashes from unloading maps and destroying all objects.
It does so by setting all objects effectively dead before deleting them. This way they do not apply terminal damage to other objects and no longer trigger death modules, that would eventually attempt to spawn new objects.
```
...
generalszh.exe!WeaponStore::createAndFireTempWeapon(const WeaponTemplate * wt, const Object * source, const Coord3D * pos) Line 1544	C++
generalszh.exe!FireWeaponWhenDeadBehavior::onDie(const DamageInfo * damageInfo) Line 119	C++
generalszh.exe!Object::onDie(DamageInfo * damageInfo) Line 4563	C++
generalszh.exe!ActiveBody::attemptDamage(DamageInfo * damageInfo) Line 677	C++
generalszh.exe!Object::attemptDamage(DamageInfo * …
```

[GEN][ZH] Prevent executing death modules and spawning new objects to avoid asserts and crashes when unloading a map and destroying all objects

---

Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/ww3d.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/ww3d.cpp

This change fixes the crash when taking a screenshot with F12 while the Game Window clips over the outer boundaries of the screen.
```
>	generalszh.exe!W3DDisplay::takeScreenShot() Line 3061	C++
generalszh.exe!CommandTranslator::translateGameMessage(const GameMessage * msg) Line 5163	C++
generalszh.exe!MessageStream::propagateMessages() Line 1096	C++
generalszh.exe!GameEngine::update() Line 743	C++
generalszh.exe!Win32GameEngine::update() Line 93	C++
generalszh.exe!GameEngine::execute() Line 816	C++
generalszh.exe!GameMain(int argc, char * * argv) Line 47	C++
generalszh.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 1038	C++
[Inline Frame] generalszh.exe!invoke_main() Line 102	C++
generalszh.exe!__scrt_common_main_seh() Line 288	C++ …
```

[GEN][ZH] Fix crash when taking a screenshot while the Game Window clips over the screen edge

---

Generals/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarCommandProcessing.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarCommandProcessing.cpp

- Closes: #914
This PR corrects an uninitialised variable access that can occur when selecting an empty button on a building or vehicle that has a contain element.
If no match is made for the selected button against elements in the contain list, the object ID variable used to lookup the required object will be uninitialised which could cause unexpected behaviour if the value were to match a valid object.
Setting the object variable prevents this behaviour as we can return early if the ```objID``` variable is still the ```INVALID_ID```.

[GEN][ZH] Fix global-buffer-overflow at GUI_COMMAND_EXIT_CONTAINER in ControlBar::processCommandUI()

---

Generals/Code/GameEngine/Include/GameNetwork/WOLBrowser/FEBDispatch.h
Generals/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetTabControl.cpp
Generals/Code/GameEngine/Source/GameClient/GameText.cpp
Generals/Code/GameEngine/Source/GameLogic/AI/AIPathfind.cpp
Generals/Code/GameEngine/Source/GameNetwork/Network.cpp
GeneralsMD/Code/GameEngine/Include/GameNetwork/WOLBrowser/FEBDispatch.h
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetTabControl.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GameText.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIPathfind.cpp
GeneralsMD/Code/GameEngine/Source/GameNetwork/Network.cpp

If statements such as `if( (m_textCount == 0) )` generate a compiler warning for redundant parentheses.

[GEN][ZH] Fix compiler warnings for redundant parentheses in if statement

---

Generals/Code/GameEngine/Include/Common/BezierSegment.h
GeneralsMD/Code/GameEngine/Include/Common/BezierSegment.h

Function declaration and definition are inconsistent:
`BezierSegment(Real cp[16]);` and `BezierSegment(Real cp[12]);`
The function only uses 12, so that should be correct one of the two options:
https://github.com/TheSuperHackers/GeneralsGameCode/blob/9c20c27be58463a755b8c67a50f1fdf146a33b68/Generals/Code/GameEngine/Source/Common/Bezier/BezierSegment.cpp#L62-L79

[GEN][ZH] Set correct size for array parameter in BezierSegment function declaration

---

Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp

Fixes a typo where the same variable was used for a comparison:
`(m_gridCellsX != gridCellsX || m_gridCellsY != m_gridCellsY)` instead of the function parameter: `gridCellsY`.

[GEN][ZH] Fix incorrect grid resolution update condition in WaterRenderObjClass::setGridResolution()

---

Generals/Code/GameEngine/Source/GameNetwork/GameSpy/Thread/PeerThread.cpp
GeneralsMD/Code/GameEngine/Source/GameNetwork/GameSpy/Thread/PeerThread.cpp

EDIT: Calling `std::string::empty` and then discarding the result has to be a bug. Clearing a `std::string` is done using `clear` not `empty`.

[GEN][ZH] Remove obsolete and wrong code in listGroupRoomsCallback()

---

Core/Libraries/Source/WWVegas/WWLib/always.h
Core/Libraries/Source/WWVegas/WWMath/v3_rnd.h

The compiler generates two warnings for the following line as `that` is unused twice:
`Vector3SolidBoxRandomizer & operator = (const Vector3SolidBoxRandomizer &that) { that; return *this; }`
Because these are dummy operators (imitating `= delete`) they shouldn't need to copy anything.

[CORE] Remove unused variables in assignment operators of Vector3Randomizer classes

---

Core/Libraries/Source/WWVegas/WW3D2/rendobj.h
Generals/Code/GameEngine/Include/GameClient/Drawable.h
Generals/Code/GameEngine/Include/GameClient/InGameUI.h
Generals/Code/GameEngine/Include/GameLogic/Module/AIUpdate.h
Generals/Code/GameEngine/Include/GameLogic/Module/RailroadGuideAIUpdate.h
Generals/Code/GameEngine/Include/GameLogic/Object.h
Generals/Code/GameEngine/Source/GameClient/Drawable.cpp
Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/ww3d.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/ww3d.h
GeneralsMD/Code/GameEngine/Include/GameClient/ChallengeGenerals.h
GeneralsMD/Code/GameEngine/Include/GameClient/Drawable.h
GeneralsMD/Code/GameEngine/Include/GameClient/InGameUI.h
GeneralsMD/Code/GameEngine/Include/GameLogic/Module/AIUpdate.h
GeneralsMD/Code/GameEngine/Include/GameLogic/Module/RailroadGuideAIUpdate.h
GeneralsMD/Code/GameEngine/Include/GameLogic/Object.h
GeneralsMD/Code/GameEngine/Source/GameClient/Drawable.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/InGameUI.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/ww3d.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/ww3d.h

In cases such as `const bool foo() const;` the first `const` qualifier is meaningless and generates a compiler warning.

Fix compiler warnings for const qualifier on value return type

---

Core/Libraries/Source/WWVegas/WWAudio/WWAudio.h
Core/Libraries/Source/WWVegas/WWLib/always.h
Core/Libraries/Source/profile/internal.h
Generals/Code/Libraries/Source/WWVegas/WW3D2/meshmdl.h
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/meshmdl.h

A few functions or operators that are missing a valid return statement which generates compiler warnings. 
The operators seem to have been made private in an attempt to achieve the same as C++11 `= delete`, so they shouldn't need to actually copy anything.

[GEN][ZH] Fix compiler warnings about missing return values for non-void functions

---

Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLLoginMenu.cpp
Generals/Code/GameEngine/Source/GameNetwork/GameSpy/Thread/ThreadUtils.cpp
Generals/Code/GameEngine/Source/GameNetwork/NetPacket.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLLoginMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/Terrain/TerrainVisual.cpp
GeneralsMD/Code/GameEngine/Source/GameNetwork/GameSpy/Thread/ThreadUtils.cpp
GeneralsMD/Code/GameEngine/Source/GameNetwork/NetPacket.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DTerrainBackground.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DTerrainVisual.cpp

Fixes some mismatches where `delete[]` would need to be used instead of `delete`, and a single case where `new( ... )` was used instead of `new ...`.

[GEN][ZH] Fix array new / scalar delete mismatches in GameEngine, GameEngineDevice

---

Core/Libraries/Source/WWVegas/WWLib/ref_ptr.h
Generals/Code/GameEngine/Include/Common/StateMachine.h
Generals/Code/GameEngine/Source/Common/StateMachine.cpp
GeneralsMD/Code/GameEngine/Include/Common/StateMachine.h
GeneralsMD/Code/GameEngine/Source/Common/StateMachine.cpp

* Merge after #889 
* Fixes #212
This change fixes a crash in `StateMachine` that happens when a chained `StateMachine` update destroys the prior executor `StateMachine`. This issue happened with #212, where the Ranger's `StateMachine` in the Bus would kill the Power Plant, and then the Power Plant weapon would kill the Bus, which would then delete the `StateMachine` of the Ranger.

[GEN][ZH] Fix crash in StateMachine when a chained StateMachine update deletes the executor StateMachine

---

Generals/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate.cpp

- Resolves: #924 
The Issue contains a full list of my workings and findings on for this particular bug.
The problem stems from a race condition in which a pending AI command on an object can end up containing the ID of an object that has already been destroyed.
Many of the private action commands in ```aiupdate.cpp``` already have checks for null pointers in them. Or the object is passed internally into another function that checks for a null pointer.
But the ```privateMoveAwayFrom()``` function did not have a check, this was the cause of the crash in the attached replay in the issue. 
~~I also added a check in the ```privateguardObject()``` function as this also lacked any protection from a null pointer dereference on the passed object.~~
The AI commands are generic and not all fields …

[GEN][ZH] Fix crash in AIUpdateInterface::privateMoveAwayFromUnit() when a delayed AICommandParms relates to a then deleted object

---

Generals/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate.cpp

- Merge After: #964
This PR is a followup Pr from the Hackers delayed ai command crash PR. It adds null pointer checks to two other functions that were observed as missing them. These functions did not cause any known crashes in the game, but it is safer to add the checks.

[GEN][ZH] Add null pointer tests in AIUpdateInterface::privateCommandButtonObject(), privateGuardObject()

---

Generals/Code/GameEngine/Include/GameNetwork/IPEnumeration.h
Generals/Code/GameEngine/Include/GameNetwork/networkutil.h
Generals/Code/GameEngine/Source/GameClient/ClientInstance.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanLobbyMenu.cpp
Generals/Code/GameEngine/Source/GameNetwork/IPEnumeration.cpp
GeneralsMD/Code/GameEngine/Include/GameNetwork/IPEnumeration.h
GeneralsMD/Code/GameEngine/Include/GameNetwork/networkutil.h
GeneralsMD/Code/GameEngine/Source/GameClient/ClientInstance.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanLobbyMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameNetwork/IPEnumeration.cpp

* Merge after #905
* Closes #407
This change enables multi instance clients to connect in Network matches and is an alternative implementation to #407. It does not change the Network protocol and therefore is using the Network as if these were normal clients. To achieve that, it adds one unique local host IP address to each client that the Network can use to connect multiple local clients with each other.
Credits to @jaapdeheer for this idea.
This change also implements a new default Network user name for the multi instance clients.
Credits to @helmutbuhler for the first implementation.

[GEN][ZH] Implement Network Lobby support for multi instance clients

---

Generals/Code/GameEngine/Include/Common/crc.h
Generals/Code/GameEngine/Source/Common/GlobalData.cpp
Generals/Code/Main/CMakeLists.txt
GeneralsMD/Code/GameEngine/Include/Common/crc.h
GeneralsMD/Code/GameEngine/Source/Common/GlobalData.cpp

* Merge after #874
* Resolves #525
* Closes #852
* Relates to #981
This change implements fake exe CRC for Generals CD 1.08 and Zero Hour CD 1.04 and allows VC6 builds to matchmake with retail builds in the Network Lobby and Online Lobby. It also suppresses version mismatch warnings in the Replay Load menu when loading compatible replays.
| Game | Is CRC compatible to | Is CRC compatible with this project (VC6 build) |
|----------------------|------------|-----|
| Generals CD 1.08     | CD 1.08    | Yes |
| Generals TFD 1.08    | CD 1.08    | Yes |
| Generals Steam 1.08  | Steam 1.08 | No  |
| Generals EAApp 1.08  | EAApp 1.08 | No  |
| Zero Hour CD 1.04    | CD 1.04    | Yes |
| Zero Hour TFD 1.04   | CD 1.04    | Yes |
| Zero Hour Steam 1.04 | CD 1.04    | Yes |
| Zero Hour EAApp 1.04 | …

[GEN][ZH] Implement fake CRC for Generals CD 1.08, Zero Hour CD 1.04 executable compatibility

---

Generals/Code/GameEngine/Include/Common/crc.h
Generals/Code/GameEngine/Source/Common/GlobalData.cpp
GeneralsMD/Code/GameEngine/Include/Common/crc.h
GeneralsMD/Code/GameEngine/Source/Common/GlobalData.cpp

* Follow up for #965
I used RETAIL_COMPATIBLE_CRC macro slightly incorrectly. Flipping that macro to 0, would not compile out the code in VC6 builds.

Improve use of RETAIL_COMPATIBLE_CRC macro

---

Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp

* Split off of #398
This change fixes the missing OLDER REPLAY VERSION dialog when double clicking a replay to load.
Additionally, it moves the duplicate load replay code into a new function as a separate commit.

[GEN][ZH] Fix missing OLDER REPLAY VERSION dialog when double clicking a replay to load

---

Generals/Code/Main/CMakeLists.txt
Generals/Code/Main/RTS.RC
Generals/Code/Main/app.manifest
GeneralsMD/Code/Main/CMakeLists.txt
GeneralsMD/Code/Main/RTS.RC
GeneralsMD/Code/Main/app.manifest

Currently, Windows treats the Gen and ZH executables as [DPI unaware](https://learn.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows#dpi-awareness-mode) and forcefully scales the content of all application windows when the display scaling factor is set to something other than 100%. This means that when running the game in windowed mode with a resolution of 800x600, the real window size on screens with scaling set to 200% will be 1600x1200, and every pixel will simply be stretched to four pixels. To prevent this system scaling, the application should indicate to the system that it is DPI aware. The best way to achieve this is to add an application [manifest](https://learn.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for …

[GEN][ZH] Add Windows application manifest to executables

---

Generals/Code/GameEngine/Include/Common/Recorder.h
Generals/Code/GameEngine/Source/Common/Recorder.cpp
GeneralsMD/Code/GameEngine/Include/Common/Recorder.h
GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp

* Merge after #969
* Fixes #76
* Relates to #850
This change fixes a game crash when exiting Replay playback while a player places a beacon.
The null crash does occur in GameLogic::logicMessageDispatcher, but the root cause of the problem already starts earlier.
The `RecorderClass` can still push replay commands to the CommandList before the final `MSG_CLEAR_GAME_DATA` is processed in the same frame. `MSG_CLEAR_GAME_DATA` will destroy the match session.
```
generalszh.exe!GameLogic::reset() Line 453	C++
generalszh.exe!SubsystemInterfaceList::resetAll() Line 188	C++
[Inline Frame] generalszh.exe!GameLogic::isInMultiplayerGame() Line 418	C++
generalszh.exe!GameEngine::reset() Line 699	C++
generalszh.exe!GameLogic::clearGameData(bool showScoreScreen) Line 281	C++ …
```

[GEN][ZH] Fix crash when exiting Replay playback while a player places a beacon

---

Generals/Code/GameEngine/Include/Common/Recorder.h
Generals/Code/GameEngine/Source/Common/Recorder.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp
GeneralsMD/Code/GameEngine/Include/Common/Recorder.h
GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp

* Follow up for #984
This change fixes the `RecorderClass::testVersionPlayback` function.
The following problems were identified:
1. The return values do not match what the EA comments say about it (*1)
2. If a Replay header was not recognized, then the function would return success (*2)
(*1) The function now matches what the comment says and has been given a better name to tell what it does.
(*2) This is only a theoretical issue. The replay would not show up in the replay list anyway if its header was not read correctly.
Additionally the function was split in 2 so that it can also be called with a `ReplayHeader` (to be used in the next change after this). Reason being, `replayMatchesGameVersion(AsciiString filename)` is expensive, because it reads a physical Replay file on disk.

[GEN][ZH] Fix logical errors with RecorderClass::testVersionPlayback()

---

Core/Libraries/Source/WWVegas/WWMath/wwmath.h

Remove naked function declaration `__declspec(naked)` for `WWMath::Inv_Sqrt` because clang-cl doesn't support it for member functions. It's not consistent with the other functions in this class with inline assembly, either: 
https://github.com/TheSuperHackers/GeneralsGameCode/blob/ef17abf6928309698a7262c2b178f5a1a07bc880/Core/Libraries/Source/WWVegas/WWMath/wwmath.h#L557-L566

[CORE] Remove naked function declaration for WWMath::Inv_Sqrt

---

Generals/Code/GameEngine/Source/Common/GameEngine.cpp
GeneralsMD/Code/GameEngine/Source/Common/GameEngine.cpp

Fixes: #995
This fixes a crash when shutting down the GameEngine without calling `TheGameEngine->reset()` first. This happens during Replay Simulation (see #923).
During normal shutdown in the existing game this cannot happen because shutdown only occurs with the `GameMessage::MSG_CLEAR_GAME_DATA` message, which calls `GameLogic::clearGameData`, which in turn calls `TheGameEngine->reset()`
Why does it crash otherwise?
GameEngine has (among others) two subsystems: `TeamFactory` and `PlayerList`, which it initializes in that order. During shutdown (in opposite order) `~TeamFactory()` calls `~TeamPrototype()`, which calls `~Team()`, which calls `ThePlayerList->getPlayerCount()` (which then will crash because the PlayerList is already destructed).
Resetting first fixes this because it clears …

[GEN][ZH] Fix crash on GameEngine shutdown when GameLogic::clearGameData() was not called before

---

Generals/Code/GameEngine/Source/Common/RTS/PlayerList.cpp
GeneralsMD/Code/GameEngine/Source/Common/RTS/PlayerList.cpp

Remove silly catch block. Just to be sure, I tested this on all my replays, and they all work fine without this.

[GEN][ZH] Remove unnecessary try catch block in ~PlayerList()

---

Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp

* Relates to #126
* Relates to #992
This change fixes 2 null dereferences when attempting to load into a Replay whose map is missing. Loading in an empty map is not particularly useful, but it is better than crashing the game.
The first commit also fixes a warning from the MSVC static analyzer:
> GeneralsMD\Code\GameEngine\Source\GameLogic\System\GameLogic.cpp(832): warning C6011: Dereferencing NULL pointer 'md'.

[GEN][ZH] Prevent game crash when starting a new game without a map

---

Core/GameEngine/Include/Common/GameDefines.h
Generals/Code/GameEngine/Include/GameClient/GameText.h
Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp
Generals/Code/GameEngine/Source/GameClient/GameText.cpp
GeneralsMD/Code/GameEngine/Include/GameClient/GameText.h
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GameText.cpp

* Merge after #993
* Fixes #126
* Follow up for #984
* Split off of #398
This change implements a new MAP NOT FOUND dialog when the user attempts to load a Replay whose map is missing in the user data (or game install). Originally the game would crash when trying to start a new game with a missing map.
Additionally it implements a new REPLAY NOT FOUND dialog when the user attempts to load a Replay that was deleted after the Replay Menu was opened.
This change has 2 commits. The first commit is a refactor to help implement the fix efficiently. The second commit contains new code for GameText to allow looking up localization texts with substitute texts when those localizations are not found (which they currently are not because we do not touch game data). The …

[GEN][ZH] Implement REPLAY NOT FOUND and MAP NOT FOUND dialogs when attempting to load a Replay that was deleted or whose map is missing

---

Core/Libraries/Source/WWVegas/WWLib/ref_ptr.h
Core/Libraries/Source/WWVegas/WWLib/refcount.h
Generals/Code/GameEngine/Source/Common/StateMachine.cpp
GeneralsMD/Code/GameEngine/Source/Common/StateMachine.cpp

This change fixes up the RefCountClass and RefCountPtr<T> for upcoming use cases.
I was unable to figure out how to use the friend functions in `RefCountPtr`, so I replaced them with static functions. I renamed them to `Create_AddRef` and `Create_NoAddRef`, because that makes it much easier to understand.
The asserts are now also corrected for the reference counters.
And a Release function was added to replicate `unique_ptr::release`.

[CORE] Fix up RefCountClass, RefCountPtr<T>

---

Core/Libraries/Source/WWVegas/WWMath/wwmath.h

* Follow-up to https://github.com/TheSuperHackers/GeneralsGameCode/pull/1009
I noticed some inconsistencies in `wwmath.h`. This pr makes the following changes to fix that:
https://github.com/TheSuperHackers/GeneralsGameCode/blob/ef17abf6928309698a7262c2b178f5a1a07bc880/Core/Libraries/Source/WWVegas/WWMath/wwmath.h#L605-L610
The `fastcall` calling convention appears to be ignored here as `a`, the function parameter, is accessed on the stack (`[esp+4]`). Functions with `fastcall` calling convention use registers for their function parameters, per https://learn.microsoft.com/en-us/cpp/cpp/fastcall:
> The first two DWORD or smaller arguments that are found in the argument list from left to right are passed in ECX and EDX registers; all other arguments are passed on the stack from right to …

[CORE] Cleanup wwmath header for consistency

---

GeneralsMD/Code/GameEngine/Include/Common/TunnelTracker.h
GeneralsMD/Code/GameEngine/Source/Common/RTS/TunnelTracker.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp

* Relates to #921
This change fixes another crash when occupants kill their container and force the remaining occupants to evacuate. This time it concerns the TunnelContain module. This problem is Zero Hour specific. Generals does not have this code.
The technical mistake here is calling `TunnelTracker::onTunnelDestroyed` within the process of iterating `TunnelTracker::m_containList` in `TunnelContain::killAllContained`. It is catastophic to modify the list in recursive calls.
To fix this problem, the recursive modification is avoided. The `TunnelTracker::m_containList` will be long empty before the code ever reaches `TunnelTracker::onTunnelDestroyed`.
This change carries risk of mismatch with retail game, IF there is a code path that **reads** `TunnelTracker::m_containList` while …

[ZH] Fix crash in TunnelContain::killAllContained() when killed occupants kill the host container

---

Generals/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp

A break statement was in the wrong scope leading to hollow boxes behaving as though they were line systems.
MSVC says
```
GeneralsMD\Code\GameEngine\Source\GameClient\System\ParticleSys.cpp(1644): warning C26819: Unannotated fallthrough between switch labels (es.78).
```

[GEN][ZH] Fix hollow BOX particles treated as LINE particles in ParticleSystem::computeParticlePosition()

---

Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/TerrainTex.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DShaderManager.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/TerrainTex.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DShaderManager.cpp

`if (TheGlobalData && TheGlobalData->m_bilinearTerrainTex || TheGlobalData->m_trilinearTerrainTex)`
This is a bug because `TheGlobalData->m_trilinearTerrainTex` may be accessed without checking if `TheGlobalData != NULL`.

[GEN][ZH] Fix logical expressions for TheGlobalData in TerrainTex and W3DShaderManager

---

Generals/Code/GameEngine/Source/GameLogic/AI/AIPathfind.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIPathfind.cpp

Followup for #904
I found a way to initialize newCostSoFar in `Pathfinder::findGroundPath` without breaking compat. Because the variable is used in a loop, it stays the same when it is not assigned. Moving the variable up one scope in VC6 allows us to initialize it properly. This can, at least theoretically, fix mismatches.
This PR also initializes some more variables in the same file. Those variables don't seem to be used before assigning to them, but better safe than sorry.

[GEN][ZH] Initialize all uninitialized variables in AIPathfind

---

Generals/Code/GameEngine/Source/Common/Recorder.cpp
GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp

This change adds additional information on Replay playback CRC mismatch.
The Frame Number is useful to then use that for command line `-DebugCRCFromFrame N -DebugCRCUntilFrame N+X`.

[GEN][ZH] Add message with additional information on CRC mismatch in Replay playback

---

Generals/Code/GameEngine/Source/Common/Dict.cpp
Generals/Code/GameEngine/Source/Common/MiniLog.cpp
Generals/Code/GameEngine/Source/Common/System/AsciiString.cpp
Generals/Code/GameEngine/Source/Common/System/UnicodeString.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DModelDraw.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
GeneralsMD/Code/GameEngine/Source/Common/Dict.cpp
GeneralsMD/Code/GameEngine/Source/Common/MiniLog.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/AsciiString.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/UnicodeString.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DModelDraw.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp

Static / global variable:
https://github.com/TheSuperHackers/GeneralsGameCode/blob/08b06e3616cb20897bb3c4d6a6f1abaa53686be3/GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp#L353
https://github.com/TheSuperHackers/GeneralsGameCode/blob/08b06e3616cb20897bb3c4d6a6f1abaa53686be3/GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp#L152-L169
I ran into an issue where the initialization of  global `TheStatDump` happened before the initialization of global `TheDynamicMemoryAllocator` which is used for `AsciiString` (aka static initialization order fiasco). This PR fixes a couple of places where that may happen, though I only noticed it for `TheStatDump`.
I've also added a couple of `DEBUG_ASSERTCRASH`. They'll work better with …

[GEN][ZH] Fix static initialization order for StatDumpClass and LogClass

---

Core/Libraries/Source/WWVegas/WWLib/mutex.h
Core/Libraries/Source/profile/internal.h

`std::atomic_flag::test_and_set` is an atomic read-modify-write (RMW) operation. I think it makes more sense to use `std::memory_order_acq_rel` instead of `std::memory_order_acquire`, though in my experience x86 doesn't seem particularly sensitive to using the appropriate memory order.

[CORE] Change memory order for std::atomic_flag::test_and_set in FastCriticalSectionClass and ProfileFastCS

---

Generals/Code/GameEngine/Include/GameClient/View.h
Generals/Code/GameEngine/Source/GameLogic/AI/AIPlayer.cpp
Generals/Code/GameEngine/Source/GameLogic/Map/TerrainLogic.cpp
Generals/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptActions.cpp
Generals/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DBridgeBuffer.h
Generals/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DShaderManager.h
Generals/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DView.h
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DBridgeBuffer.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DShaderManager.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp
GeneralsMD/Code/GameEngine/Include/GameClient/View.h
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIPlayer.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Map/TerrainLogic.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptActions.cpp
GeneralsMD/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DBridgeBuffer.h
GeneralsMD/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DShaderManager.h
GeneralsMD/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DView.h
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DBridgeBuffer.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DShaderManager.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp

These enums proved to be a source of compilation errors when compiling with clang-cl. This PR consists of two changes:
1. Change out-dated style from `enum EnumName` to `EnumName`.
2. Forward declare enums where needed.

[GEN][ZH] Fix clang compile errors with enums FilterTypes, FilterModes, BodyDamageType

---

Generals/Code/GameEngine/Source/Common/GlobalData.cpp
GeneralsMD/Code/GameEngine/Source/Common/GlobalData.cpp

* Follow up for #965
This change sets the correct fake CRC value for Zero Hour CD 1.04 (and the other unused ones). Unclear why I had these wrong. The ones for Generals are correct.

[ZH] Set correct fake CRC for Zero Hour CD 1.04

---

Generals/Code/GameEngine/Source/GameClient/GUI/LoadScreen.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/LoadScreen.cpp

The initial progressbar after the intro is delayed 3 seconds for no reason. I don't know why they included this. Maybe they intended to implement a fadein effect and never got to it. Didn't happen for `-quickstart`. This PR removes the delay and also some commented code.

[GEN][ZH] Remove unnecessary 3 seconds delay from game startup

---

Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanGameOptionsMenu.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanLobbyMenu.cpp
Generals/Code/GameEngine/Source/GameNetwork/Connection.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanGameOptionsMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanLobbyMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/GarrisonContain.cpp
GeneralsMD/Code/GameEngine/Source/GameNetwork/Connection.cpp

Fix some wrong #if expressions.
I changed `#if defined __DEBUG || defined RTS_INTERNAL` because those were not compiling with RTS_INTERNAL and DEBUG_CRASHING disabled.

[GEN][ZH] Fix some RTS_DEBUG and RTS_INTERNAL defines

---

Core/Libraries/Source/WWVegas/WWLib/refcount.h
Generals/Code/GameEngine/Include/Common/StateMachine.h
GeneralsMD/Code/GameEngine/Include/Common/StateMachine.h

* Fixes #1064
* Follow up for #890
This changes the reference counter implementation for `StateMachine` to avoid mismatch with Retail.
The previous reference counter changes the struct layout of `StateMachine`, which then changed the generated assembler code of many functions that interact with `StateMachine`.

[GEN][ZH] Change reference counter implementation for StateMachine to avoid mismatch with Retail

---

Generals/Code/GameEngine/Include/Common/TunnelTracker.h
Generals/Code/GameEngine/Source/Common/RTS/TunnelTracker.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/OpenContain.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp

* Follow up for #921
* Follow up for #1006
This change is a minor refactor to make the code in OpenContain and TunnelContain a bit more consistent.  It also removes a redundant `owningPlayer->getTunnelSystem()->isInContainer()` test. It intents to not change functionality.

[GEN][ZH] Refactor evacuation code in OpenContain, TunnelContain

---

Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp

* Fixes #103
This change prevents IP options from changing when changing the Display Resolution in the Options Menu. This is a critical issue, because this is the number one reason why people are unable to connect to Networks after their IP was changed without notice.

[GEN][ZH] Prevent IP options from changing when changing the Display Resolution in the Options Menu

---

Core/Tools/ImagePacker/Source/WindowProcedures/PreviewProc.cpp
Core/Tools/W3DView/BoneMgrDialog.cpp
Core/Tools/W3DView/HierarchyPropPage.cpp
Core/Tools/W3DView/MainFrm.cpp
Core/Tools/W3DView/MeshPropPage.cpp
Generals/Code/Tools/ParticleEditor/CColorAlphaDialog.cpp
Generals/Code/Tools/WorldBuilder/include/wbview3d.h
Generals/Code/Tools/WorldBuilder/src/DrawObject.cpp
Generals/Code/Tools/WorldBuilder/src/WorldBuilderDoc.cpp
GeneralsMD/Code/Tools/ParticleEditor/CColorAlphaDialog.cpp
GeneralsMD/Code/Tools/WorldBuilder/include/wbview3d.h
GeneralsMD/Code/Tools/WorldBuilder/src/DrawObject.cpp
GeneralsMD/Code/Tools/WorldBuilder/src/WorldBuilderDoc.cpp
GeneralsMD/Code/Tools/wdump/chunk_d.cpp

* Relates to: https://github.com/TheSuperHackers/GeneralsGameCode/pull/888
This PR fixes a couple of compiler errors when compiling with clang-cl. None of these changes are in projects required to build the game executables.
There are still a few projects that cannot be compiled with clang-cl, because they're full of MFC code. The most glaring issue is attempting to store a pointer to a non-static member function from within a static member function.

[CORE][GEN][ZH] Make tools compile with clang-cl in VS2022

---

Core/Tools/mangler/wlib/threadfac.h
Core/Tools/matchbot/wlib/threadfac.h

Fix the recent Pipeline build issues caused by the misused friend and static declarations within threadfac.h.
This exists within mangler and matchbot but appeared to be failing at random.

[CORE] Fix compile error "friend cannot be used with static" in mangler's and matchbot's threadfac.h

---

.github/workflows/ci.yml

This PR updates the continuous integration pipeline to remove VCPKG builds for now and restore the regular VS22 builds for generals.
The VCPKG build options have been added that were missing for zero hour. But i have currently commented them out for future use once other issues with the build pipeline and VCPKG are resolved.
The internal builds were also removed as these are no longer seen as useful when we can live debug.
Each VCPKG build was taking 30 minutes per preset to build, which results in the build runners being blocked for long periods per PR.

[GITHUB] Disable VCPKG builds and remove INTERNAL builds to speed up CI

---

Core/Libraries/Source/WWVegas/WW3D2/statistics.cpp

This change prevent dereferencing NULL pointer 't' in Record_Texture_End().
> **Core\Libraries\Source\WWVegas\WW3D2\statistics.cpp(139): warning C6011: Dereferencing NULL pointer 't'.**

[CORE] Prevent dereferencing NULL pointer 't' in Record_Texture_End()

---

Generals/Code/GameEngine/Include/Common/GlobalData.h
GeneralsMD/Code/GameEngine/Include/Common/GlobalData.h

This change makes debugging more comfortable by being able to see TheGlobalData values on hover in the debugger.

[GEN][ZH] Replace TheGlobalData macro with inline variable to make debugging easier

---

Generals/Code/GameEngine/Source/Common/System/FileSystem.cpp
Generals/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/FileSystem.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp

* Follow up for #1058
#1058 added a new check for testing if a file is under a specific base path. In case it was not, a DEBUG_CRASH was triggered, before returning false.
This leads to an assert when starting the shell map, as the code in `GameLogic::startNewGame` explicitly sanity checks that the map is not in the save directory.
This type of sanity checking should not cause assertion failures or debug logging, so it's better to move the responsibility for reacting to those cases to the caller. This change removes the DEBUG_CRASH from `FileSystem::isPathInDirectory`, downgrades is to a DEBUG_LOG and places it in `GameState::portableMapPathToRealMapPath`.

[GEN][ZH] Downgrade debug assertion to log for isPathInDirectory

---

GeneralsMD/Code/Tools/WorldBuilder/src/WorldBuilderDoc.cpp

**Can be reproduced by starting the World Builder (using a debug build) and creating a new map.**
`PolygonTrigger::deleteTriggers()` deallocates an instance of `PolygonTrigger` here:
https://github.com/TheSuperHackers/GeneralsGameCode/blob/ef5fea1e4c5e7aaa95f1e4c1c1134888fc5fb0b4/GeneralsMD/Code/Tools/WorldBuilder/src/WorldBuilderDoc.cpp#L1274-L1278
but there may still be pointers to this object in `TheLayersList->mLayers`, so there would be use-after-free and crash here (line 450):
https://github.com/TheSuperHackers/GeneralsGameCode/blob/ef5fea1e4c5e7aaa95f1e4c1c1134888fc5fb0b4/GeneralsMD/Code/Tools/WorldBuilder/src/LayersList.cpp#L449-L452
`triggerIt` no longer points to a valid instance of `PolygonTrigger` because that had been deallocated.

[ZH] Fix heap-use-after-free in LayersList::updateUIFromList() when creating a new map in World Builder

---

Generals/Code/Tools/WorldBuilder/src/WorldBuilderDoc.cpp

* Relates to: https://github.com/TheSuperHackers/GeneralsGameCode/pull/1098
This PR ports an old bug fix from ZH to Gen and a new one described in the above PR.
Code in ZH:
https://github.com/TheSuperHackers/GeneralsGameCode/blob/ef5fea1e4c5e7aaa95f1e4c1c1134888fc5fb0b4/GeneralsMD/Code/Tools/WorldBuilder/src/WorldBuilderDoc.cpp#L1273-L1283

[GEN] Backport bug fixes in CWorldBuilderDoc::OnNewDocument from Zero Hour

---

Core/Libraries/Source/WWVegas/WWLib/always.h
Dependencies/Utility/Utility/CppMacros.h
Generals/Code/GameEngine/Source/Common/RandomValue.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ScoreScreen.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/GameWindowTransitionsStyles.cpp
Generals/Code/GameEngine/Source/GameClient/GameText.cpp
Generals/Code/GameEngine/Source/GameClient/MessageStream/WindowXlat.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/HackInternetAIUpdate.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/JetAIUpdate.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/MissileAIUpdate.cpp
Generals/Code/GameEngine/Source/GameLogic/ScriptEngine/Scripts.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/meshmdlio.cpp
GeneralsMD/Code/GameEngine/Source/Common/RandomValue.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ScoreScreen.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GameWindowTransitionsStyles.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GameText.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/WindowXlat.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/HackInternetAIUpdate.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/JetAIUpdate.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/MissileAIUpdate.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/SpecialAbilityUpdate.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/Scripts.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/meshmdlio.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/textureloader.cpp

This change annotates fallthroughs in GameEngine to suppress warnings and make the intent clear.
```
GeneralsMD\Code\GameEngine\Source\Common\RandomValue.cpp(387): warning C26819: Unannotated fallthrough between switch labels (es.78).
```

[GEN][ZH] Annotate fallthrough between various switch case labels

---

Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankTruckDraw.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankTruckDraw.cpp

This change prevents using uninitialized memory 'offset_u' in W3DTankDraw, W3DTankTruckDraw.
It probably is no actual runtime issue.
```
GeneralsMD\Code\GameEngineDevice\Source\W3DDevice\GameClient\Drawable\Draw\W3DTankDraw.cpp(239): warning C6001: Using uninitialized memory 'offset_u'.
GeneralsMD\Code\GameEngineDevice\Source\W3DDevice\GameClient\Drawable\Draw\W3DTankTruckDraw.cpp(419): warning C6001: Using uninitialized memory 'offset_u'.
```

[GEN][ZH] Prevent using uninitialized memory 'offset_u' in W3DTankDraw, W3DTankTruckDraw

---

Generals/Code/GameEngine/Source/GameLogic/Object/Behavior/BridgeScaffoldBehavior.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/BridgeScaffoldBehavior.cpp

This change prevents using uninitialized memory 'start', 'end' in BridgeScaffoldBehavior::update()
It mostly keeps the compiler happy, and is not expected to hit on runtime ever.
```
GeneralsMD\Code\GameEngine\Source\GameLogic\Object\Behavior\BridgeScaffoldBehavior.cpp(199): warning C6001: Using uninitialized memory 'end'.
GeneralsMD\Code\GameEngine\Source\GameLogic\Object\Behavior\BridgeScaffoldBehavior.cpp(199): warning C6001: Using uninitialized memory 'start'.
```

[GEN][ZH] Prevent using uninitialized memory 'start', 'end' in BridgeScaffoldBehavior::update()

---

Generals/Code/Libraries/Source/WWVegas/WW3D2/assetmgr.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/assetmgr.cpp

This change prevents dereferencing NULL pointer 'tex' in WW3DAssetManager::Get_Texture().
It likely is no actual problem in the runtime.
```
GeneralsMD\Code\Libraries\Source\WWVegas\WW3D2\assetmgr.cpp(1125): warning C6011: Dereferencing NULL pointer 'tex'.
```

[GEN][ZH] Prevent dereferencing NULL pointer 'tex' in WW3DAssetManager::Get_Texture()

---

Generals/Code/GameEngine/Source/GameClient/GUI/LoadScreen.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/LoadScreen.cpp

This change prevents reading some invalid data in LoadScreen on exceptional code paths.
This likely is no issue in the runtime.
```
GeneralsMD\Code\GameEngine\Source\GameClient\GUI\LoadScreen.cpp(1540): warning C6385: Reading invalid data from 'this->m_progressBars':  the readable size is '32' bytes, but 'this->m_playerLookup[playerId]' bytes may be read.
GeneralsMD\Code\GameEngine\Source\GameClient\GUI\LoadScreen.cpp(1540): warning C6385: Reading invalid data from 'this->m_playerLookup':  the readable size is '32' bytes, but 'playerId' bytes may be read.
GeneralsMD\Code\GameEngine\Source\GameClient\GUI\LoadScreen.cpp(1902): warning C6385: Reading invalid data from 'this->m_progressBars':  the readable size is '32' bytes, but 'this->m_playerLookup[playerId]' bytes may be read. …
```

[GEN][ZH] Prevent reading invalid data in LoadScreen

---

Generals/Code/GameEngine/Source/GameLogic/Object/Update/EMPUpdate.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/EMPUpdate.cpp

This change fixes using uninitialized memory 'curVictim' in EMPUpdate and makes the compiler happy.
This is only a theoretical or Mod issue. The default EffectRadius is larger than 0 and the ones specified in INI files are larger than 0 as well.
```
GeneralsMD\Code\GameEngine\Source\GameLogic\Object\Update\EMPUpdate.cpp(214): warning C6001: Using uninitialized memory 'curVictim'.
GeneralsMD\Code\GameEngine\Source\GameLogic\Object\Update\EMPUpdate.cpp(515): warning C6001: Using uninitialized memory 'curVictim'.
```

[GEN][ZH] Fix using uninitialized memory 'curVictim' in EMPUpdate

---

Generals/Code/GameEngine/Source/GameLogic/AI/AI.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AI.cpp

This change prevents dereferencing NULL pointer 'TheAI' in AI::parseAiDataDefinition() and makes the compiler happy.
```
GeneralsMD\Code\GameEngine\Source\GameLogic\AI\AI.cpp(436): warning C6011: Dereferencing NULL pointer 'TheAI'.
```

[GEN][ZH] Prevent dereferencing NULL pointer 'TheAI' in AI::parseAiDataDefinition()

---

Generals/Code/GameEngine/Source/GameLogic/Object/Update/PhysicsUpdate.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/PhysicsUpdate.cpp

This change prevents dereferencing NULL pointer 'that' in PhysicsBehavior::transferVelocityTo() to make the compiler happy.
```
GeneralsMD\Code\GameEngine\Source\GameLogic\Object\Update\PhysicsUpdate.cpp(1071): warning C6011: Dereferencing NULL pointer 'that'.
```

[GEN][ZH] Prevent dereferencing NULL pointer 'that' in PhysicsBehavior::transferVelocityTo()

---

Generals/Code/GameEngine/Source/GameNetwork/DisconnectManager.cpp
GeneralsMD/Code/GameEngine/Source/GameNetwork/DisconnectManager.cpp

This change fixes a heap-use-after-free in DisconnectManager::update().
This problem would only happen in Online matches when the Disconnect Menu pops up.
> **GeneralsMD\Code\GameEngine\Source\GameNetwork\DisconnectManager.cpp(145): warning C26815: The pointer is dangling because it points at a temporary instance which was destroyed.**

[GEN][ZH] Fix heap-use-after-free in DisconnectManager::update()

---

Generals/Code/Libraries/Source/WWVegas/WW3D2/dazzle.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dazzle.cpp

This change prevents buffer overrun while writing to 'new_types', 'new_lensflares' in DazzleRenderObjClass.
Dazzle is unused code, so this should be inconsequential for the game.
```
GeneralsMD\Code\Libraries\Source\WWVegas\WW3D2\dazzle.cpp(689): warning C6386: Buffer overrun while writing to 'new_types':  the writable size is 'new_count*4' bytes, but '8' bytes might be written.
GeneralsMD\Code\Libraries\Source\WWVegas\WW3D2\dazzle.cpp(713): warning C6386: Buffer overrun while writing to 'new_lensflares':  the writable size is 'new_count*4' bytes, but '8' bytes might be written.
```

[GEN][ZH] Prevent buffer overrun while writing to 'new_types', 'new_lensflares' in DazzleRenderObjClass

---

Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8wrapper.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dx8wrapper.cpp

This change fixes dereferencing NULL pointer 'ext' in DX8Wrapper::_Create_DX8_Surface()
```
GeneralsMD\Code\Libraries\Source\WWVegas\WW3D2\dx8wrapper.cpp(2949): warning C6011: Dereferencing NULL pointer 'ext'. See line 2947 for an earlier location where this can occur
GeneralsMD\Code\Libraries\Source\WWVegas\WW3D2\dx8wrapper.cpp(2949): warning C6387: 'ext' could be '0':  this does not adhere to the specification for the function 'strlen'.
```

[GEN][ZH] Fix dereferencing NULL pointer 'ext' in DX8Wrapper::_Create_DX8_Surface()

---

Generals/Code/GameEngine/Source/GameNetwork/GUIUtil.cpp
Generals/Code/GameEngine/Source/GameNetwork/GameInfo.cpp
GeneralsMD/Code/GameEngine/Source/GameNetwork/GUIUtil.cpp
GeneralsMD/Code/GameEngine/Source/GameNetwork/GameInfo.cpp

This change removes unnecessary NULL pointer tests in UpdateSlotList() and makes the compiler happy.
The slot pointers are always initialized and not expected to be NULL ever.
```
GeneralsMD\Code\GameEngine\Source\GameNetwork\GUIUtil.cpp(458): warning C6011: Dereferencing NULL pointer 'slot'.
```

[GEN][ZH] Remove unnecessary NULL pointer tests in UpdateSlotList()

---

Generals/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptActions.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptActions.cpp

This change prevents dereferencing NULL pointer 'button' in ScriptActions::doCameoFlash() and makes the compiler happy.
I think this code path could be reached by handing over a button name that does not exist. Whether this happens in the original game, I do not know. Probably does not.
```
GeneralsMD\Code\GameEngine\Source\GameLogic\ScriptEngine\ScriptActions.cpp(2640): warning C6011: Dereferencing NULL pointer 'button'.
```

[GEN][ZH] Prevent dereferencing NULL pointer 'button' in ScriptActions::doCameoFlash()

---

Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DShaderManager.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DShaderManager.cpp

This change prevents using uninitialized memory 'hr' in W3DShaderManager::LoadAndCreateD3DShader() and makes the compiler happy.
This will not happen in practice but the compiler complained here because technically a Bool could be different from values TRUE and FALSE.
```
GeneralsMD\Code\GameEngineDevice\Source\W3DDevice\GameClient\W3DShaderManager.cpp(3057): warning C6001: Using uninitialized memory 'hr'.
```

[GEN][ZH] Prevent using uninitialized memory 'hr' in W3DShaderManager::LoadAndCreateD3DShader()

---

Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DProjectedShadow.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DProjectedShadow.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp

This change just adds missing break keywords between switch labels in W3DProjectedShadow, W3DDisplay, W3DWater to make the compiler happy.
There is no functional change at all.

[GEN][ZH] Add missing break keywords between switch labels in W3DProjectedShadow, W3DDisplay, W3DWater

---

Generals/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarScheme.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarScheme.cpp

This change fixes dereferencing NULL pointer 'CBScheme->m_buttonQueueImage' in ControlBarSchemeManager::preloadAssets().
```
GeneralsMD\Code\GameEngine\Source\GameClient\GUI\ControlBar\ControlBarScheme.cpp(1007): warning C6011: Dereferencing NULL pointer 'CBScheme->m_buttonQueueImage'.
```

[GEN][ZH] Fix dereferencing NULL pointer 'CBScheme->m_buttonQueueImage' in ControlBarSchemeManager::preloadAssets()

---

Generals/Code/GameEngine/Source/GameClient/GUI/GameWindowManagerScript.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GameWindowManagerScript.cpp

This change fixes using uninitialized memory 'window' in GameWindowManagerScript's createGadget() and makes the compiler happy.
Basically this function would return an uninitialized pointer if the gadget type was not recognized. I put a breakpoint and visited a few menus and was unable to hit this. It probably is no concern for the game runtime.
```
GeneralsMD\Code\GameEngine\Source\GameClient\GUI\GameWindowManagerScript.cpp(2019): warning C6001: Using uninitialized memory 'window'.
```

[GEN][ZH] Fix using uninitialized memory 'window' in createGadget()

---

Generals/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp

This change fixes dereferencing NULL pointer 'victimObj' in WeaponTemplate::estimateWeaponTemplateDamage() and makes the compiler happy.
This would be a 100% crash if this function was called with the positional argument, but it appears this is only ever called with the object argument, so it does not crash in the current game.
```
GeneralsMD\Code\GameEngine\Source\GameLogic\Object\Weapon.cpp(601): warning C6011: Dereferencing NULL pointer 'victimObj'.
GeneralsMD\Code\GameEngine\Source\GameLogic\Object\Weapon.cpp(615): warning C6011: Dereferencing NULL pointer 'victimObj'.
```

[GEN][ZH] Fix dereferencing NULL pointer 'victimObj' in WeaponTemplate::estimateWeaponTemplateDamage()

---

GeneralsMD/Code/GameEngine/Source/Common/StateMachine.cpp

This change prevents dereferencing NULL pointer 'state' in StateMachine::xfer() to make the compiler happy.
It appears the EA developer tried to avoid some crashing, because that code is different from Generals, but he did not write the null handling correctly, so I refactored it a bit to avoid crashing. Whether this error handling is useful I do not know.
```
GeneralsMD\Code\GameEngine\Source\Common\StateMachine.cpp(860): warning C6011: Dereferencing NULL pointer 'state'.
```

[ZH] Prevent dereferencing NULL pointer 'state' in StateMachine::xfer()

---

Generals/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/CrateCollide.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/CrateCollide.cpp

This change removes an unnecessary NULL pointer test in CrateCollide::isValidToExecute() and makes the compiler happy.
```
GeneralsMD\Code\GameEngine\Source\GameLogic\Object\Collide\CrateCollide\CrateCollide.cpp(179): warning C6011: Dereferencing NULL pointer 'md'. See line 162 for an earlier location where this can occur
```

[GEN][ZH] Remove unnecessary NULL pointer test in CrateCollide::isValidToExecute()

---

Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp

This change prevents dereferencing NULL pointer 'pbmi' in CreateBMPFile() and makes the compiler happy.
This is no practical issue.
```
GeneralsMD\Code\GameEngineDevice\Source\W3DDevice\GameClient\W3DDisplay.cpp(2913): warning C28182: Dereferencing NULL pointer. 'pbmi' contains the same NULL value as 'LocalAlloc()`2912' did.
GeneralsMD\Code\GameEngineDevice\Source\W3DDevice\GameClient\W3DDisplay.cpp(2938): warning C28182: Dereferencing NULL pointer. 'pbih' contains the same NULL value as 'LocalAlloc()`2912' did. See line 2913 for an earlier location where this can occur
```

[GEN][ZH] Prevent dereferencing NULL pointer 'pbmi' and memory leaks in CreateBMPFile()

---

Generals/Code/GameEngine/Source/Common/RTS/Money.cpp
GeneralsMD/Code/GameEngine/Source/Common/RTS/Money.cpp

Money withdraw and deposit audio is no longer accessed if it ends up unused due to `playSound` being false. Not a massive performance implication. The code reads somewhat cleaner.

[GEN][ZH] Do not acquire money transaction audio if the play sound parameter is false

---

Generals/Code/GameEngine/Source/Common/Dict.cpp
GeneralsMD/Code/GameEngine/Source/Common/Dict.cpp

This change prevents using uninitialized memory 'delta' in Dict::ensureUnique()
```
GeneralsMD\Code\GameEngine\Source\Common\Dict.cpp(192): warning C6001: Using uninitialized memory 'delta'.
```

[GEN][ZH] Prevent using uninitialized memory 'delta' in Dict::ensureUnique()

---

Generals/Code/GameEngine/Source/GameLogic/Object/PartitionManager.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/PartitionManager.cpp

This change prevents using uninitialized memory 'result' in PartitionData::calcMaxCoiForShape() to make the compiler happy.
This is effectively just a refactor because this is impossible to happen because we expect passing valid enum values only. Handling default case is just courtesy.
```
GeneralsMD\Code\GameEngine\Source\GameLogic\Object\PartitionManager.cpp(2181): warning C6001: Using uninitialized memory 'result'.
```

[GEN][ZH] Prevent using uninitialized memory 'result' in PartitionData::calcMaxCoiForShape()

---

Generals/Code/GameEngine/Source/GameLogic/Object/PartitionManager.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/PartitionManager.cpp

This change fixes GEOMETRY_SPHERE & GEOMETRY_CYLINDER treated as GEOMETRY_BOX in PartitionData::calcMaxCoiForShape()
I do not know the implications of this change, so I put this behind the !RETAIL_COMPATIBLE_CRC macro.
I did load a map with all faction units and tested if the result would be different for the 2 cases but that breakpoint never hit. So the missing break is perhaps inconsequential in the game.
```
GeneralsMD\Code\GameEngine\Source\GameLogic\Object\PartitionManager.cpp(2173): warning C26819: Unannotated fallthrough between switch labels (es.78).
```

[GEN][ZH] Fix GEOMETRY_SPHERE & GEOMETRY_CYLINDER treated as GEOMETRY_BOX in PartitionData::calcMaxCoiForShape()

---

Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupSaveLoad.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupSaveLoad.cpp

This change removes a unnecessary NULL pointer test in SaveLoadMenuSystem() and makes the compiler happy.
> GeneralsMD\Code\GameEngine\Source\GameClient\GUI\GUICallbacks\Menus\PopupSaveLoad.cpp(796): warning C6011: Dereferencing NULL pointer 'selectedGameInfo'.

[GEN][ZH] Remove unnecessary NULL pointer test in SaveLoadMenuSystem()

---

Generals/Code/GameEngine/Source/GameLogic/AI/AIPlayer.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIPlayer.cpp

This change suppresses a compile warning about a buffer overrun while writing to 'this->m_structuresToRepair' in AIPlayer::repairStructure()
m_structuresInQueue should never become larger than MAX_STRUCTURES_TO_REPAIR in practice. But the static analyzer does not see this. So rewriting the condition helps the compiler understand.
> GeneralsMD\Code\GameEngine\Source\GameLogic\AI\AIPlayer.cpp(2308): warning C6386: Buffer overrun while writing to 'this->m_structuresToRepair':  the writable size is '8' bytes, but 'm_structuresInQueue' bytes might be written.

[GEN][ZH] Suppress compile warning about buffer overrun while writing to 'm_structuresToRepair' in AIPlayer::repairStructure()

---

Generals/Code/GameEngine/Source/GameLogic/Object/Damage/TransitionDamageFX.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Damage/TransitionDamageFX.cpp

This change prevents dereferencing NULL pointer 'damageSource' in TransitionDamageFX::onBodyDamageStateChange() and makes the compiler happy.
In practice, `damageSource` is not NULL.
> GeneralsMD\Code\GameEngine\Source\GameLogic\Object\Damage\TransitionDamageFX.cpp(378): warning C6011: Dereferencing NULL pointer 'damageSource'.

[GEN][ZH] Prevent dereferencing NULL pointer 'damageSource' in TransitionDamageFX::onBodyDamageStateChange()

---

Generals/Code/GameEngine/Source/GameLogic/Object/Update/BoneFXUpdate.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/BoneFXUpdate.cpp

This change prevents dereferencing NULL pointer 'drawable' in BoneFXUpdate::resolveBoneLocations()
I do not know if this would have ever crashed the game. Probably not.
I removed the NULL check for Module Data because that is unnecessary. Other functions in this class also do not test it.
> GeneralsMD\Code\GameEngine\Source\GameLogic\Object\Update\BoneFXUpdate.cpp(536): warning C6011: Dereferencing NULL pointer 'drawable'.

[GEN][ZH] Prevent dereferencing NULL pointer 'drawable' in BoneFXUpdate::resolveBoneLocations()

---

Core/Libraries/Source/WWVegas/WWDownload/FTP.CPP

This change prevents using uninitialized memory 'listline' in Cftp::FindFile() and makes the compiler happy.
I do not know why `listline` is static, but it does not matter for this fix. Maybe there is a reason. Whether this invalid read happened on runtime, I do not know. Maybe it never hit.
> Core\Libraries\Source\WWVegas\WWDownload\FTP.CPP(822): warning C6054: String 'listline' might not be zero-terminated.

[CORE] Prevent using uninitialized memory 'listline' in Cftp::FindFile()

---

Core/Libraries/Source/WWVegas/WW3D2/rendobj.cpp

This change prevents using uninitialized memory 'name' in RenderObjPersistFactoryClass::Load() and makes the compiler happy.
```
Core\Libraries\Source\WWVegas\WW3D2\rendobj.cpp(1248): warning C6001: Using uninitialized memory 'name'.
Core\Libraries\Source\WWVegas\WW3D2\rendobj.cpp(1248): warning C6054: String 'name' might not be zero-terminated.
```

[CORE] Prevent using uninitialized memory 'name' in RenderObjPersistFactoryClass::Load()

---

Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DScene.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DScene.cpp

This change removes an unnecessary NULL pointer test in RTS3DScene::Visibility_Check() and makes the compiler happy.
> GeneralsMD\Code\GameEngineDevice\Source\W3DDevice\GameClient\W3DScene.cpp(487): warning C6011: Dereferencing NULL pointer 'TheGameLogic'.

[GEN][ZH] Remove unnecessary NULL pointer test in RTS3DScene::Visibility_Check()

---

Generals/Code/GameEngine/Source/Common/GameLOD.cpp
GeneralsMD/Code/GameEngine/Source/Common/GameLOD.cpp

This change prevents reading invalid data from 'this->m_numLevelPresets' in GameLODManager::newLODPreset() and makes the compiler happy.
```
GeneralsMD\Code\GameEngine\Source\Common\GameLOD.cpp(261): warning C6385: Reading invalid data from 'this->m_numLevelPresets':  the readable size is '12' bytes, but 'index' bytes may be read.
GeneralsMD\Code\GameEngine\Source\Common\GameLOD.cpp(264): warning C6385: Reading invalid data from 'this->m_lodPresets':  the readable size is '1920' bytes, but 'index' bytes may be read.
GeneralsMD\Code\GameEngine\Source\Common\GameLOD.cpp(261): warning C33011: Unchecked upper bound for enum index used as index..
```
In practice this is no issue, but the compiler rightfully warns about this because the enum has a value with a negative numeral and enum value …

[GEN][ZH] Prevent reading invalid data from 'm_numLevelPresets' in GameLODManager::newLODPreset()

---

Generals/Code/GameEngine/Source/Common/Thing/Module.cpp
GeneralsMD/Code/GameEngine/Source/Common/Thing/Module.cpp

This change prevents dereferencing NULL pointer 'theTemplate' in UpgradeMuxData::getUpgradeActivationMasks() and makes the compiler happy.
> GeneralsMD\Code\GameEngine\Source\Common\Thing\Module.cpp(321): warning C6011: Dereferencing NULL pointer 'theTemplate'.
It looks like this code could crash the game when specifying a bad string in the CommandButton.ini
```
CommandButton Command_UpgradeChinaFanaticism
Upgrade       = Upgrade_Fanaticism // Make this empty or NONE
...
```
The crash probably makes no difference to the user facing outcome, because it would do `throw INI_INVALID_DATA` anyway.

[GEN][ZH] Prevent dereferencing NULL pointer 'theTemplate' in UpgradeMuxData::getUpgradeActivationMasks()

---

Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DScene.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DScene.cpp

* Reverts #1146
* Fixes #1182
#1146 introduced crashing in World Builder.
The compiler warning is now fixed by adding another NULL check in this function.
> GeneralsMD\Code\GameEngineDevice\Source\W3DDevice\GameClient\W3DScene.cpp(487): warning C6011: Dereferencing NULL pointer 'TheGameLogic'.

[GEN][ZH] Fix World Builder crashing on drawing scene, introduced by previous change #1146

---

Generals/Code/Tools/WorldBuilder/include/ScorchOptions.h
Generals/Code/Tools/WorldBuilder/include/mapobjectprops.h
Generals/Code/Tools/WorldBuilder/src/ScorchOptions.cpp
Generals/Code/Tools/WorldBuilder/src/mapobjectprops.cpp
GeneralsMD/Code/Tools/WorldBuilder/include/ScorchOptions.h
GeneralsMD/Code/Tools/WorldBuilder/include/mapobjectprops.h
GeneralsMD/Code/Tools/WorldBuilder/src/ScorchOptions.cpp
GeneralsMD/Code/Tools/WorldBuilder/src/mapobjectprops.cpp

**Reproduction steps: Start World Builder (debug build) and tick "Enabled" in the "Object Properties" window. This will result in a debug assertion: "front() called on empty vector".**
Notice how a pointer to the first element of `m_allSelectedDicts` is taken without checking whether the vector is empty or not (line 1436):
https://github.com/TheSuperHackers/GeneralsGameCode/blob/51afe0c6d2f5ab1debc801e414db8fc1b7a03d49/GeneralsMD/Code/Tools/WorldBuilder/src/mapobjectprops.cpp#L1418-L1441
I chose to not add size checks everywhere but keep the code functionally the same except calling front() on an empty vector. As long as the vector is empty, the code in `DictItemUndoable::DictItemUndoable` won't attempt to dereference the front pointer so it can be `NULL`.
Would need to be replicated in …

[GEN][ZH] Check vector size before accessing first element in World Builder's MapObjectProps and ScorchOptions

---

Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/ControlBarCallback.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/ControlBarCallback.cpp

This change prevents dereferencing NULL pointer 'TheControlBar', 'window' in ControlBarCallback and makes the compiler happy.
Practically this never crashes because these globals are not meant to be null. At least not in the regular game client.
```
GeneralsMD\Code\GameEngine\Source\GameClient\GUI\GUICallbacks\ControlBarCallback.cpp(515): warning C6011: Dereferencing NULL pointer 'TheControlBar'.
GeneralsMD\Code\GameEngine\Source\GameClient\GUI\GUICallbacks\ControlBarCallback.cpp(563): warning C6011: Dereferencing NULL pointer 'TheControlBar'.
GeneralsMD\Code\GameEngine\Source\GameClient\GUI\GUICallbacks\ControlBarCallback.cpp(598): warning C6011: Dereferencing NULL pointer 'TheControlBar'.
```

[GEN][ZH] Prevent dereferencing NULL pointer 'TheControlBar', 'window' in ControlBarCallback

---

Generals/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp

This change fixes the missing unit voice when attacking the ground due wrong fallthrough at switch case GameMessage::MSG_DO_FORCE_ATTACK_GROUND in pickAndPlayUnitVoiceResponse()
In the original game, units would not play their attack voice when attacking the ground, except for the USA Tomahawk because it uses the VoiceBombard audio.
This issue is caused by a wrong switch case setup. It was introduced by an original developer who incorrectly added the `case GameMessage::MSG_SWITCH_WEAPONS` between the case `GameMessage::MSG_DO_FORCE_ATTACK_GROUND` and `case GameMessage::MSG_DO_FORCE_ATTACK_OBJECT`.
https://github.com/user-attachments/assets/401aeefe-1f89-4de6-8f88-34260a98bbb6

[GEN][ZH] Fix missing unit voice when attacking the ground

---

Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupReplay.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupReplay.cpp

This change fixes a missing break label at switch case GEM_UPDATE_TEXT in PopupReplaySystem()
I tested the replay save text update (in front of the LAN ScoreScreen) and it worked fine before and after this change, so this appears to have had no user facing issue.

[GEN][ZH] Fix missing break at switch case GEM_UPDATE_TEXT in PopupReplaySystem()

---

Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLGameSetupMenu.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLLobbyMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLGameSetupMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLLobbyMenu.cpp

This change fixes missing break labels at switch case PeerResponse::PEERRESPONSE_DISCONNECT in WOLGameSetupMenuUpdate(), WOLLobbyMenuUpdate()
Both fall throughs should be inconsequential because there were no bad side effects.
In `WOLLobbyMenuUpdate()` it would not create a staging room, because `resp.createStagingRoom.result` would not be 0 because `resp.discon.reason` has no 0 enum value (they are in the same union).
In `WOLGameSetupMenuUpdate()` it would not do anything after the fall through, because `resp.command` will be empty.

[GEN][ZH] Fix missing break at switch case PeerResponse::PEERRESPONSE_DISCONNECT in WOLGameSetupMenuUpdate(), WOLLobbyMenuUpdate()

---

Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8wrapper.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dx8wrapper.cpp

This change fixes a wrong returned name for D3DTSS_TEXTURETRANSFORMFLAGS in DX8Wrapper::Get_DX8_Texture_Stage_State_Value_Name() because of a missing break label.
This affects some debug logging and is not important.

[GEN][ZH] Fix wrong returned name for D3DTSS_TEXTURETRANSFORMFLAGS in DX8Wrapper::Get_DX8_Texture_Stage_State_Value_Name()

---

Core/Tools/WW3D/max2w3d/vchannel.cpp

[CORE] Fix memset zero in max2w3d's VectorChannelClass::SaveAdaptiveDelta()

---

Generals/Code/GameEngine/Include/Common/GlobalData.h
Generals/Code/GameEngine/Source/Common/GlobalData.cpp
GeneralsMD/Code/GameEngine/Include/Common/GlobalData.h
GeneralsMD/Code/GameEngine/Source/Common/GlobalData.cpp

* Fixes #1083
* Follow up for #1068 
#1068 has introduced a bug where `GlobalData::m_exeCRC` remained 0 after `GameEngine::init`. This happened because GlobalData was created before `TheFileSystem` (and `TheVersion`) which were required to access the files for CRC generation.
The EXE CRC generation is now moved to `GlobalData::init`, which is called after `TheFileSystem` (and `TheVersion`) is initialized, and therefore fixes this issue.
`GlobalData::init` is also called by all tools that use `GlobalData`.
There is no user of `GlobalData::m_exeCRC` before `GameEngine::init` is done.

[GEN][ZH] Fix untimely Exe CRC generation in GlobalData

---

Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/InGameUI.cpp

This change removes unnecessary NULL pointer tests in InGameUI and makes the compiler happy.
Unnecessary because `m_worldAnimationList` will not accept adding null elements and will not write null to its elements.
```
GeneralsMD\Code\GameEngine\Source\GameClient\InGameUI.cpp(5406): warning C6011: Dereferencing NULL pointer 'wad'.
```

[GEN][ZH] Remove unnecessary NULL pointer tests in InGameUI

---

GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/ParticleUplinkCannonUpdate.cpp

* Fixes https://github.com/TheSuperHackers/GeneralsGameCode/issues/1204
If a scripted Particle Cannon reaches its last way point before it stops firing, it'll attempt to access a non-existing way point. This is a `nullptr` dereference and crashes the game.

[ZH] Fix crash with USA Particle Cannon when the last scripted target waypoint is reached before the end of the firing sequence

---

Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp

https://github.com/TheSuperHackers/GeneralsGameCode/blob/7e18d29f7270a362caa4df34eebc1a76518f5cc7/GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp#L213-L227
The current logic to show the list of replay files is divided into two parts. First it collects all replay files, and then it attempts to open any found replay files. The former searches all sub directories, but the latter uses only the replay file name and tries to open the file from the base directory.
Considering the following directory layout, GR2 isn't shown but GR1 is shown twice even if the second file is different or empty:
- GoldenReplay1.rep
- SubDirectory:
- GoldenReplay1.rep
- GoldenReplay2.rep
This PR disables the search in sub directories.

[GEN][ZH] Prevent duplicate replays from being shown in the Replay Menu

---

GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/WorldHeightMap.cpp

This change fixes a compiler warning about possibly incorrect order of operations in WorldHeightMap::getPointerToTileData()
```
GeneralsMD\Code\GameEngineDevice\Source\W3DDevice\GameClient\WorldHeightMap.cpp(2437): warning C6269: Possibly incorrect order of operations.
```

[ZH] Fix compiler warning about incorrect order of operations in WorldHeightMap::getPointerToTileData()

---

Generals/Code/GameEngine/Source/GameLogic/AI/AIGroup.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIGroup.cpp

This PR fixes a game crash within AIGroupSell()
I won't post the reproduction steps here due to the nature of this bug.
Talk to me outside of this PR to learn the reproduction steps.

[GEN][ZH] Fix game crash in AIGroup::groupSell()

---

Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp

The game only allows select resolutions with 4:3 aspect ratio and the logic between Generals and Generals ZH is slightly different. With these changes, it's possible to select all supported by display resolutions.
- Extracted duplicated logic for filtering resolutions from `W3DDisplay::getDisplayModeCount` and `W3DDisplay::getDisplayModeDescription` into single function `isResolutionSupported`;
- Allowed all aspect ratios between instead of fixed 4:3;
- Applied the same logic for Generals and Generals ZH.
Fixes #72

[GEN][ZH] Enable resolutions with aspect ratios different from 4:3 in Options Menu

---

Core/GameEngine/Include/Common/GameDefines.h
Generals/Code/GameEngine/Include/Common/Player.h
Generals/Code/GameEngine/Include/GameLogic/AI.h
Generals/Code/GameEngine/Include/GameLogic/Object.h
Generals/Code/GameEngine/Source/GameLogic/AI/AI.cpp
Generals/Code/GameEngine/Source/GameLogic/AI/AIGroup.cpp
Generals/Code/GameEngine/Source/GameLogic/AI/AIPlayer.cpp
Generals/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Object.cpp
Generals/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptActions.cpp
Generals/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptEngine.cpp
Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp
Generals/Code/GameEngine/Source/GameLogic/System/GameLogicDispatch.cpp
GeneralsMD/Code/GameEngine/Include/Common/Player.h
GeneralsMD/Code/GameEngine/Include/GameLogic/AI.h
GeneralsMD/Code/GameEngine/Include/GameLogic/Object.h
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AI.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIGroup.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIPlayer.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Object.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptActions.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptEngine.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogicDispatch.cpp

* Merge after #1212
* Replaces #1004
* Fixes #75
This change fixes a critical problem with AIGroup, that happens all the time in any match, but only crashes the Replay playback when a player is selected. The memory management of AIGroup is totally broken, and it will leak many AIGroups in AI matches (or matches that use AI scripts) and that will slow down iterating over `std::list<AIGroup *> m_groupList`.
AIGroup has a fundamental memory management flaw with its `AIGroup::remove` function. It deletes itself when all members are removed, which means that any non-AIGroup members holding a reference to that AIGroup will dangle when it is deleted.
This happens all the time in `GameLogic::logicMessageDispatcher` with its `currentlySelectedGroup` variable. It holds objects in a AIGroup, but …

[GEN][ZH] Fix AIGroup memory management and leaks

---

.github/workflows/build-toolchain.yml
CMakePresets.json
cmake/compilers.cmake

~~Created a custom cmake toolchain file for using the vc6 compiler with the ninja generator~~
Switching from nmake to multithreaded ninja reduces compile times by an order of magnitude

[CMAKE] Enable multithreaded compilation for VC6 builds

---

Generals/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/RailedTransportAIUpdate.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/RailedTransportAIUpdate.cpp

- Fixes: #1072 
This PR fixes a crash that occurs when a civilian ferry is being used without being properly setup. 
When the go button is pressed the ferry will cause a crash if it is missing the waypoints for the path that it would travel along.
So we have to test that we have a valid waypoint from the path before choosing to move, if we have no valid waypoints then we also need to reset the `inTransit` variable.

[GEN][ZH] Fix crash when using a Civilian Ferry that has no waypoint path

---

Generals/Code/GameEngine/Source/GameLogic/Map/SidesList.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Map/SidesList.cpp

This change prevents reading invalid data from 'nti', 'm_teams' in TeamsInfoRec::addTeam() to make the compiler happy.
This never is a runtime problem with the way m_teams is currently allocated in this class, but the compiler rightfully warns about this because the code would not have been safe in cases where `m_numTeams` could have been larger than `m_numTeamsAllocated + 8`.
I also simplified/optimized some other code, but it is all in the realms of refactoring and no logic changes.
```
GeneralsMD\Code\GameEngine\Source\GameLogic\Map\SidesList.cpp(1145): warning C6385: Reading invalid data from 'nti':  the readable size is '(unsigned int)*4' bytes, but '8' bytes may be read.
GeneralsMD\Code\GameEngine\Source\GameLogic\Map\SidesList.cpp(1153): warning C6385: Reading invalid data from …
```

[GEN][ZH] Prevent reading invalid data from 'nti', 'm_teams' in TeamsInfoRec::addTeam()

---

Generals/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp

Fixes #1174
The mouse cursor now correctly changes to its beacon placement state when the user is in a beacon placement context _without requiring an object to be selected_.
https://github.com/user-attachments/assets/7220b622-1db9-403b-a9d3-9394f5b9d3c0
This is achieved by adding a case to allow a `MSG_VALID_GUICOMMAND_HINT` message to be returned from `CommandXlat` when the user is in a beacon placement context, which is then received by the `HintSpyTranslator` and sent to the `InGameUI` where the cursor is appropriately updated.

[GEN][ZH] Fix beacon mouse cursor not showing while nothing is selected

---

Core/GameEngine/CMakeLists.txt
Core/GameEngine/Include/Common/STLUtils.h
Generals/Code/GameEngine/Include/Common/GameEngine.h
Generals/Code/GameEngine/Include/Common/Radar.h
Generals/Code/GameEngine/Include/Common/STLTypedefs.h
Generals/Code/GameEngine/Source/Common/GameEngine.cpp
Generals/Code/GameEngine/Source/Common/System/Radar.cpp
Generals/Code/GameEngineDevice/Include/W3DDevice/Common/W3DRadar.h
Generals/Code/GameEngineDevice/Source/W3DDevice/Common/System/W3DRadar.cpp
Generals/GameEngine/Include/Common/STLUtils.h
GeneralsMD/Code/GameEngine/Include/Common/GameEngine.h
GeneralsMD/Code/GameEngine/Include/Common/Radar.h
GeneralsMD/Code/GameEngine/Include/Common/STLTypedefs.h
GeneralsMD/Code/GameEngine/Source/Common/GameEngine.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/Radar.cpp
GeneralsMD/Code/GameEngineDevice/Include/W3DDevice/Common/W3DRadar.h
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/Common/System/W3DRadar.cpp

* Merge after #1036
* Fixes #1034
When a Hero unit is killed, a heap-use-after-free is hit in W3DRadar::drawHeroIcon().
This happens because W3DRadar::m_cachedHeroPosList contains pointers to object positions, which are never cleaned up when the objects are destroyed.
To solve this problem, the cache Hero list has been reworked and tied to the established `addObject` and `removeObject` functions.
This fix also revealed a problem with the subsystems reset where cross dependencies can cause issues on GameEngine::reset. This is fixed as well.
I expect that this change fixes the user facing bug #1034. Not tested.
```
=================================================================
==18020==ERROR: AddressSanitizer: heap-use-after-free on address 0x50db3338 at pc 0x00d2c932 bp 0x018ff258 sp …
```

[GEN][ZH] Fix heap-use-after-free in W3DRadar::drawHeroIcon()

---

Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWaterTracks.cpp
GeneralsMD/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DTreeBuffer.h
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DTreeBuffer.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWaterTracks.cpp

- Fixes: https://github.com/TheSuperHackers/GeneralsGameCode/issues/117
This PR fixes the abnormal animations of Trees, water and waves within Zero Hour and Partly within Generals.
Generals does not have the same Tree managment code that Zero Hour has.
For the Water movement, it only required moving a block of code into the already present block that limited the updates to the logic tick rate.
For waves, they had naively added a fixed update time of 33ms, even though the code already functioned properly if it had the actual time since last update passed into the render functions. This resulted in the waves updating quicker than they should when the client FPS went above 30.
The tree code required little extra code to limit the update of the tree sway without affecting the rendering.
I …

[GEN][ZH] Decouple tree, water and wave movements from client FPS

---

GeneralsMD/Code/GameEngine/Include/Common/Energy.h

- Fixes: https://github.com/TheSuperHackers/GeneralsGameCode/issues/53
This PR prevents a mismatch from occuring in a new game when a previous game had the players power sabotaged.
Since the `m_powerSabotagedTillFrame` variable was not being reset, the game would think the players power was still sabotaged when starting a new game. 
This is due to the `m_powerSabotagedTillFrame` value being greater than the current frame number, this then makes the game think the power is sabotaged.

[ZH] Fix multiplayer mismatch in a new game after exiting the previous game while a player was power sabotaged

---

Generals/Code/GameEngine/Source/Common/System/BuildAssistant.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/BuildAssistant.cpp

- Relates To: #1200 
This PR fixes the ordering of deselection logic within the build assistants `sellObject()` function.
I came across this while resolving #1200 and it corrects the object handling for removing the required object from the current selected objects.
In the original ordering, the object being sold was not being removed from it's original AiGroup and put into a new AIGroup within `Player::getCurrentSelectionAsAIGroup()` when it was called by `GameLogic::deselectObject()`.
This is because `getCurrentSelectionAsAiGroup` tests if an object is selectable before placing it in an AiGroup.
This meant that subsequent code within `GameLogic::deselectObject()` was not working as intended.
At the moment there should not be any user facing changes with this.

[GEN][ZH] Fix object deselection logic in BuildAssistant::sellObject()

---

Generals/Code/GameEngine/Include/GameClient/Display.h
Generals/Code/GameEngine/Source/GameClient/MessageStream/LookAtXlat.cpp
Generals/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DDisplay.h
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
Generals/Code/Tools/GUIEdit/Include/GUIEditDisplay.h
GeneralsMD/Code/GameEngine/Include/GameClient/Display.h
GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/LookAtXlat.cpp
GeneralsMD/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DDisplay.h
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
GeneralsMD/Code/Tools/GUIEdit/Include/GUIEditDisplay.h

- Relates to: https://github.com/TheSuperHackers/GeneralsGameCode/issues/83
This PR fixes the rate of viewPort scrolling to make it independent of the game clients FPS, this allows the scrolling to be consistent across the whole FPS range. This also makes the scroll speed setting work properly.
As the cameras movement is updated in the game client and not the game logic, this leaves it tied to the game clients current FPS. This can result in the camera moving faster at higher FPS as it takes the same movement step in each message update.
This helps the most when the FPS is in excess of the original target FPS of 30. And also helps within replays when fast forwarding as the FPS is completely uncapped at this point.

[GEN][ZH] Make viewport scroll speed frame rate independent

---

Generals/Code/GameEngine/Include/Common/SparseMatchFinder.h
Generals/Code/GameEngine/Include/Common/ThingTemplate.h
Generals/Code/GameEngine/Include/GameLogic/ArmorSet.h
Generals/Code/GameEngine/Include/GameLogic/WeaponSet.h
GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h
GeneralsMD/Code/GameEngine/Include/Common/ThingTemplate.h
GeneralsMD/Code/GameEngine/Include/GameLogic/ArmorSet.h
GeneralsMD/Code/GameEngine/Include/GameLogic/WeaponSet.h

* Fixes #856
* Closes #1194
This change fixes #856 and is an alternative implementation to #1194.

[GEN][ZH] Fix ThingTemplate copying to prevent multiplayer mismatch with original Shell Map and custom Maps

---

Generals/Code/Tools/WorldBuilder/src/OpenMap.cpp
Generals/Code/Tools/WorldBuilder/src/SaveMap.cpp
GeneralsMD/Code/Tools/WorldBuilder/src/OpenMap.cpp
GeneralsMD/Code/Tools/WorldBuilder/src/SaveMap.cpp

* Resolves #1189
* Partially resolves #1116
This change enables the System Maps tab in World Builder without RTS_DEBUG. This makes the GUI more consistent accross configurations.

[GEN][ZH] Show the System Maps tab in World Builder without RTS_DEBUG

---

Generals/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBar.cpp
Generals/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBar.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp

*Squash and merge*
- Closes: #73 
- Related To: #850 
This PR removes the early return that was preventing the command bar size control from working during replays.

[GEN][ZH] Enable Control Bar toggle for Replay playback and match observers

---

Generals/Code/GameEngine/Include/Common/GlobalData.h
Generals/Code/GameEngine/Include/Common/UserPreferences.h
Generals/Code/GameEngine/Include/GameClient/InGameUI.h
Generals/Code/GameEngine/Source/Common/GlobalData.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp
Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DInGameUI.cpp
GeneralsMD/Code/GameEngine/Include/Common/GlobalData.h
GeneralsMD/Code/GameEngine/Include/Common/UserPreferences.h
GeneralsMD/Code/GameEngine/Include/GameClient/InGameUI.h
GeneralsMD/Code/GameEngine/Source/Common/GlobalData.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/InGameUI.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DInGameUI.cpp

**Squash and merge**
- Resolves #903
- Relates To: #850 
This PR implements the system clock and game time. They can be stylised and moved by adding the relevant fields to the inGameUi.ini file.
The system time is just currently offset from the left while the game time is positioned relative to the right side of the viewport.
This is to replicate how they are implemented within GenTool.
They are enabled by default for now to a font size of 8, but can also be disabled in the options.ini by setting their font size to 0.
The following will disable them independently if added to the options.ini.
```
SystemTimeFontSize = 0
GameTimeFontSize = 0
```
EDIT: Updated example with latest version
EDIT2: Updated once more with the now grey frame string
Example:

[GEN][ZH] Implement System Time and Game Time display

---

Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp

This change fixes and removes the lower and upper Scroll Speed boundaries.
- Min Scroll Speed is now 1 instead of 0.
- Max Scroll Speed is now uncapped instead of 100. This means that the ScrollFactor above 100 is no longer lost on game restart. And the user can set any scroll speed he likes.
- The Scroll Speed slider no longer overwrites the ScrollFactor in the Options.ini if it is not set to a recognized range (10 - 145). The Slider Range is defined in OptionsMenu.wnd:SliderScrollSpeed (data).

[GEN][ZH] Fix and remove Scroll Speed limits

---

Generals/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptEngine.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptEngine.cpp

* Fixes #1271
This change fixes use of invalidated iterator in `ScriptEngine::reset()`.
The problem is that `cleanupSequentialScript()` erases the iterator and invalidates it. In practice it is not a problem, but it is technically illegal.
The simpler fix here would have been:
```cpp
VecSequentialScriptPtrIt seqScriptIt;
for (seqScriptIt = m_sequentialScripts.begin(); seqScriptIt != m_sequentialScripts.end(); ) {
seqScriptIt = cleanupSequentialScript(seqScriptIt, TRUE);
```
But I chose against this because `cleanupSequentialScript` is risky. It has a null check at the beginning which will lead to no erasure, in which case this loop would never finish.
So I fixed it safe.

[GEN][ZH] Fix use of invalidated iterator in ScriptEngine::reset()

---

Core/Libraries/Source/WWVegas/WW3D2/prim_anim.h

Followup for #888
The PR above made the codebase compatible with clang, but also incompatible with VS2019. This PR should make it work on all relevant compilers: VC6, VS2019, VS2022 and clang.

[CORE] Make game compile in VS2019

---

Generals/Code/GameEngine/Source/Common/System/GameMemoryNull.cpp
Generals/Code/Main/WinMain.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/GameMemoryNull.cpp
GeneralsMD/Code/Main/WinMain.cpp

* Follow up for #1275
This change fixes the Null Memory Manager that was not working correctly after #1275.

[GEN][ZH] Fix Null Memory Manager issues introduced by #1275

---

Generals/Code/GameEngine/Source/GameLogic/Object/Contain/GarrisonContain.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/GarrisonContain.cpp

- Resolves #1282 
- Follow up on #783 
**Context**: PR #783 relocated a `DEBUG_ASSERTCRASH` outside the `for`-loop, which now triggers unexpectedly in the shell map scenario. This occurs because `containList` is empty in the shell map, meaning the assertion—previously nested and bypassed when the loop was skipped—is now always evaluated.
**Fix**: Update the assertion to also validate that `containList` is empty, ensuring consistent behavior regardless of loop execution.

[GEN][ZH] Fix incorrect garrison points debug assert hit in Shell Map

---

Generals/Code/GameEngine/Source/GameClient/MessageStream/LookAtXlat.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/LookAtXlat.cpp

- Merge After: #1026 
This PR fixes the right mouse button scrolling which was not originally affected by adjusting the scroll options in the options menu.
It cleans up the original implementation and implemented the functionality properly. The original code never did what it was meant to do when it comes to scaling the RMB scroll speed.
The main factor that affects the movement in the code is the factor that measures the mouse position away from the anchor point.
The extra added factor in the original code added an insignificant addition to the movement that was not perceivable.
In the fixed code we take the length of the mouse position from anchor to get the magnitude of the movement, then normalise the mouses position vector from the acnchor point. This allows us to properly normalise …

[GEN][ZH] Fix up the right mouse button scrolling to properly normalize its movement and correctly apply the Scroll Speed modifier

---

Generals/Code/GameEngine/Include/Common/Radar.h
Generals/Code/GameEngine/Source/Common/System/Radar.cpp
Generals/Code/GameEngineDevice/Include/W3DDevice/Common/W3DRadar.h
Generals/Code/GameEngineDevice/Source/W3DDevice/Common/System/W3DRadar.cpp
GeneralsMD/Code/GameEngine/Include/Common/Radar.h
GeneralsMD/Code/GameEngine/Source/Common/System/Radar.cpp
GeneralsMD/Code/GameEngineDevice/Include/W3DDevice/Common/W3DRadar.h
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/Common/System/W3DRadar.cpp

* Fixes #1246
* Follow up for #1240
* Follow up for #1035
This change fixes #1246, which was introduced with #1035 and #1240. There were actually 3 bugs remaining:
1. Hero Radar icons on garrisoned building were not removed or updated from the Radar
2. Hero Radar icons would stack inside garrisons
3. Hero Radar icons would move to fire ports when shooting, which looked irritating
To fix that, I reinstanted the "calcHero" code that the original EA code had, in combination with code that takes care of cleaning up the object pointers to avoid dangling.
---
I did experiment with several implementations and there are many pitfalls when doing it just not the right way. I tried removing and adding Geros and Buildings containing Heros on containing and uncontaining, but that was doomed with …

[GEN][ZH] Fix Hero Radar icon garrison issues introduced by #1035

---

Generals/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/HackInternetAIUpdate.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/HackInternetAIUpdate.cpp

- Fixes: #223
- Closes: #399 
This PR is an alternate / updated implementation of an earlier orphaned PR
This PR prevents hackers that are currently hacking from packing then unpacking again when told to hack the internet.
This often occurs when they are part of a selection of hackers which are idling or hacking and are ordered to hack the internet.

[GEN][ZH] Fix China Hackers unnecessarily packing and unpacking when ordered to hack while already hacking

---

Core/GameEngine/Include/Common/XferCRC.h
Core/GameEngine/Source/Common/System/XferCRC.cpp

This PR refactors the XferCRC to make the code branchless and to remove the winsock dependency within it.
There may be minimal performance improvement from this as other factors will need changing in the data being passed to the CRC to further improve the performance.
The winsock dependency has been replaced with the endian compat library instead.

[CORE] Reduce cost of XferCRC::xferImplementation by 60%

---

Generals/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp
Generals/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp

- closes: #334 
This PR is an updated implementation of an earlier orphaned PR
This PR backports the multi selection blocks put in place by Kris Morness that make it harder to perform the scud bug and other building related bugs.

[GEN] Backport fix to prevent building multi-selection from Zero Hour

---

Generals/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp

- Merge after #1306
- Resolves #74 
- Related to #850  
The chat toggle function is blocked by a the `isActivePlayer` check, which checks if a player is either an observer or dead (note that an observer is also classified as a 'dead' player).
I have not removed this check from team chat functionality (backspace), because observers are not in a team. Observer messages are never send to active players anyways. There is a safeguard for that further on in the chat logic.
~~An additional blocker prevented the observer chat to work after surrender. The player template is changed to observer and resets a number of data entries related to network information. This information is used to determine the value of `player->IsMultiplayer()`, causing it to return false. The chat function uses this to …

[GEN][ZH] Enable Chat for Observers

---

Generals/Code/GameEngine/Source/GameLogic/Object/Object.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Object.cpp

* Fixes https://github.com/TheSuperHackers/GeneralsGameCode/issues/937
Disabling a power plant with a microwave tank immediately decreases the power level even if that power plant is still under construction. If the power plant is destroyed while disabled the reduction becomes permanent.

[GEN][ZH] No longer adjust the power level for disabled Power Plants that are still under construction

---

Generals/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp
GeneralsMD/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp

- Resolves #66
- Related to #850  
Issue caused by and operator having higher precedence and therefore missing parenthesis.

[GEN][ZH] Fix broken Player muting for Observer

---

GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DPropBuffer.cpp

This change fixes the RenderObjClass memory leaks in W3DPropBuffer. Is Zero Hour specific issue.
Tested by loading into Shell Map, into 1 Skirmish Map, and exit game. It would leak about 200 kb in this test.

[ZH] Fix RenderObjClass memory leaks in W3DPropBuffer

---

Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8renderer.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8renderer.h
Generals/Code/Libraries/Source/WWVegas/WW3D2/hlod.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/meshgeometry.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/BaseHeightMap.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dx8renderer.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dx8renderer.h
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/hlod.cpp
GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/meshgeometry.cpp

As I was investigating memory leaks I saw a few places that warranted adding asserts for null pointers, just to be safe. This change fixes nothing.
There currently is a memory leak with render tasks but I have not been able to figure out what the problem is. The `DX8TextureCategoryClass::Clear_Render_List` function is now properly implemented and an assert was added to the destructor: It did not solve it. But it is a start for further investigations.

[GEN][ZH] Add a few checks to warn of memory leaks

---

GeneralsMD/Code/GameEngine/Source/Common/RTS/Player.cpp

This fixes the broken money deposit and withdraw audio and academy income record.
The issue is caused by copying the Money class after the Money player index was already set. It is Zero Hour specific, because Generals does deposit the money correctly.
An alternative/supplementary fix here would be to exclude `Money::m_playerIndex` from copying in the Money class. I am not 100% sure if that meets expectations for Money.
I noticed this Money issue when testing the "Free Build" debug command.

[ZH] Fix broken money deposit and withdraw audio and academy income record

---

Core/GameEngine/Source/Common/Audio/GameAudio.cpp

This change simplifies how audio settings are accessed in `AudioManager`. The null tests in `AudioManager::init` are not necessary, because the INI code would throw if the AudioSettings.ini could not be loaded and `AudioSettings` could not be created, plus `AudioManager` and other code would crash elsewhere anyway.
Practically nothing changes.

[CORE] Simplify how audio settings are accessed in AudioManager

---

Core/GameEngine/Source/Common/Audio/GameAudio.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLLobbyMenu.cpp
Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp
Generals/Code/GameEngine/Source/GameClient/MessageStream/MetaEvent.cpp
Generals/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp
Generals/Code/GameEngine/Source/GameNetwork/FirewallHelper.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameLogic/W3DGhostObject.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLLobbyMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/InGameUI.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/MetaEvent.cpp
GeneralsMD/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp
GeneralsMD/Code/GameEngine/Source/GameNetwork/FirewallHelper.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameLogic/W3DGhostObject.cpp

Observed a crash when using a Saboteur to steal cash in a debug build - caused by a missing object in a call to `DEBUG_ASSERTCRASH` in `GameAudio.cpp`. This change adds the missing object and a few others (found via regex expression - `DEBUG_.+\(\s*("([^"]*%[^"]*)")\s*\)`).
Affected assertions are now correctly shown instead of crashing the game.

fix(log): Fix missing debug log arguments

---

Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp

* Follow up for #1170
This PR is a small fixup pr in which the value zero was not being considered when saving the game and sytem time font sizes in the game options.
Zero is used to disabled the game time and will eventually be input by the user through the options menu.

fix(options): Fix System Time and Game Time settings not loading and applying correctly

---

Generals/Code/GameEngine/Include/GameLogic/AIGuard.h
Generals/Code/GameEngine/Include/GameLogic/AITNGuard.h
Generals/Code/GameEngine/Source/GameLogic/AI/AIGuard.cpp
Generals/Code/GameEngine/Source/GameLogic/AI/AITNGuard.cpp
GeneralsMD/Code/GameEngine/Include/GameLogic/AIGuard.h
GeneralsMD/Code/GameEngine/Include/GameLogic/AIGuardRetaliate.h
GeneralsMD/Code/GameEngine/Include/GameLogic/AITNGuard.h
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIGuard.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIGuardRetaliate.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AITNGuard.cpp

This PR fixes memory leaks within AiGuard states that internally allocate other states.
These leaks occur when an AI state machine is destroyed due to the state machines only calling `onExit` on their currently selected state. All other states are simply deleted from the state machines state map.
As none of the states cleaned up within their destructors, this resulted in the observed leaking child states.

fix(ai): Fix memory leaks in AIGuard states

---

cmake/compilers.cmake
cmake/config-build.cmake

This PR adds a cmake option to make VC6 generate builds with full debug information.
This does slow down the build process so it disabled by default.
This sets the compiler options `/Zi` and sets the build pools to 1 as generating the full debug info is not supported with VC6 when multi-threaded builds are used.

build(debug): Add CMake option to generate full debug information for VC6 builds

---

Generals/Code/GameEngine/Source/Common/System/Debug.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/Debug.cpp

* Fixes #1365
* Follow up for #1275
This change fixes the memory corruption in DebugCrash().
It has 2 commits. The first is the bug fix. The second is fixing a few more theoretical offenders in Debug.cpp.
The corruption was introduced by #1275 and only manifested as a runtime issue in VC6 Debug because of #858.

bugfix(debug): Fix memory corruption in DebugCrash()

---

GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIPlayer.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AISkirmishPlayer.cpp

This change fixes a debug compile error when logging is turned off. Only happens with Zero Hour. Generals somehow already has the correct #ifdef.
```
GeneralsMD\Code\GameEngine\Source\GameLogic\AI\AISkirmishPlayer.cpp(813) : error C4101: 'to' : unreferenced local variable
```

build(debug): Fix GeneralsMD debug compile error when logging is turned off

---

Core/GameEngine/Source/Common/Audio/GameAudio.cpp

* Fixes #169
This change fixes muted audio after regaining window focus. Does not happen always.
This issue can happen because `AudioManager::loseFocus` can be called twice (depending on what Windows sends us), in which case `m_savedValues` would be written a second time, with all 0 values, and therefore restore 0 values on regaining focus.

bugfix(audio): Fix muted audio after regaining window focus

---

Core/GameEngine/Source/Common/Audio/GameAudio.cpp
Generals/Code/GameEngine/Source/Common/System/Debug.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/Debug.cpp

Add some headless checks required for this PR: https://github.com/TheSuperHackers/GeneralsGameCode/pull/1366

tweak(debug): Add more headless checks in preparation for the CI Replay Check

---

GeneralsMD/Code/Main/WinMain.cpp

* Fixes #1394
* Follow up for #799
This change fixes the thread unsafe reference counting of AsciiString.
It was previously introduced by merging Generals code into Zero Hour code.

bugfix(asciistring): Fix thread unsafe reference counting of AsciiString

---

.github/workflows/build-toolchain.yml

GitHub has announced that `windows-latest` label in GitHub Actions will migrate from Windows Server 2022 to Windows Server 2025 beginning September 2, 2025: [GitHub Announcement](https://github.blog/changelog/2025-07-31-github-actions-new-apis-and-windows-latest-migration-notice/#windows-latest-image-label-migration)
To maintain the stability of the builds we should remain on `windows-2022` until we ourselves are at a stable state.

ci(build): Ensure runner uses windows-2022 image for build jobs

---

Generals/Code/GameEngine/Source/Common/GameEngine.cpp
Generals/Code/GameEngine/Source/GameClient/GameText.cpp
GeneralsMD/Code/GameEngine/Source/Common/GameEngine.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GameText.cpp

* Follow up for #1309
This change prevents crashing in WorldBuilder, MapCacheBuilder by moving updateWindowTitle() out of GameText class. It was crashing, because `GameText::init()` is calling `GameText::updateWindowTitle()` when `TheVersion` is NULL.
The Game Window Title is game specific, so it does not need to execute in tools. World Builder sets its Window Name elsewhere anyway. It also makes no sense that GameText class would own this Window Title update.

bugfix(gametext): Prevent crashing in WorldBuilder, MapCacheBuilder by moving updateWindowTitle() out of GameText class

---

Core/Tools/ImagePacker/Source/WinMain.cpp
Core/Tools/MapCacheBuilder/Source/WinMain.cpp
Generals/Code/Tools/GUIEdit/Source/WinMain.cpp
Generals/Code/Tools/WorldBuilder/src/WorldBuilder.cpp
GeneralsMD/Code/Tools/GUIEdit/Source/WinMain.cpp
GeneralsMD/Code/Tools/WorldBuilder/src/WorldBuilder.cpp

* Follow up for #1275
This change fixes Release debug logging in tools.

fix(debug): Fix Release logging in tools

---

Core/Libraries/Source/WWVegas/WWLib/cpudetect.cpp
Core/Libraries/Source/WWVegas/WWLib/cpudetect.h

Memory detection would be incorrect on systems with > 4GB. Verson info detection is incorrect on Windows 8 and later and if manifested for an earlier version than currently running on.

fix(cpudetect): Fix version and memory detection

---

Core/GameEngine/Include/Common/STLUtils.h
Generals/Code/GameEngine/Include/GameClient/InGameUI.h
Generals/Code/GameEngine/Include/GameLogic/GameLogic.h
Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp
GeneralsMD/Code/GameEngine/Include/GameClient/InGameUI.h
GeneralsMD/Code/GameEngine/Source/GameClient/InGameUI.cpp

Fixes #1333
Selecting idle workers via the Select Next Idle Worker button now always selects the next unique selectable and correctly selects top-level containers.
https://github.com/user-attachments/assets/183eddde-ef1f-4c45-863a-0f9b7c32d73a

bugfix(controls): Fix and improve next idle worker selection with contained workers

---

Core/GameEngine/Include/Common/file.h

This change fixes a small documentation error that we added to the File flags.

docs(file): Fix incorrect comment in File class flags

---

Generals/Code/GameEngine/Include/GameClient/InGameUI.h
Generals/Code/GameEngine/Include/GameLogic/GameLogic.h
Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp
Generals/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp
GeneralsMD/Code/GameEngine/Include/GameClient/InGameUI.h
GeneralsMD/Code/GameEngine/Source/GameClient/InGameUI.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp

* Fixes #1332
* Alternative solution to #1334
Centering the camera on a group by double-pressing a group selection hotkey (0 - 9) will now reselect the group if it was deselected.
Technically either one of the two commits fixes the issue. Setting `m_lastGroupSelGroup = -1;` on global deselect is essentially replicating the existing behaviour of selecting something else (where the last group is also set to -1) - which also allows the group to be selected again - whereas the `performSelection` logic adjustment acts as more of a safer catch-all in case the selection can be lost by other means.

bugfix(controls): Fix double-press group selection logic not reselecting deselected groups

---

Generals/Code/GameEngine/Source/GameLogic/Object/Object.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Object.cpp

- Fixes: #999 
- Relates to TheSuperHackers/GeneralsGamePatch#404
This PR fixes a game crash caused when a unit is created with veterancy and the object has an upgrade unlocked that attempts to apply a terrain decal. This can be reproduced with the chemical suits upgrade of the USA and is likely the reason why the chemical suit upgrade is disabled on USA pilots.
When an object is created the thing factory runs through all of it's behaviour modules and calls their `onCreate()` function if there is one available.
Units created with veterancy have the veterancyGainCreate module applied to them. This module iterates over all of the objects behaviour modules and forces them to update their status.
If the chemical suits upgrade or any other upgrade that applies a terrain decal is unlocked then …

bugfix(object): Fix crash when an object is created with veterancy and an upgrade that applies a terrain decal

---

Generals/Code/GameEngine/Source/GameLogic/Object/Contain/OpenContain.cpp

* Follow up for #1019
This fixes the compile errors in Generals' `OpenContain::processDamageToContained` with `RETAIL_COMPATIBLE_CRC 0`.

fix(contain): Fix compile errors with RETAIL_COMPATIBLE_CRC 0

---

scripts/cpp/unify_move_files.py

* Split off of #1383
This python script helps moving files for the unification effort.
Is now a separate change because it is a pain to base everything on the GameMemory unify change when that gets review comments.

chore(script): Add script to help move files to Core

---

Generals/Code/GameEngine/Include/Common/GlobalData.h
Generals/Code/GameEngine/Include/GameClient/ControlBar.h
Generals/Code/GameEngine/Source/Common/CommandLine.cpp
Generals/Code/GameEngine/Source/Common/GameEngine.cpp
Generals/Code/GameEngine/Source/Common/GlobalData.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBar.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/ControlBarCallback.cpp
Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp
GeneralsMD/Code/GameEngine/Include/Common/GlobalData.h
GeneralsMD/Code/GameEngine/Include/GameClient/ControlBar.h
GeneralsMD/Code/GameEngine/Source/Common/CommandLine.cpp
GeneralsMD/Code/GameEngine/Source/Common/GameEngine.cpp
GeneralsMD/Code/GameEngine/Source/Common/GlobalData.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBar.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/ControlBarCallback.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/InGameUI.cpp

* Relates to #850
* Resolves #1284
This change implements the fullviewport support for 'Control Bar Pro' Addons like GenTool did.
New command line argument is "-forcefullviewport"
And file at "GenTool/fullviewport.dat" is read too.

feat(controlbar): Implement full viewport support for 'Control Bar Pro' Addons

---

.github/workflows/check-replays.yml

Follow-up for #1366
Fixes a syntax error

ci: Fix up Replay Checker

---

Generals/Code/GameEngine/Include/Common/Recorder.h
Generals/Code/GameEngine/Source/Common/Recorder.cpp
GeneralsMD/Code/GameEngine/Include/Common/Recorder.h
GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp

- Merge After: #1385 
- Merge After: #1414
This PR converts the Recorder class to use the game file system for replay saving and playback.
This was done to cleanup the implementation and to eventually make use of data buffering during playback.
With this change, streaming of replays that are actively being recorded should still be possible.
~~I set the replay file buffer to 8192 bytes, this is 16x larger than the standard buffer size.~~
~~When other bottlenecks are removed in future, this change should show bigger contributions to replay playback speed.~~
- EDIT: The File buffer tweak will be split out into a seperate PR: #1389

refactor(recorder): Replace fopen with FileSystem in Replay Recorder

---

Generals/Code/Libraries/Source/WWVegas/WW3D2/textureloader.cpp
Generals/Code/Libraries/Source/WWVegas/WW3D2/texturethumbnail.cpp

* Follow up for #1410
Texture loader has an infinite loop:
```
while (poweroftwodepth< depth)
{
poweroftwodepth <<= 1;
}
```
where depth is 3435973836 (uninitialised) and poweroftwodepth is 0
There was two spots where depth was uninitialized, setting to 0 fixed it. The depth is not actually used by the code so its safe to be 0. Unfortunately ZH code is significantly different, maybe it should be unified soon (it calls Get_Texture_Information to get the depth, which is better if we need depth later).

bugfix(textureloader): Fix Generals game hang with TextureLoader::Validate_Texture_Size

---

GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Object.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptActions.cpp

* Fixes #1419
This change fixes a missing null check on the best object in the else block of `ScriptActions::doTeamUseCommandButtonOnNearestObjectType`, which leads to a crash.

bugfix(script): Fix crash if nearest command button target is not found

---

Generals/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp

This change prevents dead objects from blocking positional context commands.
In the retail game, the hover hint / mouse-over logic correctly checks for dead objects and thus returns a valid hint for movement special powers, or force-fire; however the command logic is missing this check and so the respective commands fail. This leads to a confusing state where the cursor is telling the player that they can perform an action, and yet the action does not occur. This can make a huge difference in the heat of battle when attempting to move a unit or perform an action at a position, and the command inexplicably fails.
Cannot command the Dozer to move to the location of the dead Ranger
https://github.com/user-attachments/assets/e1e4bce1-80d8-4b0f-baca-4fc015ab7e4d
Can command the Dozer to move …

bugfix(input): Prevent dead units from blocking positional context commands

---

Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/GUICallbacks/W3DControlBar.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/GUICallbacks/W3DControlBar.cpp

This change shows the experience bar for the selected player when observing (both live matches and replays). The conditions are identical to the power bar display conditions.

bugfix(controlbar): Show the experience bar for the selected player when observing

---

Generals/Code/GameEngine/Source/GameNetwork/NetCommandMsg.cpp
Generals/Code/GameEngine/Source/GameNetwork/NetPacket.cpp
GeneralsMD/Code/GameEngine/Source/GameNetwork/NetCommandMsg.cpp
GeneralsMD/Code/GameEngine/Source/GameNetwork/NetPacket.cpp

This PR is a first pass on the network message parsing classes.
The network messaging works based on serialised messages that can vary in length.
The message headers can vary in size and are constructed by setting or reading tokens in a specific ordering.
This first parse optimises some of the logical handling by replacing long `if else if` blocks with switches.
~~It also makes the message length retrieval functions return fixed sizes instead of calculating their size on the fly.~~
~~Some of the message length functions have to perform calculations as their messages can be variable in length.
But where these occur i have filled in the prior size of the header to cut down on the calculations.~~
~~Inside the message size functions, i commented out but maintained the original message size …

refactor(network): Replace branches with switches in Network command parse functions

---

Generals/Code/GameEngine/Source/Common/Recorder.cpp
GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp

- Merge After: #1233 
This PR changes how replay files are opened so they open with a larger than standard file buffer.
This is to help reduce disk access and aid replay playback speed in the long run.
As other bottlenecks are removed in the future, this PR should present a biffer performance boost.

tweak(recorder): Improve performance of Replay playback slightly by increasing the Replay file read buffer to 8192 bytes

---

Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp

This change simply allows camera zooming while the game is paused.
Unclear to me why this was not allowed originally. Perhaps just a mistake.

tweak(input): Allow camera zoom while game is paused

---

Generals/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp

Fixes #1447
Follow-up to #1430
This change disables the "set prevention of left click deselection in alternate mouse mode for one click" logic when cancelling building placement - a leftover side-effect from the improvement introduced with #1430.
The respective `setPreventLeftClickDeselectionInAlternateMouseModeForOneClick` method is used to prevent a worker from being deselected when placing a structure, which is considered a click on empty terrain that would otherwise deselect the unit. In this case, as building placement has been cancelled, it is set back to false so that clicking an empty area will deselect the worker as expected.

bugfix(input): No longer require two clicks to deselect worker after cancelling building placement in alternate mouse mode

---

Generals/Code/GameEngine/Include/GameLogic/ExperienceTracker.h
Generals/Code/GameEngine/Include/GameLogic/Module/ActiveBody.h
Generals/Code/GameEngine/Include/GameLogic/Module/BodyModule.h
Generals/Code/GameEngine/Include/GameLogic/Module/InactiveBody.h
Generals/Code/GameEngine/Include/GameLogic/Object.h
Generals/Code/GameEngine/Source/GameLogic/Object/Body/ActiveBody.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/ExperienceTracker.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/Object.cpp

This change ports the `provideFeedback` parameter and respective logic regarding the veterancy effect from Zero Hour to Generals. It also fixes a bug in Generals where detected stealth units would not play the veterancy effect.

unify(object): Merge the unit veterancy effect changes including the veterancy effect fix for detected stealth units from Zero Hour

---

Generals/Code/GameEngine/Include/GameLogic/ExperienceTracker.h
Generals/Code/GameEngine/Source/GameLogic/Object/Create/VeterancyGainCreate.cpp
Generals/Code/GameEngine/Source/GameLogic/Object/ExperienceTracker.cpp
GeneralsMD/Code/GameEngine/Include/GameLogic/ExperienceTracker.h
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Create/VeterancyGainCreate.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/ExperienceTracker.cpp

Fixes #51
This change fixes the veterancy effect appearing at the map origin for spawned units (produced from buildings, dropped from planes, spawned by scripts, etc.).
It turns out `Object::onVeterancyLevelChanged` has an optional `provideFeedback` parameter for playing the veterancy effect, so the solution was to simply pass `false` to it when called via `ExperienceTracker::setMinVeterancyLevel` (which is only called from the offending `VeterancyGainCreate` module).

bugfix(object): Fix veterancy effect spawning at the map origin when a veteran unit is produced

---

Generals/Code/GameEngine/Source/GameClient/MessageStream/LookAtXlat.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/LookAtXlat.cpp

Spinning the mouse wheel to zoom the camera in / out no longer stops any active camera scrolling.

bugfix(input): Prevent mouse wheel from stopping camera scrolling

---

Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/MainMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/MainMenu.cpp

By default, the cursor and menu are hidden to display the shell map. When using the `--quickstart` option, the shell map is replaced with a static background, but the player still had to move the mouse before the cursor and menu appeared.
This change explicitly checks if the shell map is enabled, ensuring the mouse and menu are shown immediately when it is not.

tweak(menu): Show mouse and menu immediately when shellmap is disabled

---

Generals/Code/GameEngine/Source/GameClient/Drawable.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBar.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3dWaypointBuffer.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/Drawable.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBar.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3dWaypointBuffer.cpp

This change expands object selection information for observers. While a player is selected, the following information is now displayed for selected objects:
- Group numbers / formations
- Ammo
- Passengers / occupants
- Car bombs
- Rally points

tweak(client): Show additional information for selected objects while observing

---

Generals/Code/GameEngine/Source/Common/INI/INI.cpp
GeneralsMD/Code/GameEngine/Source/Common/INI/INI.cpp

This change improves INI whitespace read performance. The existing logic is inefficient as `strlen(tempBuff)` is O(n) and called on every loop iteration, making the loop O(n²). The null terminator is now checked directly and each character is iterated only once, reducing loop complexity to O(n).

perf(ini): Decrease cost of INI::isDeclarationOfType by around 10%

---

Core/GameEngine/Include/Common/AsciiString.h
Core/GameEngine/Include/Common/UnicodeString.h
Core/GameEngine/Source/Common/System/AsciiString.cpp
Core/GameEngine/Source/Common/System/UnicodeString.cpp

* Broken off of #1476
This change implements new constructors for AsciiString, UnicodeString that take a string and max length.

feat(string): Implement functions for AsciiString, UnicodeString that build a new string with a fixed length

---

Generals/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp
Generals/Code/GameEngine/Source/GameClient/MessageStream/MetaEvent.cpp
Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/MetaEvent.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp

* Follow up for #827
This change backports the fast forward instructions text from Zero Hour and adds English substitute text for Fast Forward messages.
The substitute texts are relevant for Generals, because its loca strings do not contain texts for it.

tweak(text): Add English substitute text for Fast Forward messages

---

Generals/Code/GameEngine/Source/GameClient/GUI/HeaderTemplate.cpp
Generals/Code/GameEngine/Source/GameClient/GlobalLanguage.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/HeaderTemplate.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GlobalLanguage.cpp

* Replacement for #1496
This change removes the legacy code for loading Language9x.ini, HeaderTemplate9x.ini for Windows 95, 98, ME systems. It was used by Chinese and Korean localizations only.

refactor(language): Remove legacy code for loading Language9x.ini, HeaderTemplate9x.ini

---

Generals/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/ChinookAIUpdate.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/ChinookAIUpdate.cpp

This change prevents Chinooks from getting stuck when performing Combat Drops into buildings above terrain height.
As can be seen in 1.04 in particular situations on some maps:
https://github.com/user-attachments/assets/e5b8d400-ca91-4a90-a3a2-4061bd46f296

bugfix(aiupdate): Chinooks no longer get stuck when performing Combat Drops into buildings above terrain height

---

GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/SabotageCommandCenterCrateCollide.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/SabotageFakeBuilding.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/SabotageInternetCenterCrateCollide.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/SabotageMilitaryFactoryCrateCollide.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/SabotagePowerPlantCrateCollide.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/SabotageSuperweaponCrateCollide.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/SabotageSupplyCenterCrateCollide.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/SabotageSupplyDropzoneCrateCollide.cpp

* Fixes #1570
* Follow up for #1459
This change prevents the retail CRC mismatch from the changes to Sabotage Crate Collide.

bugfix(collide): Prevent retail CRC mismatch from changes to Sabotage Crate Collide

---

Generals/Code/Tools/GUIEdit/Source/GUIEdit.cpp
GeneralsMD/Code/Tools/GUIEdit/Source/GUIEdit.cpp

This PR fixes a startup crash within GuiEdit that was introduced by changed in Global Languge in PR #1457
This crash occured due to the global language object being initialised before global data in GuiEdit.
Global language is now dependent on being initialised after Global Data. This is due to the recent need for the user data directory string when retrieving options.ini settings within global language.
The user data directory string is initialised when the global data is initialised, resulting in a null string being handled within global languages, resulting in the crash.
For some reason the VS22 builds were immune to the issue. But the VC6 builds would always crash.

fix(guiedit): Fix crash on GuiEdit launch by initializing GlobalLanguage after GlobalData

---

Generals/Code/GameEngine/Source/GameNetwork/Network.cpp
GeneralsMD/Code/GameEngine/Source/GameNetwork/Network.cpp

Fixes #162
This change allows a player's assets to be transferred to their allies upon disconnect.

tweak(network): Transfer assets of disconnected players to allies

---

Core/Libraries/Include/Lib/BaseTypeCore.h
GeneralsMD/Code/GameEngine/Source/GameClient/Eva.cpp

This change removes the ELEMENTS_OF macro which is a duplicate of the ARRAY_SIZE macro.

refactor: Remove ELEMENTS_OF macro

---

Generals/Code/GameEngine/Source/GameLogic/Object/Update/SpecialAbilityUpdate.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/SpecialAbilityUpdate.cpp

This change allows the `EffectValue` defined in the `SpecialAbilityUpdate` module to control the amount of cash stolen by Black Lotus's Cash Hack ability as originally intended.
```
Behavior = SpecialAbilityUpdate ModuleTag_13
SpecialPowerTemplate  = SpecialAbilityBlackLotusStealCashHack
StartAbilityRange     = 150.0
UnpackTime            = 6730 ;animation time is 6730 (changing this will scale anim speed)
PackTime              = 5800 ;animation time is 5800 (changing this will scale anim speed)
PreparationTime       = 6000 ;time to complete hack once prepared (unpacked)
EffectValue           = 1000 ;amount of cash stolen
SpecialObject         = BinaryDataStream
PackSound             = BlackLotusPack
UnpackSound           = BlackLotusUnpack
TriggerSound          = BlackLotusTrigger …
```

bugfix(behavior): Fix hardcoded cash hack value for Black Lotus

---

.github/workflows/weekly-release.yml

**What this PR does?**
This PR complements https://github.com/TheSuperHackers/GeneralsGameCode/pull/1171
Creates a github action to create a weekly release with the latest code changes. It will be scheduled to every moday.
https://github.com/fbraz3/GeneralsGameCode/actions/runs/15689781515
It also can be mannualy triggered, and it have parameters to bypass the code changes check to force a new build
The release notes also have a changelog with all commits since the last release - for the first release it will be limited to the last 10 commits

ci(release): Add weekly pre-releases workflow for Generals and GeneralsMD

---

Core/GameEngine/Include/Common/GameDefines.h
Generals/Code/GameEngine/Include/GameLogic/AIPathfind.h
Generals/Code/GameEngine/Source/GameLogic/AI/AIPathfind.cpp
GeneralsMD/Code/GameEngine/Include/GameLogic/AIPathfind.h
GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIPathfind.cpp

- Fixes: #968 
- Fixes: #980 
- Fixes: #979
These issues are likely also fixed by this, it does not appear to be an issue with moving units on mass but a cascade failure in the pathfinding that can finally get triggered by moving units.
- Fixes: #330 
- Fixes: #81 
--- 
**TODO**
---
This PR fixes the crashing within AI pathing. Which is being caused by a lack of cleanup of pathfinding resources in some return paths. This then results in resource exhaustion and dangling parent cell information that points to invalid cells when a new path is calculated.
It can appear to be triggered when units get stuck or there are mass unit movements. But the pathing can start to fail long before the point of the actual crash in some circumstances.
I am keeping it as a draft for now as better ways of …

bugfix(pathfinder): Fix various crashes in Pathfinder due to inadequate cleanup of pathfinding resources

---

Generals/Code/GameEngine/Source/GameClient/MessageStream/MetaEvent.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/MetaEvent.cpp

While looking into double click code I saw complicated logic in `MetaEventTranslator::translateGameMessage()` and simplified that by elimitating a bunch of extra braches.

refactor(message): Simplify double click related code in MetaEventTranslator::translateGameMessage()

---

Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp

* Relates to #850
This change fixes the camera terrain height adjustment in Replay playback. Originally the camera would not raise or lower when scrolling over a mountain or valley.

bugfix(view): Fix camera terrain height adjustment in Replay playback

---

Generals/Code/GameEngine/Include/GameClient/View.h
Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp
Generals/Code/GameEngine/Source/GameClient/View.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp
GeneralsMD/Code/GameEngine/Include/GameClient/View.h
GeneralsMD/Code/GameEngine/Source/GameClient/InGameUI.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/View.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp

This change fixes camera terrain height adjustment during camera playback in Replay playback. Originally the saved camera would not raise or lower when scrolling over a mountain or valley. This happened because of the (min) and max zoom clamping. Removing the clamping solves this.

bugfix(view): Fix camera terrain height adjustment during camera playback in Replay playback

---

Generals/Code/GameEngine/Include/GameClient/View.h
Generals/Code/GameEngine/Source/GameClient/View.cpp
Generals/Code/GameEngine/Source/GameLogic/System/GameLogicDispatch.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp
GeneralsMD/Code/GameEngine/Include/GameClient/View.h
GeneralsMD/Code/GameEngine/Source/GameClient/View.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogicDispatch.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp

* Follow up for #1451
This change prevents moving the camera with most user inputs during camera playback in Replay playback. The possibility of this behavior was introduced with the render and logic update decoupling. When the logic step is smaller than the render update, then there is room for user input to move the camera after a `MSG_SET_REPLAY_CAMERA` message.
Numpad 5 still causes issues but it is very minor and a different problem.
https://github.com/user-attachments/assets/75e64678-f35f-41d6-aaef-a1f63a8e016e

bugfix(view): Prevent moving the camera with most user inputs during camera playback in Replay playback

---

Generals/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DProjectedShadow.h
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DModelDraw.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DProjectedShadow.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DShadow.cpp
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DScene.cpp
GeneralsMD/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DProjectedShadow.h
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DModelDraw.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DProjectedShadow.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DShadow.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DScene.cpp
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DTreeBuffer.cpp

* Fixes #261
This change fixes the missing tree shadow decals while no object shadow decals exist.
The issue happens because the decal draw bounds are only updated when there are object decal shadows (for example under infantry units).
Map: North America

bugfix(shadow): Fix missing tree shadow decals when no object shadow decals exist

---

Generals/Code/GameEngine/Include/Common/GlobalData.h
Generals/Code/GameEngine/Source/Common/GlobalData.cpp
Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp
GeneralsMD/Code/GameEngine/Include/Common/GlobalData.h
GeneralsMD/Code/GameEngine/Source/Common/GlobalData.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/InGameUI.cpp

* Merge after #1591
This change makes the opacity and shadows of build placement preview objects customizable. It adds new fields `ObjectPlacementOpacity=0..1` and `ObjectPlacementShadows=Yes/No` to GameData.ini.
By default, user facing nothing changes.
I put the mod fields into GameData.ini instead of InGameUI.ini because thematically it does not fit in InGameUI, despite being referenced there.
I have chosen the new fields names because there is precedent in `Object: PlacementViewAngle`.
```
ObjectPlacementOpacity = 0.60
ObjectPlacementShadows = No
```

feat(client): Make opacity and shadows of build placement preview objects customizable

---

Generals/Code/GameEngine/Source/Common/System/BuildAssistant.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/BuildAssistant.cpp

This change prevents the invalid building placement indicator from showing for shrouded objects (an example of which can be seen below).

bugfix(buildassistant): Prevent showing the invalid placement indicator for shrouded objects

---

GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/ActiveBody.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/UndeadBody.cpp

This change prevents bunkered Battle Buses from being subdued indefinitely (demonstrated below).
https://github.com/user-attachments/assets/980cde0e-2d75-4c6d-a386-5d766c478931
As a Battle Bus gains 250 health when entering bunkered mode (400 health → 650 health), the subdual damage threshold can be shifted above the current subdual damage and thus cause the Battle Bus to remain subdued forever. To rectify this, the subdual damage is set to the threshold (max health) on transitioning to the bunkered state to ensure the subdued state is removed when healed.

bugfix(module): GLA Battle Bus can no longer be subdued indefinitely

---

Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp

Fixes #29
This change prevents unit attachments from being visible through fog after exiting a Tunnel Network. The tunnel garrison logic goes through a different pathway and does not add the occupants of open containers (e.g. Avenger turrets) to the partition manager on exit. Unfortunately, this change is not retail compatible (though maybe for the best as it would introduce a disadvantage over retail).
See the comparison below:
https://github.com/user-attachments/assets/dbd376eb-7b99-4634-a709-8a00814e6b86
**Left client:** This change - the blue player cannot see the turret attachment of the green Avenger through the fog ✔️
**Right client:** Retail build - the green player can see the turret attachment of the blue Avenger through the fog ❌

bugfix(contain): Fix unit attachments being visible in fog after exiting a GLA Tunnel Network

---

Generals/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DProjectedShadow.h
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DProjectedShadow.cpp
GeneralsMD/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DProjectedShadow.h
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DProjectedShadow.cpp

This change fixes counting of `W3DProjectedShadowManager::m_numDecalShadows`. This value appears to be not used for anything, so it is inconsequential. I think it was mainly intended for diagnostics.
Interestingly, the count appears to be still not right after the fix. I do see value of 1 even when there are 0 decals in the list, which implies that there is another bug somewhere. I was not able to locate it.

fix(shadow): Fix counting of W3DProjectedShadowManager::m_numDecalShadows

---

Generals/Code/GameEngine/Source/Common/System/BuildAssistant.cpp
GeneralsMD/Code/GameEngine/Source/Common/System/BuildAssistant.cpp

Fixes #1644
This change fixes an issue introduced by #1543 which used local drawable state that was also used by game logic paths, leading to desynchronised behaviour.

bugfix(buildassistant): Fix Network game mismatch by using the correct player index to check shroud status when placing structures

---

Generals/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp

This change fixes the missing toggle for DEMO_TOGGLE_NO_DRAW.
Previously, hitting the forward slash button (US keyboard) in game (with RTS_DEBUG) would disable draw for practically ever. This also happened during debug sessions. Annoying.

bugfix(debug): Fix missing toggle for DEMO_TOGGLE_NO_DRAW

---

Generals/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DWater.h
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp
GeneralsMD/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DWater.h
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp

This change decouples the water movement time step from the render update.

tweak(water): Decouple water movement time step from render update

---

Generals/Code/GameEngine/Include/Common/GlobalData.h
Generals/Code/GameEngine/Include/Common/UserPreferences.h
Generals/Code/GameEngine/Include/GameClient/InGameUI.h
Generals/Code/GameEngine/Source/Common/GlobalData.cpp
Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp
Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp
GeneralsMD/Code/GameEngine/Include/Common/GlobalData.h
GeneralsMD/Code/GameEngine/Include/Common/UserPreferences.h
GeneralsMD/Code/GameEngine/Include/GameClient/InGameUI.h
GeneralsMD/Code/GameEngine/Source/Common/GlobalData.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp
GeneralsMD/Code/GameEngine/Source/GameClient/InGameUI.cpp

- Relates To: #850
- Follow up for: #1170 
This change implements Latency Counter (left), FPS Counter (left), and FPS Limit (left) in Generals and Zero Hour.
They are enabled by default with a size of 8 and positioned before (to the left of) SystemTime, replicating GenTool implementation.
The following options have been added:
```
NetworkLatencyFontSize = 8
RenderFpsFontSize = 8
```
They can be styled and repositioned by adding the relevant fields to the InGameUI.ini data file.
Example: 
- In a Network Game:
- In Menus:
**TODO**
---

feat(ui): Implement simple Latency and FPS display

---

Generals/Code/GameEngine/Include/Common/GameEngine.h
Generals/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DDisplay.h
Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
GeneralsMD/Code/GameEngine/Include/Common/GameEngine.h
GeneralsMD/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DDisplay.h
GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp

This change removes the Munkee übercomplexity and the frame spike filter from W3DDisplay::updateAverageFPS().
The spike filter ignored any frames longer than 500 ms and that does not make sense to keep around.

tweak(fps): Simplify function W3DDisplay::updateAverageFPS() and remove its frame spike filter

---

GeneralsMD/Code/GameEngine/Include/GameLogic/Module/CreateObjectDie.h
GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Die/CreateObjectDie.cpp

This change allows the Sneak Attack to remain selected when it transitions from its spawning object.
A new `TransferSelection` field can now be added to the `CreateObjectDie` module to enable this behaviour.
Note: No other object uses the `TransferPreviousHealth` field, so this field could technically be used to control the reselection behaviour (initially?) and thus be retail compatible. However, it would not make logical sense and would confound the behaviour.
```diff
Object GLASneakAttackTunnelNetworkStart
Behavior             = CreateObjectDie ModuleTag_11
CreationList  = OCL_CreateSneakAttackTunnel
TransferPreviousHealth = Yes
+   TransferSelection = Yes
End
End
```
Feature or bugfix?

tweak(module): Add 'TransferSelection' field to CreateObjectDie INI module to allow transfer selection on object creation
