TheSuperHackers/GeneralsGameCode

cmake/miles.cmake
Brings in fixes to API that solve audio issues.
Fixes #434
=> Bumps version of miles sdk stub.

CMakeLists.txt, CMakePresets.json, Generals/Code/GameEngine/CMakeLists.txt, Generals/Code/Libraries/Source/WWVegas/CMakeLists.txt, Generals/Code/Tools/WW3D/max2w3d/CMakeLists.txt, GeneralsMD/Code/GameEngine/CMakeLists.txt, GeneralsMD/Code/Libraries/Source/WWVegas/CMakeLists.txt, GeneralsMD/Code/Libraries/Source/profile/CMakeLists.txt, GeneralsMD/Code/Tools/WW3D/max2w3d/CMakeLists.txt
Adds additional configure presets to build these on vc6.
Adds an additional config for loading into Visual Studio without breaking ninja.
=> Implement options to control building internal and debug code.

README.md
We probably want a fancy readme with ways to contribute etc but for now just don't say this is an archived project which doesn't accept PR's.
=> README.md: Remove that this project is archived and doesn't accept PRs

Generals/Code/GameEngine/CMakeLists.txt, GeneralsMD/Code/GameEngine/CMakeLists.txt, GeneralsMD/Code/Libraries/CMakeLists.txt, GeneralsMD/Code/Libraries/Source/debug/CMakeLists.txt, GeneralsMD/Code/Libraries/Source/debug/debug_stack.cpp, GeneralsMD/Code/Libraries/Source/profile/CMakeLists.txt, GeneralsMD/Code/Main/CMakeLists.txt, GeneralsMD/Code/Tools/GUIEdit/CMakeLists.txt, GeneralsMD/Code/Tools/ImagePacker/CMakeLists.txt, GeneralsMD/Code/Tools/MapCacheBuilder/CMakeLists.txt, GeneralsMD/Code/Tools/PATCHGET/CMakeLists.txt, GeneralsMD/Code/Tools/ParticleEditor/CMakeLists.txt, GeneralsMD/Code/Tools/WorldBuilder/CMakeLists.txt
Fixes mistake in PR for internal build where a change for debug handling was only partial reverted.
=> Fix building debug and internal builds.

.github/workflows/toolchain-common.yml, Dependencies/Utility/Utility/sstream_adapter.h, GeneralsMD/Code/Tools/mangler/wlib/wdebug.h, GeneralsMD/Code/Tools/matchbot/mydebug.h, GeneralsMD/Code/Tools/matchbot/wlib/wdebug.h
This change fixes the extra tools compile errors.
=> [ZH] Fix stringstream for Zero Hour Tools build

Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DVolumetricShadow.cpp, Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DBridgeBuffer.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/aabtree.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/aabtreebuilder.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/aabtreebuilder.h, Generals/Code/Libraries/Source/WWVegas/WW3D2/boxrobj.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/decalmsh.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/decalmsh.h, Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8renderer.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/dynamesh.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/dynamesh.h, Generals/Code/Libraries/Source/WWVegas/WW3D2/mesh.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/meshgeometry.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/meshgeometry.h, Generals/Code/Libraries/Source/WWVegas/WW3D2/meshmdl.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/meshmdl.h, Generals/Code/Libraries/Source/WWVegas/WW3D2/meshmdlio.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/ringobj.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/seglinerenderer.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/shattersystem.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/sphereobj.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/sphereobj.h, Generals/Code/Libraries/Source/WWVegas/WW3D2/visrasterizer.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/visrasterizer.h
This will simplify unifying the code, the underlaying type for Gen hasn't been changed to Vector3i16 like ZH and remains Vector3i
=> [GEN] Backport TriIndex typedef

GeneralsMD/Code/GameEngine/Include/Common/Debug.h, GeneralsMD/Code/GameEngine/Source/Common/CommandLine.cpp, GeneralsMD/Code/GameEngine/Source/Common/System/Debug.cpp, GeneralsMD/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp, GeneralsMD/Code/GameEngine/Source/GameNetwork/FrameDataManager.cpp, GeneralsMD/Code/GameEngine/Source/GameNetwork/NetPacket.cpp, GeneralsMD/Code/GameEngine/Source/GameNetwork/Network.cpp
Alternatively opposed to removing could implement it for ZH
=> [ZH] Port DEBUG_LOG_LEVEL from Generals

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/config.yml
Updated bug report issue template to add type:Bug and other small improvements
=> [GitHub] Update bug report template

GeneralsMD/Code/GameEngineDevice/Source/Win32Device/GameClient/Win32Mouse.cpp
Seems somehow, they missed adding it to ZH..
=> [ZH] Port mod cursor support from Generals

GeneralsMD/Code/GameEngineDevice/Source/Win32Device/GameClient/Win32DIMouse.cpp
=> [ZH] Fix BitTest macro name in Win32DIMouse.cpp

Generals/CMakeLists.txt, GeneralsMD/CMakeLists.txt
Eventually we want to add a MainPage.dox at some point for some more detailed documentation
=> [CMake] Add doxygen targets for documentation

Generals/Code/Libraries/Source/WWVegas/WWSaveLoad/definition.h, Generals/Code/Libraries/Source/WWVegas/WWSaveLoad/definitionmgr.cpp, Generals/Code/Libraries/Source/WWVegas/WWSaveLoad/editable.h, Generals/Code/Libraries/Source/WWVegas/WWSaveLoad/parameter.cpp, Generals/Code/Libraries/Source/WWVegas/WWSaveLoad/parameter.h, Generals/Code/Libraries/Source/WWVegas/WWSaveLoad/parameterlist.h, Generals/Code/Libraries/Source/WWVegas/WWSaveLoad/saveload.cpp, Generals/Code/Libraries/Source/WWVegas/WWSaveLoad/saveload.h, Generals/Code/Libraries/Source/WWVegas/WWSaveLoad/saveloadstatus.cpp, Generals/Code/Libraries/Source/WWVegas/WWSaveLoad/saveloadstatus.h, Generals/Code/Libraries/Source/WWVegas/WWSaveLoad/twiddler.cpp, Generals/Code/Libraries/Source/WWVegas/Wwutil/mathutil.cpp, Generals/Code/Libraries/Source/WWVegas/Wwutil/mathutil.h, Generals/Code/Libraries/Source/WWVegas/Wwutil/miscutil.cpp
saveload.cpp isn't exactly the same cause it requires bringing WWDebug in line with ZH, and that dir has a whole lot of problems to resolve
Only thing missing there however is profiler calls so it's not too relevant
=> [GEN] Bring WWSaveLoad and WWUtil in line with Zero Hour

Generals/Code/Libraries/Source/WWVegas/WW3D2/bmp2d.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/decalsys.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/part_ldr.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/texproject.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/texture.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/texture.h
=> [GEN] Backport WW3D2's TextureClass dimension functions from Zero Hour

Generals/Code/Libraries/Source/WWVegas/WW3D2/ddsfile.cpp, Generals/Code/Libraries/Source/WWVegas/WW3D2/ddsfile.h
This change backports cube map, volume texture and hsv shift support for DDSFileClass from Zero Hour.
=> [GEN] Backport cube map, volume texture and hsv shift support for DDSFileClass from Zero Hour

GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/texturethumbnail.cpp, GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/texturethumbnail.h
SAGE doesn't use mix or th6 files that Ren and E&B did so this code is useless
=> [ZH] Remove unused code in ThumbnailManagerClass

Generals/Code/GameEngine/Include/GameLogic/ObjectCreationList.h, Generals/Code/GameEngine/Source/GameLogic/Object/ObjectCreationList.cpp
ObjectCreationList : All OCLs return the first object that is created (or NULL if not applicable)
=> [GEN] Backport OCL first object returns from Zero Hour

Generals/Code/Libraries/Source/WWVegas/WW3D2/w3d_file.h
* Follow up for #599
* Follow up for #736
This change replicates #599 and #736 in Generals.
=> [GEN] Add FXShader, BINORMAL, TANGENT chunks from BFME

Generals/Code/GameEngine/Source/GameClient/ClientInstance.cpp, GeneralsMD/Code/GameEngine/Source/GameClient/ClientInstance.cpp
* Follow up for #794
Fixes inverted condition.
=> [GEN][ZH] Fix wrong assert condition in ClientInstance::getInstanceIndex()

Generals/Code/GameEngine/Source/Common/Recorder.cpp, GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp
Simplify the code in `RecorderClass::appendNextCommand()` a bit. No semantic change here.
=> [GEN][ZH] Simplify RecorderClass::appendNextCommand()

Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/QuitMenu.cpp, GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/QuitMenu.cpp
- Split from #864
- Related to #850
=> [GEN][ZH] Fix Diplomacy Screen, Tooltips and Chat not working after surrender

Generals/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp, GeneralsMD/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp, GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DPropBuffer.cpp, GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DTreeBuffer.cpp
* Resolves #942
This change removes the bogus calls to memset.
Practically nothing changes.
=> [GEN][ZH] Remove bogus calls to memset

Generals/Code/GameEngine/Source/Common/RTS/Money.cpp, GeneralsMD/Code/GameEngine/Source/Common/RTS/Money.cpp
* Merge after #1311
This change implements the "Free Build" debug command. Everything was in place for this debug command except for actually modifying the money value.
This change requires #1311 to work properly.
=> [GEN][ZH] Finalize the implementation for the 'Free Build' debug command

Generals/Code/GameEngine/Include/Common/GlobalData.h, Generals/Code/GameEngine/Source/Common/GlobalData.cpp, Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp, GeneralsMD/Code/GameEngine/Include/Common/GlobalData.h, GeneralsMD/Code/GameEngine/Source/Common/GlobalData.cpp, GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp
This change removes unused audio fields in GlobalData.
=> refactor(audio): Remove unused audio fields in GlobalData

Generals/Code/GameEngine/Source/Common/System/Debug.cpp, GeneralsMD/Code/GameEngine/Source/Common/System/Debug.cpp
* Follow up for #1371
Very informative description
=> fix(debug): Fix copypasta in Debug.cpp

Core/GameEngine/Source/Common/Audio/GameAudio.cpp, Generals/Code/GameEngine/Source/Common/System/Debug.cpp, GeneralsMD/Code/GameEngine/Source/Common/System/Debug.cpp
Add some headless checks required for this PR: #1366
=> tweak(debug): Add more headless checks in preparation for the CI Replay Check

Generals/Code/GameEngine/Source/GameLogic/Object/Update/ParticleUplinkCannonUpdate.cpp, GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/ParticleUplinkCannonUpdate.cpp
This PR cleans up some indentation and unnecessary code in `ParticleUplinkCannonUpdate::initiateIntentToDoSpecialPower`.
=> refactor(specialpower): Clean up ParticleUplinkCannonUpdate::initiateIntentToDoSpecialPower

Generals/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp, GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp
This change replaces some duplicate in-line logic with a function call.
=> refactor(input): Simplify click conditions for MSG_RAW_MOUSE_RIGHT_BUTTON_UP

Core/Libraries/Source/Compression/EAC/btreeencode.cpp, Core/Libraries/Source/Compression/EAC/refencode.cpp, Core/Libraries/Source/Compression/LZHCompress/NoxCompress.cpp
Added fixes to avoid memory leaks during error checking that were introduced in the original code.
=> fix(compress): Fix a few memory leaks on fail conditions in Compression code
